(()=>{'use strict';
const STORE='ppc_stream_overlay_v83',CHANNEL='ppc-stream-v83',SUPA='https://cdmzrsvwztndqfwzsumo.supabase.co',PUB='sb_publishable_rRpqFtZ_izENE8u8gTjo9Q_858RVJzl';
const q=new URLSearchParams(location.search),forced=q.get('mode'),overlayId=q.get('overlay'),root=document.getElementById('overlayRoot');
let state=null,sceneIndex=0,lastScene=Date.now(),polling=false,failures=0,status=overlayId?'connecting':'local',timer=null,channel=null,lastMode='',lastSignature='';
const esc=v=>String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const mode=()=>forced||state?.config?.overlayMode||'ranked';
const record=()=>state?.record||{};
const session=()=>state?.session||{};
const deck=()=>state?.deck||{};
function scenes(){const cfg=state?.config?.scenes||{},m=mode();let out=Object.keys(cfg).filter(k=>cfg[k]!==false);if(m==='tournament'||m==='caster')out=out.filter(k=>!['rank','graph'].includes(k));if(!out.length)out=[m==='ranked'?'rank':'tournament'];return out}
function card(kicker,title,sub='',inner=''){return '<section class="pn-shell"><div class="pn-accent"></div><div class="pn-body"><div class="pn-kicker">'+esc(kicker)+'</div><div class="pn-title">'+title+'</div>'+(sub?'<div class="pn-sub">'+sub+'</div>':'')+inner+'</div></section>'}
function stat(label,value,cls=''){return '<div class="pn-stat"><span>'+esc(label)+'</span><strong class="'+cls+'">'+esc(value)+'</strong></div>'}
function statusCard(title,msg,bad=false){return '<section class="pn-shell pn-status"><div class="pn-accent"></div><div class="pn-body"><div class="pn-kicker">POCKETNEXUS OVERLAY</div><div class="pn-title '+(bad?'pn-bad':'')+'">'+esc(title)+'</div><div class="pn-sub">'+esc(msg)+'</div></div></section>'}
function fmtRecord(v){if(v&&typeof v==='object')return [n(v.wins??v.w),n(v.losses??v.l),n(v.ties??v.t)].filter((x,i)=>i<2||x>0).join('-');const s=String(v??'').trim();return s&&s!=='[object Object]'?s:'—'}
function fmtRound(v){const s=String(v??'').trim();if(!s)return '—';if(/^\d+$/.test(s))return 'Round '+s;return s}
function renderScene(key){
 const r=record(),s=session(),d=deck(),rank=state?.rank||{},t=state?.tournament||{},c=state?.caster||{},match=state?.lastMatch,mu=state?.matchup||{};
 if(key==='deck'){const imgs=(d.cards||[]).filter(x=>x.image).slice(0,3).map(x=>'<img src="'+esc(x.image)+'" alt="">').join('');return card('CURRENT DECK',esc(d.name||'No deck selected'),esc(d.archetype||d.energy||'Pokémon TCG Pocket'),'<div class="pn-deck">'+(imgs?'<div class="pn-art">'+imgs+'</div>':'')+'<div class="pn-stats" style="flex:1">'+stat('Session',s?((s.wins||0)+'-'+(s.losses||0)):'—')+stat('Streak',r.streak??'—')+stat('Win rate',n(r.winRate).toFixed(1)+'%')+stat('RP',rank.points??'—')+'</div></div>')}
 if(key==='decklist')return card('20-CARD DECK LIST',esc(d.name||'No deck selected'),'', '<div class="pn-list">'+((d.cards||[]).map(x=>'<div><b>'+esc(x.name)+'</b><br>×'+n(x.qty,1)+'</div>').join('')||'<div>No saved card list</div>')+'</div>');
 if(key==='lastmatch')return card('LAST MATCH',match?'<span class="'+(match.result==='win'?'pn-good':match.result==='loss'?'pn-bad':'pn-warn')+'">'+esc(String(match.result||'').toUpperCase())+'</span>':'No match yet',match?esc((match.deckName||d.name||'Deck')+' vs '+(match.opponentArchetype||'Opponent')):'Waiting for the first result',match?'<div class="pn-stats">'+stat('RP change',(n(match.rankChange)>0?'+':'')+n(match.rankChange),n(match.rankChange)>=0?'pn-good':'pn-bad')+stat('RP total',match.rankAfter??rank.points??'—')+'</div>':'');
 if(key==='matchup')return card('MATCHUP',esc((d.name||'Your deck')+' vs '+(state?.opponent||'Opponent')),'','<div class="pn-stats">'+stat('Session',(mu.session?.w||0)+'-'+(mu.session?.l||0)+'-'+(mu.session?.t||0))+stat('Lifetime',(mu.lifetime?.w||0)+'-'+(mu.lifetime?.l||0)+'-'+(mu.lifetime?.t||0))+'</div>');
 if(key==='graph'){const p=(state?.rpJourney||[n(rank.points)]).map(Number),lo=Math.min(...p),hi=Math.max(...p),delta=Math.max(1,hi-lo),pts=p.map((v,i)=>(i*100/Math.max(1,p.length-1))+','+(90-(v-lo)/delta*75)).join(' ');return card('LIVE RP JOURNEY',esc((rank.points||0)+' RP'),esc(rank.tier||'Ranked'),'<svg class="pn-graph" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="'+pts+'"/></svg><div class="pn-sub">Low '+lo+' • High '+hi+'</div>')}
 if(key==='tournament'){if(mode()==='caster')return card('CASTER • '+esc(t.name||'Tournament'),'<div class="pn-row"><div class="pn-player">'+esc(c.a||'Player A')+'</div><div class="pn-score">'+n(c.scoreA)+' — '+n(c.scoreB)+'</div><div class="pn-player">'+esc(c.b||'Player B')+'</div></div>',esc(fmtRound(t.round)+' • '+(t.stage||'Stage')));return card('TOURNAMENT',esc(t.name||'Tournament'),'', '<div class="pn-stats">'+stat('Round',fmtRound(t.round))+stat('Record',fmtRecord(t.record))+stat('Stage',t.stage||'—')+'</div>')}
 return card('LIVE RANK',esc(rank.tier||'Ranked'),esc((rank.points||0)+' RP'),'<div class="pn-stats">'+stat('Record',(r.wins||0)+'-'+(r.losses||0)+'-'+(r.ties||0))+stat('Streak',r.streak??'—')+stat('Session RP',(n(s.rankChange)>0?'+':'')+n(s.rankChange),n(s.rankChange)>=0?'pn-good':'pn-bad')+stat('Win rate',n(r.winRate).toFixed(1)+'%')+'</div>');
}
function render(){
 if(!state){root.innerHTML=status==='revoked'?statusCard('Overlay revoked','Generate a fresh browser-source URL in Streamer Center.',true):status==='invalid'?statusCard('Overlay not found','Copy a fresh browser-source URL from Streamer Center.',true):status==='error'?statusCard('Reconnecting…','PocketNexus is retrying the overlay connection.',true):statusCard('Connecting…','Waiting for Streamer Center.');return}
 const cfg=state.config||{},list=scenes();sceneIndex=Math.max(0,Math.min(sceneIndex,list.length-1));document.body.className=cfg.theme||'dark';root.style.opacity=String(Math.max(.1,Math.min(1,n(cfg.opacity,90)/100)));root.style.fontSize=Math.max(70,Math.min(150,n(cfg.fontScale??cfg.scale,100)))+'%';
 const hud=cfg.persistentHud!==false&&mode()==='ranked'?'<div class="pn-hud"><span class="pn-dot"></span>'+esc((state.rank?.tier||'Ranked')+' • '+(state.rank?.points||0)+' RP • '+(record().streak??'—'))+'</div>':'';
 root.innerHTML=hud+renderScene(list[sceneIndex]);
}
function signature(next,activeMode){try{return JSON.stringify([activeMode||'',next])}catch{return String(Date.now())}}
function apply(next,activeMode,remote=false){if(!next)return;const sig=signature(next,activeMode);if(remote&&sig===lastSignature)return false;lastSignature=sig;state=next;if(forced){state.config=state.config||{};state.config.overlayMode=forced}const m=forced||activeMode||mode();if(lastMode&&lastMode!==m){sceneIndex=0;lastScene=Date.now()}lastMode=m;if(!remote){const requested=n(next?.config?.sceneIndex,NaN);if(Number.isFinite(requested))sceneIndex=Math.max(0,requested)%Math.max(1,scenes().length)}render();return true}
async function pull(){if(!overlayId||polling)return;polling=true;const ctl=new AbortController(),timeout=setTimeout(()=>ctl.abort(),5000);try{const res=await fetch(SUPA+'/rest/v1/rpc/read_stream_overlay?ts='+Date.now(),{method:'POST',headers:{apikey:PUB,'Content-Type':'application/json','Cache-Control':'no-store'},body:JSON.stringify({p_overlay_id:overlayId}),cache:'no-store',signal:ctl.signal});if(!res.ok)throw Error('HTTP '+res.status);const out=await res.json();status=out?.status||'error';if(status==='ok'){const env=out.state||{},m=forced||env.activeMode||'ranked',next=env.modes?.[m];if(next){failures=0;apply(next,m,true);return}}state=null;render()}catch(e){if(++failures>=2){status='error';state=null;render()}}finally{clearTimeout(timeout);polling=false}}
function initLocal(){try{channel=new BroadcastChannel(CHANNEL);channel.onmessage=e=>{const m=e.data||{};if(m.type==='state'&&m.data)apply(m.data,mode(),false);if(m.type==='ping')channel.postMessage({type:'pong',from:'overlay-v4',at:Date.now()})};channel.postMessage({type:'overlay-ready',version:4,at:Date.now()})}catch{}window.addEventListener('storage',e=>{if(e.key===STORE){try{const x=JSON.parse(e.newValue||'null');if(x)apply(x,mode(),false)}catch{}}});try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(x)apply(x,mode(),false);else render()}catch{render()}}
if(overlayId){render();pull();timer=setInterval(pull,5000)}else initLocal();
setInterval(()=>{if(state?.config?.sceneRotation!==false&&Date.now()-lastScene>=Math.max(10,n(state?.config?.sceneSeconds,120))*1000){const list=scenes();sceneIndex=(sceneIndex+1)%Math.max(1,list.length);lastScene=Date.now();render()}},1000);
window.addEventListener('beforeunload',()=>{if(timer)clearInterval(timer);try{channel?.close()}catch{}});
})();