/* PocketNexus V8.68.3 — public Limitless decklist/QR overlay layer. */
(function(){
'use strict';
const mode=document.body.dataset.mode||new URLSearchParams(location.search).get('mode')||'ranked';if(!['tournament','caster'].includes(mode))return;
const STORE='ppc_stream_overlay_v868_'+mode,CHANNEL='ppc-stream-v868-'+mode;let payload=null;
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function cards(deck){const raw=deck?.cards;if(!raw)return[];if(Array.isArray(raw))return raw.map((x,i)=>{if(typeof x==='string')return{name:x,count:1};return{name:x?.name||x?.cardName||x?.card||`Card ${i+1}`,count:Number(x?.count??x?.quantity??x?.qty??1)||1}});if(typeof raw==='object')return Object.entries(raw).map(([name,count])=>({name,count:Number(count)||1}));return[]}
function qrSrc(url){return url?`https://api.qrserver.com/v1/create-qr-code/?size=220x220&margin=8&data=${encodeURIComponent(url)}`:''}
function deckPanel(player,label){const deck=player?.decklist,entries=cards(deck),url=player?.publicDeckUrl||'';return `<section class="pnBroadcastDeck"><div class="pnBroadcastDeckHead"><div><small>${label}</small><strong>${esc(player?.name||'Unknown Player')}</strong><span>${esc(deck?.archetype||player?.deck||'Archetype unavailable')}</span></div>${url?`<img class="pnBroadcastQr" src="${esc(qrSrc(url))}" alt="Decklist QR code">`:''}</div>${entries.length?`<div class="pnBroadcastDeckList">${entries.slice(0,30).map(x=>`<div><b>${esc(x.count)}×</b><span>${esc(x.name)}</span></div>`).join('')}</div><footer>${entries.reduce((n,x)=>n+(Number(x.count)||0),0)} cards • Public decklist</footer>`:`<div class="pnBroadcastDeckUnavailable">Full decklist is not public for this player.</div>`}</section>`}
function render(){const root=document.getElementById('root');if(!root)return;root.querySelector('.pnLiveTableBroadcast')?.remove();const live=payload?.liveTable;if(!live)return;const layer=document.createElement('div');layer.className='pnLiveTableBroadcast '+mode;layer.innerHTML=mode==='caster'?`<div class="pnBroadcastMatchMeta"><span>${esc(live.tournamentName||'Tournament')}</span><b>Round ${esc(live.round)} • Table ${esc(live.table)}</b></div><div class="pnBroadcastDeckGrid">${deckPanel(live.playerA,'PLAYER A')}${deckPanel(live.playerB,'PLAYER B')}</div>`:(()=>{const tracked=String(payload?.config?.followPlayerId||'');const me=String(live.playerB?.id)===tracked?live.playerB:live.playerA;const opp=me===live.playerA?live.playerB:live.playerA;return `<div class="pnBroadcastMatchMeta"><span>${esc(live.tournamentName||'Tournament')}</span><b>Round ${esc(live.round)} • Table ${esc(live.table)}</b></div><div class="pnBroadcastTournamentNames"><div><small>PLAYER</small><strong>${esc(me?.name||'Player')}</strong><span>${esc(me?.decklist?.archetype||me?.deck||'Archetype unavailable')}</span></div><em>VS</em><div><small>OPPONENT</small><strong>${esc(opp?.name||'Opponent')}</strong><span>${esc(opp?.decklist?.archetype||opp?.deck||'Archetype unavailable')}</span></div></div><div class="pnBroadcastDeckGrid">${deckPanel(me,'YOUR PUBLIC DECK')}${deckPanel(opp,'OPPONENT PUBLIC DECK')}</div>`})();root.appendChild(layer)}
function receive(x){payload=x;render()}
try{const ch=new BroadcastChannel(CHANNEL);ch.onmessage=e=>{if(e.data?.type==='state')receive(e.data.data)}}catch{}
window.addEventListener('storage',e=>{if(e.key===STORE)receive(load())});
const mo=new MutationObserver(()=>{if(payload&&!document.querySelector('.pnLiveTableBroadcast'))render()});const root=document.getElementById('root');if(root)mo.observe(root,{childList:true,subtree:false});receive(load());
})();