/* PocketNexus V8.68.1 — shared OBS browser-source renderer */
(function(){
'use strict';
const params=new URLSearchParams(location.search),embedded=params.get('embedded')==='1';
const mode=document.body.dataset.mode||params.get('mode')||'ranked';
const STORE='ppc_stream_overlay_v868_'+mode,CHANNEL='ppc-stream-v868-'+mode;let d=null;
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const root=document.getElementById('root');
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function cfg(){return d?.config||{}}
function metric(label,value){return `<div class="metric"><small>${label}</small><strong>${value}</strong></div>`}
function ranked(){const c=cfg(),r=d?.rank||{},rec=d?.record||{},s=d?.session,deck=d?.deck||{};if(c.preset==='compact')return `<div class="bar compact"><b>${esc(r.tier)}</b><span>${Number(r.points||0)} RP</span><span>${rec.wins||0}-${rec.losses||0}</span></div>`;if(c.preset==='minimal')return `<div class="card minimal"><small>RANKED</small><b>${esc(r.tier)}</b><span>${Number(r.points||0)} RP</span></div>`;if(c.preset==='match')return `<div class="card match"><div class="ey">MATCH FOCUS</div><h1>${esc(deck.name||'Current Deck')} <span>vs</span> ${esc(d?.opponent||'Opponent')}</h1><div class="metrics">${metric('RP',Number(r.points||0))}${metric('SESSION',s?`${s.wins}-${s.losses}`:'—')}${metric('LAST',d?.lastMatch?String(d.lastMatch.result).toUpperCase():'—')}</div></div>`;return `<div class="card full ranked"><div class="ey">RANKED STREAM</div><div class="hero"><div><h1>${esc(r.tier)}</h1><b>${Number(r.points||0)} RP</b></div><div class="deck"><small>CURRENT DECK</small><strong>${esc(deck.name||'—')}</strong></div></div><div class="metrics">${metric('RECORD',`${rec.wins||0}-${rec.losses||0}`)}${metric('WIN RATE',`${Number(rec.winRate||0).toFixed(1)}%`)}${metric('SESSION RP',s?`${s.rankChange>=0?'+':''}${s.rankChange}`:'—')}</div></div>`}
function tournament(){const t=d?.tournament||{},deck=d?.deck||{};return `<div class="card tournament full"><div class="ey">TOURNAMENT PLAYER</div><h1>${esc(t.name||'Tournament')}</h1><div class="subline"><span>${esc(t.stage||'Swiss')}</span><span>${esc(t.round||'Round 1')}</span><b>${esc(t.record||'0-0')}</b></div><div class="metrics">${metric('CURRENT DECK',esc(deck.name||'—'))}${metric('OPPONENT',esc(d?.opponent||'—'))}</div></div>`}
function caster(){const t=d?.tournament||{},x=d?.caster||{};return `<div class="scoreboard top"><div class="event"><small>${esc(t.name||'TOURNAMENT')}</small><span>${esc(t.stage||'Stage')} • ${esc(t.round||'Round')}</span></div><div class="player a"><b>${esc(x.a||'Player A')}</b></div><div class="score">${Number(x.scoreA||0)} — ${Number(x.scoreB||0)}</div><div class="player b"><b>${esc(x.b||'Player B')}</b></div></div>`}
function render(){if(!d){root.innerHTML='';return}const c=cfg();document.body.className=`theme-${c.theme||'dark'} anchor-${c.anchor||'bottom-center'}`;root.style.opacity=String(Math.max(.1,Math.min(1,Number(c.opacity||95)/100)));root.style.setProperty('--scale',String(Math.max(.7,Math.min(1.5,Number(c.scale||100)/100))));root.innerHTML=mode==='caster'?caster():mode==='tournament'?tournament():ranked()}
function receive(data){if(data){d=data;render()}}
try{const ch=new BroadcastChannel(CHANNEL);ch.onmessage=e=>{if(e.data?.type==='state')receive(e.data.data);if(e.data?.type==='ping')ch.postMessage({type:'pong',mode,embedded,at:Date.now()})};ch.postMessage({type:'overlay-ready',mode,embedded,at:Date.now()});if(!embedded)setInterval(()=>ch.postMessage({type:'overlay-heartbeat',mode,embedded:false,at:Date.now()}),3000)}catch{}
window.addEventListener('storage',e=>{if(e.key===STORE)receive(load())});d=load();render();
})();