/* PocketNexus V8.68.0 — shared OBS browser-source renderer */
(function(){
'use strict';
const mode=document.body.dataset.mode||new URLSearchParams(location.search).get('mode')||'ranked';
const STORE='ppc_stream_overlay_v868_'+mode,CHANNEL='ppc-stream-v868-'+mode;let d=null,scene=0,lastSwitch=Date.now();
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const root=document.getElementById('root');
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function cfg(){return d?.config||{}}
function metric(label,value){return `<div class="metric"><small>${label}</small><strong>${value}</strong></div>`}
function ranked(){const c=cfg(),r=d?.rank||{},rec=d?.record||{},s=d?.session,deck=d?.deck||{},mu=d?.matchup||{};if(c.preset==='compact')return `<div class="bar compact"><b>${esc(r.tier)}</b><span>${Number(r.points||0)} RP</span>${c.showRecord!==false?`<span>${rec.wins||0}-${rec.losses||0}</span>`:''}${c.showSessionRP!==false?`<span>${s?`${s.rankChange>=0?'+':''}${s.rankChange} RP`:'—'}</span>`:''}${c.showStreak!==false?`<span>${esc(rec.streak||'—')}</span>`:''}</div>`;if(c.preset==='minimal')return `<div class="card minimal"><small>RANKED</small><b>${esc(r.tier)}</b><span>${Number(r.points||0)} RP</span>${c.showStreak!==false?`<em>${esc(rec.streak||'—')}</em>`:''}</div>`;if(c.preset==='match')return `<div class="card match"><div class="ey">MATCH FOCUS</div><h1>${esc(deck.name||'Current Deck')} <span>vs</span> ${esc(d?.opponent||'Opponent')}</h1><div class="metrics">${metric('RP',Number(r.points||0))}${metric('SESSION',s?`${s.wins}-${s.losses}`:'—')}${metric('LAST',d?.lastMatch?String(d.lastMatch.result).toUpperCase():'—')}</div></div>`;const recent=c.showRecent!==false?`<div class="recent">${(d?.recent||[]).slice(0,c.recentCount||5).map(x=>`<div><b class="${x.result==='win'?'good':'bad'}">${x.result==='win'?'W':'L'}</b><span>${esc(x.opponentArchetype)}</span><small>${x.rankChange>=0?'+':''}${x.rankChange} RP</small></div>`).join('')||'<small>No recent matches</small>'}</div>`:'';return `<div class="card full ranked"><div class="ey">RANKED STREAM</div><div class="hero"><div>${c.showRank!==false?`<h1>${esc(r.tier)}</h1><b>${Number(r.points||0)} RP</b>`:''}</div>${c.showDeck!==false?`<div class="deck"><small>CURRENT DECK</small><strong>${esc(deck.name||'—')}</strong></div>`:''}</div><div class="metrics">${c.showRecord!==false?metric('RECORD',`${rec.wins||0}-${rec.losses||0}`):''}${c.showWinRate!==false?metric('WIN RATE',`${Number(rec.winRate||0).toFixed(1)}%`):''}${c.showStreak!==false?metric('STREAK',esc(rec.streak||'—')):''}${c.showSessionRP!==false?metric('SESSION RP',s?`${s.rankChange>=0?'+':''}${s.rankChange}`:'—'):''}</div>${c.showOpponent!==false&&d?.opponent?`<div class="matchup"><span>VS ${esc(d.opponent)}</span>${c.showMatchup!==false&&mu.lifetime?`<small>${mu.lifetime.w}-${mu.lifetime.l} lifetime</small>`:''}</div>`:''}${recent}</div>`}
function tournament(){const c=cfg(),t=d?.tournament||{},deck=d?.deck||{};if(c.preset==='minimal')return `<div class="bar tournament"><b>${esc(t.name||'Tournament')}</b><span>${esc(t.round||'Round')}</span><span>${esc(t.record||'0-0')}</span></div>`;if(c.preset==='match')return `<div class="card match tournament"><div class="ey">${esc(t.name||'TOURNAMENT')}</div><h1>${esc(t.round||'Round')} • ${esc(t.stage||'Stage')}</h1><div class="vsline"><strong>${esc(deck.name||'Current Deck')}</strong><span>vs</span><strong>${esc(d?.opponent||'Opponent')}</strong></div><div class="score">${esc(t.record||'0-0')}</div></div>`;if(c.preset==='deck')return `<div class="card tournament"><div class="ey">DECK SHOWCASE</div><h1>${esc(deck.name||'Current Deck')}</h1><div class="deckcards">${(deck.cards||[]).filter(x=>x.image).slice(0,4).map(x=>`<img src="${esc(x.image)}" alt="${esc(x.name)}">`).join('')||'<p>No deck artwork available.</p>'}</div></div>`;return `<div class="card tournament full"><div class="ey">TOURNAMENT PLAYER</div><h1>${esc(t.name||'Tournament')}</h1><div class="subline"><span>${esc(t.stage||'Swiss')}</span><span>${esc(t.round||'Round 1')}</span><b>${esc(t.record||'0-0')}</b></div><div class="metrics">${metric('CURRENT DECK',esc(deck.name||'—'))}${metric('OPPONENT',esc(d?.opponent||'—'))}${metric('ROUND',esc(t.round||'—'))}</div></div>`}
function caster(){const c=cfg(),t=d?.tournament||{},x=d?.caster||{};const a=esc(x.a||'Player A'),b=esc(x.b||'Player B'),sa=Number(x.scoreA||0),sb=Number(x.scoreB||0);if(c.preset==='minimal')return `<div class="bar caster"><b>${a}</b><strong>${sa} — ${sb}</strong><b>${b}</b></div>`;if(c.preset==='center')return `<div class="card caster center"><div class="ey">${esc(t.name||'TOURNAMENT')}</div><h1>${a} <span>vs</span> ${b}</h1><div class="score huge">${sa} — ${sb}</div><small>${esc(t.round||'Round')} • ${esc(t.stage||'Stage')}</small></div>`;return `<div class="scoreboard ${c.preset||'top'}"><div class="event"><small>${esc(t.name||'TOURNAMENT')}</small><span>${esc(t.stage||'Stage')} • ${esc(t.round||'Round')}</span></div><div class="player a"><b>${a}</b><small>PLAYER A</small></div><div class="score">${sa} — ${sb}</div><div class="player b"><b>${b}</b><small>PLAYER B</small></div></div>`}
function anchorClass(a){return 'anchor-'+(a||'bottom-center')}
function render(){if(!d){root.innerHTML='';return}const c=cfg();document.body.className=`theme-${c.theme||'dark'} ${anchorClass(c.anchor)}`;root.style.opacity=String(Math.max(.1,Math.min(1,Number(c.opacity||95)/100)));root.style.setProperty('--scale',String(Math.max(.7,Math.min(1.5,Number(c.scale||100)/100))));root.innerHTML=mode==='caster'?caster():mode==='tournament'?tournament():ranked()}
function receive(data){if(!data)return;d=data;render()}
try{const ch=new BroadcastChannel(CHANNEL);ch.onmessage=e=>{if(e.data?.type==='state')receive(e.data.data);if(e.data?.type==='ping')ch.postMessage({type:'pong',mode,at:Date.now()})};ch.postMessage({type:'overlay-ready',mode,at:Date.now()})}catch{}
window.addEventListener('storage',e=>{if(e.key===STORE)receive(load())});d=load();render();setInterval(()=>{const c=cfg();if(mode==='ranked'&&c.sceneRotation&&Date.now()-lastSwitch>=Number(c.sceneSeconds||10)*1000){scene++;lastSwitch=Date.now();render()}},1000);
})();