/* V8.43 Battle + Streamer readability pass. Logic/storage intentionally unchanged. */
(function(){
 const oldMatchCard=window.matchCardHtml;
 window.sessionCardHtml=function(s){
  const x=sessionSummary(s), rp=x.rankedMatches?(x.rpTracked?`${x.rankChange>0?'+':''}${x.rankChange} RP`:'RP not tracked'):'Casual / no RP';
  return `<article class="sessionCard ${x.matches===0?'sessionEmpty':''}"><div class="sessionCardHead"><div class="sessionCardTitle"><strong>${esc(s.name||'Battle Session')}</strong><small>${new Date(s.start).toLocaleString()}</small></div><span class="pill">${s.end?'Ended':'Active'}</span></div><div class="sessionMetricGrid"><div><small>Record</small><strong>${x.w}-${x.l}</strong></div><div><small>Win rate</small><strong>${x.matches?x.wr.toFixed(1)+'%':'—'}</strong></div><div><small>Ranked RP</small><strong>${rp}</strong></div><div><small>Duration</small><strong>${x.durationMinutes} min</strong></div><div><small>Current streak</small><strong>${x.streak.type==='none'?'—':(x.streak.type==='win'?'W':'L')+x.streak.count}</strong></div></div><div class="sessionMatchups"><div><small>Most faced</small><span>${esc(x.mostCommon)}</span></div><div><small>Best matchup</small><span>${esc(x.bestMatchup)}</span></div><div><small>Hardest matchup</small><span>${esc(x.hardestMatchup)}</span></div></div></article>`;
 };
 window.battleFiltersHtml=function(){
  const rows=normalizedMatches(),decks=[...new Set(rows.map(m=>m.deckName).filter(Boolean))].sort(),opps=[...new Set(rows.map(m=>m.opponentArchetype).filter(Boolean))].sort();
  const sessions=(state.sessions||[]).map(s=>({s,count:rows.filter(m=>m.sessionId===s.id).length})).filter(x=>x.count>0).sort((a,b)=>(b.s.start||0)-(a.s.start||0));
  return `<details class="historyFilters"><summary><strong>Filters</strong><span class="muted tiny">Search, deck, opponent, mode, session & date</span></summary><div class="historyToolbar"><input id="bhSearch" placeholder="Search history…" oninput="state.battlePrefs.historyPage=0;renderBattleHistory()"><select id="bhDeck" onchange="state.battlePrefs.historyPage=0;renderBattleHistory()"><option value="">All decks</option>${decks.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="bhOpp" onchange="state.battlePrefs.historyPage=0;renderBattleHistory()"><option value="">All opponents</option>${opps.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="bhResult" onchange="state.battlePrefs.historyPage=0;renderBattleHistory()"><option value="">Win + Loss</option><option value="win">Wins</option><option value="loss">Losses</option></select><select id="bhTurn" onchange="state.battlePrefs.historyPage=0;renderBattleHistory()"><option value="">Any turn order</option><option value="first">Went First</option><option value="second">Went Second</option><option value="unknown">Unknown</option></select><select id="bhMode" onchange="state.battlePrefs.historyPage=0;renderBattleHistory()"><option value="">All modes</option><option value="ranked">Ranked</option><option value="casual">Casual</option><option value="tournament">Tournament</option><option value="private">Private</option><option value="other">Other</option></select><select id="bhSession" onchange="state.battlePrefs.historyPage=0;renderBattleHistory()"><option value="">All sessions</option><option value="__none__">No session</option>${sessions.map(({s,count})=>`<option value="${esc(s.id)}">${esc(s.name||'Battle Session')} · ${count} matches</option>`).join('')}</select><input id="bhDate" type="date" aria-label="Filter by date" onchange="state.battlePrefs.historyPage=0;renderBattleHistory()"><select id="bhSort" onchange="renderBattleHistory()"><option value="new">Newest</option><option value="old">Oldest</option><option value="gain">RP gained</option><option value="lossrank">RP lost</option><option value="opp">Opponent</option><option value="deck">My deck</option></select></div></details>`;
 };
 window.matchCardHtml=function(m){
  const session=(state.sessions||[]).find(s=>s.id===m.sessionId), order=m.turnOrder==='first'?'First':m.turnOrder==='second'?'Second':'Unknown';
  return `<article class="matchCard" onclick="openMatchDetails('${m.id}')"><div class="matchCardRow"><span class="resultPill ${m.result}">${m.result==='win'?'W':'L'}</span><div class="matchCardMain"><strong>${esc(m.deckName)} <span class="muted">vs ${esc(m.opponentArchetype)}</span></strong><div class="matchCardMeta"><span>${esc(m.gameMode)}</span><span>${order}</span>${session?`<span>${esc(session.name||'Session')}</span>`:''}</div></div><div class="matchCardSide"><strong>${m.rankChange>0?'+':''}${m.rankChange||0} RP</strong><small>${new Date(m.timestamp).toLocaleString()}</small></div></div></article>`;
 };
 const oldRenderHistory=window.renderBattleHistory;
 window.renderBattleHistory=function(){oldRenderHistory();const root=document.getElementById('battleHistory');if(root){const cards=[...root.querySelectorAll('.matchCard')];if(cards.length){const wrap=document.createElement('div');wrap.className='battleHistoryList';cards[0].before(wrap);cards.forEach(c=>wrap.appendChild(c));}}};
})();
