/* PocketNexus V8.69.0 — Draft Mode foundation
   Local-first draft assistant. Matches are played in Pokémon TCG Pocket. */
(function(){
'use strict';
if(window.PPCDraftMode)return;
const KEY='ppc_draft_v8690';
const WORD_A=['PLASMA','ULTRA','NOVA','ROCKET','MASTER','RIVAL','POCKET','AURORA','PRIME','VOLT'];
const WORD_B=['DRAGON','SPARK','MOON','WING','MEW','EEVEE','PIKA','PHANTOM','COMET','NEXUS'];
const safe=(fn,f=null)=>{try{return fn()}catch{return f}};
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function id(){return crypto?.randomUUID?.()||('draft-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2))}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function code(){const bytes=new Uint8Array(2);crypto?.getRandomValues?.(bytes);const n=((bytes[0]||Math.random()*255)<<8)+(bytes[1]||Math.random()*255);const suffix=n.toString(36).toUpperCase().padStart(2,'0').slice(-2);return `${pick(WORD_A)}-${pick(WORD_B)}-${suffix}`}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function write(x){localStorage.setItem(KEY,JSON.stringify(x));return x}
function newSession(opts={}){return write({id:id(),roomCode:code(),status:'lobby',mode:opts.mode||'rival',opponent:opts.opponent||'cpu',createdAt:new Date().toISOString(),round:0,deckSize:20,sharedSlots:0,playerA:{name:'You',cards:[]},playerB:{name:opts.opponent==='local'?'Player B':'CPU',cards:[]},history:[],current:null,rules:{rejectedGoesToOpponent:true,packages:true,maxCopies:2}})}
function cardPool(){const all=safe(()=>Array.isArray(CARDS)?CARDS:[],[]);return all.filter(c=>c&&c.name&&c.id&&!String(c.id).startsWith('fallback-'))}
function packageFor(card,qty=1){return {id:id(),label:qty===2?`2× ${card.name}`:card.name,slotCost:qty,cards:[{cardId:card.id,name:card.name,quantity:qty,image:card.image||'',setCode:card.setCode||''}]}}
function randomPackage(){const pool=cardPool();if(!pool.length)return null;const c=pick(pool),qty=Math.random()<.45?2:1;return packageFor(c,qty)}
function makeChoice(s){let a=randomPackage(),b=randomPackage(),tries=0;while(a&&b&&a.cards[0].cardId===b.cards[0].cardId&&tries++<10)b=randomPackage();s.current={id:id(),optionA:a,optionB:b,picker:s.round%2===0?'A':'B'};write(s);return s.current}
function addPackage(player,pkg){if(!pkg)return;for(const c of pkg.cards){const found=player.cards.find(x=>x.cardId===c.cardId);if(found)found.quantity+=c.quantity;else player.cards.push({...c})}}
function count(player){return player.cards.reduce((n,c)=>n+Number(c.quantity||0),0)}
function canTake(player,pkg){if(!pkg)return false;if(count(player)+pkg.slotCost>20)return false;return pkg.cards.every(c=>{const have=player.cards.find(x=>x.cardId===c.cardId)?.quantity||0;return have+c.quantity<=2})}
function choose(which){const s=read();if(!s||!s.current)return;const mine=s.current.picker==='A'?s.playerA:s.playerB,other=s.current.picker==='A'?s.playerB:s.playerA;const chosen=which==='A'?s.current.optionA:s.current.optionB,rejected=which==='A'?s.current.optionB:s.current.optionA;if(!canTake(mine,chosen)||!canTake(other,rejected)){s.current=null;write(s);makeChoice(s);return render()};addPackage(mine,chosen);addPackage(other,rejected);s.history.push({round:s.round+1,picker:s.current.picker,chosen,rejected});s.round++;s.current=null;if(count(s.playerA)>=20&&count(s.playerB)>=20)s.status='complete';write(s);render()}
function copyCode(){const s=read();if(!s)return;const text=s.roomCode;navigator.clipboard?.writeText?.(text).then(()=>safe(()=>ppcNotice('✓ Draft room code copied')))}
function reset(){localStorage.removeItem(KEY);render()}
function close(){document.getElementById('ppcDraftRoot')?.remove();document.body.classList.remove('ppcDraftOpen')}
function ensureChoice(s){if(s.status==='draft'&&!s.current&&count(s.playerA)<20&&count(s.playerB)<20)makeChoice(s)}
function start(kind){let s=read()||newSession({opponent:kind});s.opponent=kind;s.playerB.name=kind==='local'?'Player B':'CPU';s.status='draft';write(s);ensureChoice(s);render()}
function pkgHtml(p,label){if(!p)return `<div class="draftPkg empty"><strong>${label}</strong><p>Load the Card Database to generate draft packages.</p></div>`;const c=p.cards[0];return `<button class="draftPkg" onclick="PPCDraftMode.choose('${label}')"><span class="draftPickLabel">OPTION ${label}</span>${c.image?`<img src="${esc(c.image)}" alt="${esc(c.name)}">`:''}<strong>${esc(p.label)}</strong><small>${p.slotCost} deck slot${p.slotCost===1?'':'s'}</small><span class="draftPickBtn">Pick package</span></button>`}
function deckMini(p){return `<div class="draftDeckMini"><div><strong>${esc(p.name)}</strong><span>${count(p)} / 20</span></div><div class="draftDeckBar"><i style="width:${Math.min(100,count(p)/20*100)}%"></i></div><small>${p.cards.length} unique cards</small></div>`}
function lobby(s){return `<div class="draftHero"><div><span class="eyebrow">POCKETNEXUS DRAFT</span><h1>Rival Draft</h1><p>Build two legal 20-card decks here, then play the actual match in Pokémon TCG Pocket.</p></div><button class="secondary" onclick="PPCDraftMode.close()">Close</button></div><section class="draftLobby panel"><span class="eyebrow">DRAFT ROOM</span><h2>${esc(s.roomCode)}</h2><p class="muted">Automatically generated room code. Online joining comes in the next backend phase.</p><div class="row"><button onclick="PPCDraftMode.copyCode()">Copy Code</button><button class="secondary" onclick="PPCDraftMode.reset()">Generate New Room</button></div><div class="draftRuleGrid"><article><small>FORMAT</small><strong>Rival Draft</strong></article><article><small>DECK SIZE</small><strong>20 cards</strong></article><article><small>PICKS</small><strong>Draft Packages</strong></article><article><small>MAX COPIES</small><strong>2 per card</strong></article></div><div class="draftStart"><button onclick="PPCDraftMode.start('cpu')">Draft vs CPU</button><button class="secondary" onclick="PPCDraftMode.start('local')">Local 2 Player</button></div></section>`}
function draft(s){ensureChoice(s);return `<div class="draftHero"><div><span class="eyebrow">RIVAL DRAFT</span><h1>Round ${s.round+1}</h1><p>${s.current?.picker==='A'?'You pick. The rejected package goes to your opponent.':'Opponent pick round.'}</p></div><button class="secondary" onclick="PPCDraftMode.close()">Save & Exit</button></div><div class="draftScore">${deckMini(s.playerA)}<div class="draftVs">VS</div>${deckMini(s.playerB)}</div><section class="draftChoice"><div class="draftChoiceHead"><span class="eyebrow">CHOOSE A PACKAGE</span><h2>A pick can be 1×, 2×, or later an evolution/shared bundle.</h2></div><div class="draftCards">${pkgHtml(s.current?.optionA,'A')}${pkgHtml(s.current?.optionB,'B')}</div></section><details class="panel draftHistory"><summary>Draft History (${s.history.length})</summary>${s.history.slice().reverse().map(h=>`<div><strong>Round ${h.round}</strong><span>${esc(h.chosen?.label||'—')}</span><small>Passed: ${esc(h.rejected?.label||'—')}</small></div>`).join('')||'<p class="muted">No picks yet.</p>'}</details>`}
function complete(s){return `<div class="draftHero"><div><span class="eyebrow">DRAFT COMPLETE</span><h1>Build these decks in Pokémon TCG Pocket</h1><p>PocketNexus handled the draft. The match itself happens in the Pocket app.</p></div><button class="secondary" onclick="PPCDraftMode.close()">Close</button></div><div class="draftScore">${deckMini(s.playerA)}<div class="draftVs">VS</div>${deckMini(s.playerB)}</div><section class="panel"><h2>Next steps</h2><ol><li>Build the drafted decks in Pokémon TCG Pocket.</li><li>Play the match in Pokémon TCG Pocket.</li><li>Return to PocketNexus to record the result.</li></ol><div class="row"><button class="secondary" onclick="PPCDraftMode.reset()">New Draft</button></div></section>`}
function styles(){if(document.getElementById('ppcDraftCss'))return;const s=document.createElement('style');s.id='ppcDraftCss';s.textContent=`.ppcDraftOpen{overflow:hidden}.ppcDraftRoot{position:fixed;inset:0;z-index:9999;background:var(--bg,#0d1016);overflow:auto;padding:28px}.ppcDraftShell{max-width:1180px;margin:auto}.draftHero,.draftScore,.draftCards,.draftRuleGrid,.draftStart{display:flex;gap:16px}.draftHero{justify-content:space-between;align-items:flex-start;margin-bottom:22px}.draftHero h1{margin:.3rem 0}.draftLobby{max-width:860px;margin:auto;text-align:center}.draftLobby h2{font-size:clamp(2rem,6vw,4rem);letter-spacing:.08em}.draftRuleGrid{display:grid;grid-template-columns:repeat(4,1fr);margin:22px 0}.draftRuleGrid article,.draftDeckMini{padding:14px;border:1px solid rgba(255,255,255,.1);border-radius:14px;background:rgba(255,255,255,.03)}.draftRuleGrid small,.draftRuleGrid strong{display:block}.draftStart{justify-content:center}.draftScore{align-items:center;margin-bottom:20px}.draftDeckMini{flex:1}.draftDeckMini>div:first-child{display:flex;justify-content:space-between}.draftDeckBar{height:7px;background:rgba(255,255,255,.08);border-radius:999px;margin:9px 0;overflow:hidden}.draftDeckBar i{display:block;height:100%;background:currentColor}.draftVs{font-weight:900}.draftChoice{padding:20px 0}.draftChoiceHead{text-align:center;margin-bottom:18px}.draftCards{justify-content:center}.draftPkg{width:min(340px,46vw);min-height:390px;border:1px solid rgba(255,255,255,.12);border-radius:20px;background:rgba(255,255,255,.04);padding:18px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;color:inherit;cursor:pointer}.draftPkg:hover{transform:translateY(-2px);border-color:currentColor}.draftPkg img{max-height:260px;max-width:190px;border-radius:10px}.draftPickLabel,.draftPickBtn{font-size:.78rem;font-weight:800;letter-spacing:.08em}.draftPickBtn{margin-top:auto}.draftHistory>div{display:grid;grid-template-columns:120px 1fr 1fr;gap:12px;padding:10px 0;border-top:1px solid rgba(255,255,255,.08)}@media(max-width:700px){.ppcDraftRoot{padding:16px}.draftHero{gap:10px}.draftRuleGrid{grid-template-columns:1fr 1fr}.draftCards{gap:10px}.draftPkg{width:48%;min-height:320px;padding:10px}.draftPkg img{max-width:100%;max-height:190px}.draftHistory>div{grid-template-columns:1fr}.draftScore{gap:8px}.draftDeckMini{padding:10px}}`;document.head.appendChild(s)}
function render(){styles();let root=document.getElementById('ppcDraftRoot');if(!root){root=document.createElement('div');root.id='ppcDraftRoot';root.className='ppcDraftRoot';document.body.appendChild(root);document.body.classList.add('ppcDraftOpen')}let s=read();if(!s)s=newSession();root.innerHTML=`<main class="ppcDraftShell">${s.status==='complete'?complete(s):s.status==='draft'?draft(s):lobby(s)}</main>`}
function open(){safe(()=>loadCards());setTimeout(render,120);render()}
function installNav(){if(window.__ppcDraftNavInstalled)return;window.__ppcDraftNavInstalled=true;const base=window.nav;if(typeof base==='function'){window.nav=function(){const out=base.apply(this,arguments);queueMicrotask(()=>{const play=[...document.querySelectorAll('.navCategory')].find(x=>/Play/i.test(x.dataset.category||''));const menu=play?.querySelector('.navCategoryMenu');if(menu&&!menu.querySelector('[data-draft-nav]'))menu.insertAdjacentHTML('beforeend',`<button data-draft-nav class="navCategoryItem" role="menuitem" onclick="closeHeaderMenus();PPCDraftMode.open()"><span class="navCategoryIcon">◈</span><span><strong>Draft Mode</strong><small>Build rival 20-card decks with draft packages.</small></span></button>`)});return out};safe(()=>nav())}const oldOpen=window.openMobileMoreSheet;if(typeof oldOpen==='function'){window.openMobileMoreSheet=function(){const out=oldOpen.apply(this,arguments);queueMicrotask(()=>{const grid=document.querySelector('.mobileMoreGroup .mobileMoreGrid');if(grid&&!grid.querySelector('[data-draft-mobile]'))grid.insertAdjacentHTML('beforeend',`<button data-draft-mobile type="button" class="mobileMoreItem" onclick="closeMobileMoreSheet();PPCDraftMode.open()"><span>◈</span><strong>Draft Mode</strong></button>`)});return out}}}
window.PPCDraftMode={version:'8.69.0',open,close,render,start,choose,reset,copyCode,newSession,read};
styles();installNav();
})();