/* PocketNexus V8.69.3 — Draft intelligence + completion + Deck/Battle handoff
   Local-first draft assistant. Matches are played in Pokémon TCG Pocket. */
(function(){
'use strict';
if(window.PPCDraftMode)return;
const KEY='ppc_draft_v8690',MAX=2,SIZE=20;
const WORD_A=['PLASMA','ULTRA','NOVA','ROCKET','MASTER','RIVAL','POCKET','AURORA','PRIME','VOLT'];
const WORD_B=['DRAGON','SPARK','MOON','WING','MEW','EEVEE','PIKA','PHANTOM','COMET','NEXUS'];
const safe=(fn,f=null)=>{try{return fn()}catch{return f}},pick=a=>a[Math.floor(Math.random()*a.length)];
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function id(){return crypto?.randomUUID?.()||('draft-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2))}
function code(){const b=new Uint8Array(2);crypto?.getRandomValues?.(b);return `${pick(WORD_A)}-${pick(WORD_B)}-${(((b[0]||1)<<8)+(b[1]||1)).toString(36).toUpperCase().padStart(2,'0').slice(-2)}`}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function write(x){localStorage.setItem(KEY,JSON.stringify(x));return x}
function count(p){return (p.cards||[]).reduce((n,c)=>n+Number(c.quantity||0),0)}
function cardPool(){return safe(()=>Array.isArray(CARDS)?CARDS:[],[]).filter(c=>c?.id&&c?.name&&!String(c.id).startsWith('fallback-'))}
function kind(c){return /trainer/i.test(c.category||c.cardType||'')?'trainer':'pokemon'}
function stage(c){return String(c.stage||c.evolutionStage||'').toLowerCase()}
function cardEntry(c,q){return {cardId:c.id,name:c.name,quantity:q,image:c.image||'',setCode:c.setCode||'',kind:kind(c),stage:stage(c)}}
function pkg(cards,type='flex',label=''){const entries=cards.map(([c,q])=>cardEntry(c,q));return {id:id(),type,label:label||entries.map(x=>`${x.quantity}× ${x.name}`).join(' + '),slotCost:entries.reduce((n,x)=>n+x.quantity,0),cards:entries}}
function single(c,q=1,type='flex'){return pkg([[c,q]],type,q===2?`2× ${c.name}`:c.name)}
function evolutionPkg(pool){const evolved=pool.filter(c=>kind(c)==='pokemon'&&/stage 1|stage 2/.test(stage(c)));for(let i=0;i<24&&evolved.length;i++){const evo=pick(evolved),baseName=String(evo.evolvesFrom||evo.evolves_from||evo.preEvolution||'').trim();if(!baseName)continue;const base=pool.find(c=>String(c.name).toLowerCase()===baseName.toLowerCase());if(base)return pkg([[base,1],[evo,1]],'evolution','Evolution Package')}return null}
function trainerPkg(pool){const t=pool.filter(c=>kind(c)==='trainer');if(t.length<2)return null;let a=pick(t),b=pick(t),tries=0;while(b.id===a.id&&tries++<12)b=pick(t);return pkg([[a,1],[b,1]],'trainer','Trainer Bundle')}
function exactPackage(pool,cost){if(cost===1)return single(pick(pool),1);for(let i=0;i<30;i++){const roll=Math.random();const p=roll<.28?evolutionPkg(pool):roll<.52?trainerPkg(pool):single(pick(pool),2);if(p&&p.slotCost===cost)return p}return single(pick(pool),cost)}
function addPackage(player,p){for(const c of p?.cards||[]){const f=player.cards.find(x=>x.cardId===c.cardId);if(f)f.quantity+=c.quantity;else player.cards.push({...c})}}
function canTake(player,p){if(!p||count(player)+p.slotCost>SIZE)return false;return p.cards.every(c=>(player.cards.find(x=>x.cardId===c.cardId)?.quantity||0)+c.quantity<=MAX)}
function validForBoth(a,b,p){return canTake(a,p)&&canTake(b,p)}
function packageForBoth(a,b,pool,cost){for(let i=0;i<80;i++){const p=exactPackage(pool,cost);if(validForBoth(a,b,p))return p}return null}
function sharedCandidates(pool){return pool.filter(c=>kind(c)==='trainer')}
function addSharedCore(s){if(s.sharedApplied)return;const pool=sharedCandidates(cardPool());if(!pool.length){s.sharedApplied=true;return}const shuffled=[...pool].sort(()=>Math.random()-.5),cards=[];for(const c of shuffled){if(cards.length>=2)break;cards.push([c,1])}if(cards.length){const p=pkg(cards,'shared','Shared Core');if(canTake(s.playerA,p)&&canTake(s.playerB,p)){addPackage(s.playerA,p);addPackage(s.playerB,p);s.sharedSlots=p.slotCost;s.sharedPackage=p;s.history.push({round:0,picker:'SHARED',chosen:p,rejected:null})}}s.sharedApplied=true}
function newSession(opts={}){return write({id:id(),roomCode:code(),status:'lobby',mode:'rival',opponent:opts.opponent||'cpu',createdAt:new Date().toISOString(),round:0,deckSize:SIZE,sharedSlots:0,sharedApplied:false,playerA:{name:'You',cards:[]},playerB:{name:opts.opponent==='local'?'Player B':'CPU',cards:[]},history:[],current:null,savedDeckIds:{},rules:{rejectedGoesToOpponent:true,packages:true,maxCopies:MAX,sharedCore:true,evolutionProtection:true}})}
function deckProfile(player){let pokemon=0,trainers=0,evolution=0;for(const c of player.cards||[]){const q=Number(c.quantity||0);if(c.kind==='trainer')trainers+=q;else pokemon+=q;if(/stage 1|stage 2/.test(c.stage||''))evolution+=q}return {pokemon,trainers,evolution,total:count(player)}}
function scorePackage(player,p){if(!p)return -999;const pr=deckProfile(player),afterPokemon=pr.pokemon+p.cards.filter(c=>c.kind!=='trainer').reduce((n,c)=>n+c.quantity,0),afterTrainer=pr.trainers+p.cards.filter(c=>c.kind==='trainer').reduce((n,c)=>n+c.quantity,0);let score=0;if(p.type==='evolution')score+=24;if(p.type==='trainer')score+=pr.trainers<7?20:8;if(p.type==='pokemon')score+=pr.pokemon<11?16:7;if(p.cards.some(c=>c.quantity===2))score+=8;if(afterPokemon>=8&&afterPokemon<=14)score+=8;if(afterTrainer>=5&&afterTrainer<=10)score+=8;score+=Math.random()*4;return score}
function makeChoice(s){const pool=cardPool(),aLeft=SIZE-count(s.playerA),bLeft=SIZE-count(s.playerB);if(!pool.length||aLeft<=0||bLeft<=0)return null;const remaining=Math.min(aLeft,bLeft),cost=remaining===1?1:2;let a=packageForBoth(s.playerA,s.playerB,pool,cost),b=packageForBoth(s.playerA,s.playerB,pool,cost),tries=0;while(a&&b&&a.cards.map(x=>x.cardId).join('|')===b.cards.map(x=>x.cardId).join('|')&&tries++<20)b=packageForBoth(s.playerA,s.playerB,pool,cost);if(!a||!b){if(cost===2){a=packageForBoth(s.playerA,s.playerB,pool,1);b=packageForBoth(s.playerA,s.playerB,pool,1)}if(!a||!b)return null}s.current={id:id(),optionA:a,optionB:b,picker:s.round%2===0?'A':'B'};write(s);return s.current}
function finalizeIfReady(s){if(count(s.playerA)===SIZE&&count(s.playerB)===SIZE){s.status='complete';s.current=null;write(s);return true}return false}
function ensureChoice(s){if(finalizeIfReady(s))return;if(s.status==='draft'&&!s.current)makeChoice(s)}
function applyChoice(s,which,source='player'){if(!s?.current)return false;const mine=s.current.picker==='A'?s.playerA:s.playerB,other=s.current.picker==='A'?s.playerB:s.playerA,chosen=which==='A'?s.current.optionA:s.current.optionB,rejected=which==='A'?s.current.optionB:s.current.optionA;if(!canTake(mine,chosen)||!canTake(other,rejected)){s.current=null;write(s);ensureChoice(s);return false}addPackage(mine,chosen);addPackage(other,rejected);s.history.push({round:s.round+1,picker:s.current.picker,chosen,rejected,source});s.round++;s.current=null;finalizeIfReady(s);write(s);return true}
function choose(which){const s=read();if(!s?.current)return;applyChoice(s,which,'player');ensureChoice(s);render();queueCpuIfNeeded()}
function cpuPick(s){if(!s?.current||s.opponent!=='cpu'||s.current.picker!=='B')return false;const a=scorePackage(s.playerB,s.current.optionA),b=scorePackage(s.playerB,s.current.optionB);return applyChoice(s,a>=b?'A':'B','cpu')}
function queueCpuIfNeeded(){const s=read();if(s?.status==='draft'&&s.opponent==='cpu'&&s.current?.picker==='B'){setTimeout(()=>{const fresh=read();if(cpuPick(fresh)){ensureChoice(fresh);render();queueCpuIfNeeded()}},420)}}
function start(kind){let s=read()||newSession({opponent:kind});s.opponent=kind;s.playerB.name=kind==='local'?'Player B':'CPU';addSharedCore(s);s.status='draft';write(s);ensureChoice(s);render();queueCpuIfNeeded()}
function auditPlayer(p){const issues=[];if(count(p)!==SIZE)issues.push(`${count(p)}/${SIZE} cards`);for(const c of p.cards||[])if(Number(c.quantity||0)>MAX)issues.push(`${c.name} exceeds ${MAX} copies`);return {valid:issues.length===0,issues}}
function deckCardsObject(p){const out={};for(const c of p.cards||[])out[c.cardId]=Number(c.quantity||0);return out}
function uniqueName(base){const names=new Set((safe(()=>state.decks,[])||[]).map(d=>String(d.name||'').toLowerCase()));let n=base,i=2;while(names.has(n.toLowerCase()))n=`${base} ${i++}`;return n}
function saveDraftDecks(){const s=read();if(!s||s.status!=='complete')return;if(!auditPlayer(s.playerA).valid||!auditPlayer(s.playerB).valid)return safe(()=>ppcNotice('Draft decks must pass the 20-card audit before saving.'));if(!window.state||!Array.isArray(state.decks))return safe(()=>ppcNotice('Deck Manager is not ready yet.'));if(!s.savedDeckIds?.A){const d={id:safe(()=>makeId(),id()),name:uniqueName(`Draft ${s.roomCode} — Player A`),cards:deckCardsObject(s.playerA),energy:'',source:'draft',draftId:s.id,draftRoomCode:s.roomCode};state.decks.push(d);s.savedDeckIds=s.savedDeckIds||{};s.savedDeckIds.A=d.id}if(!s.savedDeckIds?.B){const d={id:safe(()=>makeId(),id()),name:uniqueName(`Draft ${s.roomCode} — Player B`),cards:deckCardsObject(s.playerB),energy:'',source:'draft',draftId:s.id,draftRoomCode:s.roomCode};state.decks.push(d);s.savedDeckIds.B=d.id}safe(()=>save());write(s);safe(()=>ppcNotice('✓ Both drafted decks saved to My Decks'));render()}
function openSavedDeck(side='A'){const s=read(),deckId=s?.savedDeckIds?.[side];if(!deckId)return;if(typeof openDeck==='function'){close();openDeck(deckId)}else{state.selected=deckId;state.page='decks';safe(()=>save());close();safe(()=>render())}}
function battleHandoff(){const s=read();if(!s||s.status!=='complete')return;if(!s.savedDeckIds?.A)saveDraftDecks();const fresh=read(),deckId=fresh?.savedDeckIds?.A;if(!deckId)return;state.battlePrefs=state.battlePrefs||{};state.battlePrefs.experienceMode='standard';state.battlePrefs.lastDeckId=deckId;state.battlePrefs.draftContext={draftId:fresh.id,roomCode:fresh.roomCode,opponentDeckId:fresh.savedDeckIds?.B||'',mode:'rival'};state.page='matches';safe(()=>save());close();safe(()=>render())}
function copyCode(){const s=read();if(s)navigator.clipboard?.writeText?.(s.roomCode).then(()=>safe(()=>ppcNotice('✓ Draft room code copied')))}
function reset(){localStorage.removeItem(KEY);render()}
function close(){document.getElementById('ppcDraftRoot')?.remove();document.body.classList.remove('ppcDraftOpen')}
function pkgHtml(p,label,disabled=false){if(!p)return `<div class="draftPkg empty"><strong>OPTION ${label}</strong><p>No legal package available.</p></div>`;return `<button class="draftPkg" ${disabled?'disabled':''} onclick="PPCDraftMode.choose('${label}')"><span class="draftPickLabel">OPTION ${label} · ${esc(p.type.toUpperCase())}</span><div class="draftPkgCards">${p.cards.map(c=>`${c.image?`<img src="${esc(c.image)}" alt="${esc(c.name)}">`:''}<strong>${c.quantity}× ${esc(c.name)}</strong>`).join('')}</div><small>${p.slotCost} deck slot${p.slotCost===1?'':'s'}</small><span class="draftPickBtn">${disabled?'CPU deciding…':'Pick package'}</span></button>`}
function deckMini(p,s){const pr=deckProfile(p);return `<div class="draftDeckMini"><div><strong>${esc(p.name)}</strong><span>${count(p)} / ${SIZE}</span></div><div class="draftDeckBar"><i style="width:${count(p)/SIZE*100}%"></i></div><small>Pokémon ${pr.pokemon} · Trainers ${pr.trainers} · Shared ${s.sharedSlots||0} · Remaining ${SIZE-count(p)}</small></div>`}
function lobby(s){return `<div class="draftHero"><div><span class="eyebrow">POCKETNEXUS DRAFT</span><h1>Rival Draft</h1><p>Draft packages build two 20-card decks. The actual match is played in Pokémon TCG Pocket.</p></div><button class="secondary" onclick="PPCDraftMode.close()">Close</button></div><section class="draftLobby panel"><span class="eyebrow">DRAFT ROOM</span><h2>${esc(s.roomCode)}</h2><p class="muted">Room codes are generated automatically. Online joining is a later backend phase.</p><div class="row"><button onclick="PPCDraftMode.copyCode()">Copy Code</button><button class="secondary" onclick="PPCDraftMode.reset()">Generate New Room</button></div><div class="draftRuleGrid"><article><small>FORMAT</small><strong>Rival Draft</strong></article><article><small>DECK</small><strong>20 cards</strong></article><article><small>PACKAGES</small><strong>1× / 2× / Bundles</strong></article><article><small>CPU</small><strong>Synergy scoring</strong></article></div><div class="draftStart"><button onclick="PPCDraftMode.start('cpu')">Draft vs CPU</button><button class="secondary" onclick="PPCDraftMode.start('local')">Local 2 Player</button></div></section>`}
function draft(s){ensureChoice(s);const cpuTurn=s.opponent==='cpu'&&s.current?.picker==='B';return `<div class="draftHero"><div><span class="eyebrow">RIVAL DRAFT</span><h1>Round ${s.round+1}</h1><p>${cpuTurn?'CPU is choosing based on deck composition and package value.':s.current?.picker==='A'?'Choose your package. The other package goes to your opponent.':'Player B chooses. The other package goes to Player A.'}</p></div><button class="secondary" onclick="PPCDraftMode.close()">Save & Exit</button></div>${s.sharedPackage?`<div class="draftShared panel"><span class="eyebrow">SHARED CORE · BOTH DECKS</span><strong>${esc(s.sharedPackage.label)}</strong><small>${s.sharedPackage.cards.map(c=>`${c.quantity}× ${esc(c.name)}`).join(' · ')}</small></div>`:''}<div class="draftScore">${deckMini(s.playerA,s)}<div class="draftVs">VS</div>${deckMini(s.playerB,s)}</div><section class="draftChoice"><div class="draftChoiceHead"><span class="eyebrow">CHOOSE A DRAFT PACKAGE</span><h2>Packages stay slot-balanced so both decks can finish exactly at 20.</h2></div><div class="draftCards">${pkgHtml(s.current?.optionA,'A',cpuTurn)}${pkgHtml(s.current?.optionB,'B',cpuTurn)}</div></section><details class="panel draftHistory"><summary>Draft History (${s.history.length})</summary>${s.history.slice().reverse().map(h=>`<div><strong>${h.round?`Round ${h.round}`:'Shared Core'}</strong><span>${esc(h.chosen?.label||'—')}</span><small>${h.rejected?`Passed: ${esc(h.rejected.label)}${h.source==='cpu'?' · CPU pick':''}`:'Added to both decks'}</small></div>`).join('')}</details>`}
function listHtml(p){return `<div class="draftFinalList">${(p.cards||[]).map(c=>`<div><span>${c.quantity}×</span><strong>${esc(c.name)}</strong></div>`).join('')}</div>`}
function complete(s){const a=auditPlayer(s.playerA),b=auditPlayer(s.playerB),saved=!!(s.savedDeckIds?.A&&s.savedDeckIds?.B);return `<div class="draftHero"><div><span class="eyebrow">DRAFT COMPLETE</span><h1>Both decks are ${count(s.playerA)} / ${SIZE}</h1><p>Build these decks in Pokémon TCG Pocket, play there, then return to PocketNexus to record the result.</p></div><button class="secondary" onclick="PPCDraftMode.close()">Close</button></div><div class="draftScore">${deckMini(s.playerA,s)}<div class="draftVs">VS</div>${deckMini(s.playerB,s)}</div><section class="panel"><div class="between"><div><h2>Deck audit</h2><p>${a.valid&&b.valid?'✓ Both decks pass the current 20-card / max-2-copy draft audit.':'⚠ '+esc([...a.issues,...b.issues].join(' · '))}</p></div><span class="badge">${saved?'SAVED':'READY'}</span></div><div class="draftFinalGrid"><div><h3>Player A</h3>${listHtml(s.playerA)}</div><div><h3>Player B</h3>${listHtml(s.playerB)}</div></div><div class="row draftFinalActions"><button onclick="PPCDraftMode.saveDraftDecks()">${saved?'Decks Saved':'Save Both to My Decks'}</button>${saved?`<button class="secondary" onclick="PPCDraftMode.openSavedDeck('A')">Open My Draft Deck</button>`:''}<button class="secondary" onclick="PPCDraftMode.battleHandoff()">Open Battle Tracker</button><button class="secondary" onclick="PPCDraftMode.reset()">New Draft</button></div></section>`}
function styles(){if(document.getElementById('ppcDraftCss'))return;const e=document.createElement('style');e.id='ppcDraftCss';e.textContent=`.ppcDraftOpen{overflow:hidden}.ppcDraftRoot{position:fixed;inset:0;z-index:9999;background:var(--bg,#0d1016);overflow:auto;padding:28px}.ppcDraftShell{max-width:1180px;margin:auto}.draftHero,.draftScore,.draftCards,.draftRuleGrid,.draftStart{display:flex;gap:16px}.draftHero{justify-content:space-between;align-items:flex-start;margin-bottom:22px}.draftLobby{max-width:860px;margin:auto;text-align:center}.draftLobby h2{font-size:clamp(2rem,6vw,4rem);letter-spacing:.08em}.draftRuleGrid{display:grid;grid-template-columns:repeat(4,1fr);margin:22px 0}.draftRuleGrid article,.draftDeckMini,.draftShared{padding:14px;border:1px solid rgba(255,255,255,.1);border-radius:14px;background:rgba(255,255,255,.03)}.draftRuleGrid small,.draftRuleGrid strong,.draftShared>*{display:block}.draftStart,.draftCards{justify-content:center}.draftScore{align-items:center;margin:20px 0}.draftDeckMini{flex:1}.draftDeckMini>div:first-child{display:flex;justify-content:space-between}.draftDeckBar{height:7px;background:rgba(255,255,255,.08);border-radius:999px;margin:9px 0;overflow:hidden}.draftDeckBar i{display:block;height:100%;background:currentColor}.draftVs{font-weight:900}.draftChoice{padding:20px 0}.draftChoiceHead{text-align:center;margin-bottom:18px}.draftPkg{width:min(360px,46vw);min-height:390px;border:1px solid rgba(255,255,255,.12);border-radius:20px;background:rgba(255,255,255,.04);padding:18px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;color:inherit;cursor:pointer}.draftPkg:disabled{opacity:.72;cursor:wait}.draftPkgCards{display:flex;flex-wrap:wrap;justify-content:center;gap:8px}.draftPkgCards img{max-height:190px;max-width:135px;border-radius:9px}.draftPkgCards strong{width:100%;font-size:.9rem}.draftPickLabel,.draftPickBtn{font-size:.78rem;font-weight:800;letter-spacing:.08em}.draftHistory>div{display:grid;grid-template-columns:120px 1fr 1fr;gap:12px;padding:10px 0;border-top:1px solid rgba(255,255,255,.08)}.draftFinalGrid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:18px 0}.draftFinalList{border:1px solid rgba(255,255,255,.08);border-radius:14px;overflow:hidden}.draftFinalList>div{display:grid;grid-template-columns:42px 1fr;gap:8px;padding:8px 12px;border-top:1px solid rgba(255,255,255,.06)}.draftFinalList>div:first-child{border-top:0}.draftFinalActions{flex-wrap:wrap}@media(max-width:700px){.ppcDraftRoot{padding:16px}.draftRuleGrid,.draftFinalGrid{grid-template-columns:1fr 1fr}.draftCards{gap:8px}.draftPkg{width:49%;min-height:320px;padding:10px}.draftPkgCards img{max-width:90px;max-height:130px}.draftHistory>div{grid-template-columns:1fr}.draftScore{gap:8px}.draftDeckMini{padding:10px}}@media(max-width:460px){.draftFinalGrid{grid-template-columns:1fr}.draftHero{flex-direction:column}.draftPkg{min-height:285px}}`;document.head.appendChild(e)}
function render(){styles();let root=document.getElementById('ppcDraftRoot');if(!root){root=document.createElement('div');root.id='ppcDraftRoot';root.className='ppcDraftRoot';document.body.appendChild(root);document.body.classList.add('ppcDraftOpen')}let s=read();if(!s)s=newSession();root.innerHTML=`<main class="ppcDraftShell">${s.status==='complete'?complete(s):s.status==='draft'?draft(s):lobby(s)}</main>`}
function open(){safe(()=>loadCards());setTimeout(()=>{render();queueCpuIfNeeded()},150);render();queueCpuIfNeeded()}
function installNav(){if(window.__ppcDraftNavInstalled)return;window.__ppcDraftNavInstalled=true;const base=window.nav;if(typeof base==='function'){window.nav=function(){const out=base.apply(this,arguments);queueMicrotask(()=>{const play=[...document.querySelectorAll('.navCategory')].find(x=>/Play/i.test(x.dataset.category||'')),menu=play?.querySelector('.navCategoryMenu');if(menu&&!menu.querySelector('[data-draft-nav]'))menu.insertAdjacentHTML('beforeend',`<button data-draft-nav class="navCategoryItem" role="menuitem" onclick="closeHeaderMenus();PPCDraftMode.open()"><span class="navCategoryIcon">◈</span><span><strong>Draft Mode</strong><small>Build rival 20-card decks with smart packages.</small></span></button>`)});return out};safe(()=>nav())}const old=window.openMobileMoreSheet;if(typeof old==='function')window.openMobileMoreSheet=function(){const out=old.apply(this,arguments);queueMicrotask(()=>{const grid=document.querySelector('.mobileMoreGroup .mobileMoreGrid');if(grid&&!grid.querySelector('[data-draft-mobile]'))grid.insertAdjacentHTML('beforeend',`<button data-draft-mobile type="button" class="mobileMoreItem" onclick="closeMobileMoreSheet();PPCDraftMode.open()"><span>◈</span><strong>Draft Mode</strong></button>`)});return out}}
window.PPCDraftMode={version:'8.69.3',open,close,render,start,choose,reset,copyCode,newSession,read,count,saveDraftDecks,openSavedDeck,battleHandoff,auditPlayer};styles();installNav();
})();