/* PocketNexus V8.69.2 — Draft Packages engine
   Local-first draft assistant. Matches are played in Pokémon TCG Pocket. */
(function(){
'use strict';
if(window.PPCDraftMode)return;
const KEY='ppc_draft_v8690',MAX=2,SIZE=20;
const WORD_A=['PLASMA','ULTRA','NOVA','ROCKET','MASTER','RIVAL','POCKET','AURORA','PRIME','VOLT'];
const WORD_B=['DRAGON','SPARK','MOON','WING','MEW','EEVEE','PIKA','PHANTOM','COMET','NEXUS'];
const safe=(fn,f=null)=>{try{return fn()}catch{return f}},pick=a=>a[Math.floor(Math.random()*a.length)];
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function id(){return crypto?.randomUUID?.()||('draft-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2))}
function code(){const b=new Uint8Array(2);crypto?.getRandomValues?.(b);return `${pick(WORD_A)}-${pick(WORD_B)}-${(((b[0]||1)<<8)+(b[1]||1)).toString(36).toUpperCase().padStart(2,'0').slice(-2)}`}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function write(x){localStorage.setItem(KEY,JSON.stringify(x));return x}
function count(p){return (p.cards||[]).reduce((n,c)=>n+Number(c.quantity||0),0)}
function cardPool(){return safe(()=>Array.isArray(CARDS)?CARDS:[],[]).filter(c=>c?.id&&c?.name&&!String(c.id).startsWith('fallback-'))}
function kind(c){return /trainer/i.test(c.category||c.cardType||'')?'trainer':'pokemon'}
function stage(c){return String(c.stage||c.evolutionStage||'').toLowerCase()}
function cardEntry(c,q){return {cardId:c.id,name:c.name,quantity:q,image:c.image||'',setCode:c.setCode||'',kind:kind(c),stage:stage(c)}}
function pkg(cards,type='flex',label=''){const entries=cards.map(([c,q])=>cardEntry(c,q));return {id:id(),type,label:label||entries.map(x=>`${x.quantity}× ${x.name}`).join(' + '),slotCost:entries.reduce((n,x)=>n+x.quantity,0),cards:entries}}
function single(c,q=1,type='flex'){return pkg([[c,q]],type,q===2?`2× ${c.name}`:c.name)}
function evolutionPkg(pool){const evolved=pool.filter(c=>kind(c)==='pokemon'&&/stage 1|stage 2/.test(stage(c)));for(let i=0;i<18&&evolved.length;i++){const evo=pick(evolved),baseName=String(evo.evolvesFrom||evo.evolves_from||evo.preEvolution||'').trim();if(!baseName)continue;const base=pool.find(c=>c.name===baseName);if(base)return pkg([[base,1],[evo,1]],'evolution','Evolution Package')}return null}
function trainerPkg(pool){const t=pool.filter(c=>kind(c)==='trainer');if(t.length<2)return null;let a=pick(t),b=pick(t),tries=0;while(b.id===a.id&&tries++<10)b=pick(t);return pkg([[a,1],[b,1]],'trainer','Trainer Bundle')}
function randomPackage(pool,slots=2){const roll=Math.random();let p=roll<.22?evolutionPkg(pool):roll<.42?trainerPkg(pool):null;if(p&&p.slotCost<=slots)return p;const eligible=pool.filter(c=>slots>=1);if(!eligible.length)return null;const c=pick(eligible),q=slots>=2&&Math.random()<.48?2:1;return single(c,q,kind(c)==='trainer'?'trainer':'pokemon')}
function addPackage(player,p){for(const c of p?.cards||[]){const f=player.cards.find(x=>x.cardId===c.cardId);if(f)f.quantity+=c.quantity;else player.cards.push({...c})}}
function canTake(player,p){if(!p||count(player)+p.slotCost>SIZE)return false;return p.cards.every(c=>(player.cards.find(x=>x.cardId===c.cardId)?.quantity||0)+c.quantity<=MAX)}
function validPkgFor(player,p){return canTake(player,p)}
function makeFor(player,pool,maxSlots){for(let i=0;i<50;i++){const p=randomPackage(pool,maxSlots);if(validPkgFor(player,p))return p}return null}
function sharedCandidates(pool){return pool.filter(c=>kind(c)==='trainer')}
function addSharedCore(s){if(s.sharedApplied)return;const pool=sharedCandidates(cardPool());if(!pool.length){s.sharedApplied=true;return}const shuffled=[...pool].sort(()=>Math.random()-.5),cards=[];for(const c of shuffled){if(cards.length>=2)break;cards.push([c,1])}if(!cards.length){s.sharedApplied=true;return}const p=pkg(cards,'shared','Shared Core');if(p.slotCost<=4&&canTake(s.playerA,p)&&canTake(s.playerB,p)){addPackage(s.playerA,p);addPackage(s.playerB,p);s.sharedSlots=p.slotCost;s.sharedPackage=p;s.history.push({round:0,picker:'SHARED',chosen:p,rejected:null})}s.sharedApplied=true}
function newSession(opts={}){return write({id:id(),roomCode:code(),status:'lobby',mode:'rival',opponent:opts.opponent||'cpu',createdAt:new Date().toISOString(),round:0,deckSize:SIZE,sharedSlots:0,sharedApplied:false,playerA:{name:'You',cards:[]},playerB:{name:opts.opponent==='local'?'Player B':'CPU',cards:[]},history:[],current:null,rules:{rejectedGoesToOpponent:true,packages:true,maxCopies:MAX,sharedCore:true,evolutionProtection:true}})}
function makeChoice(s){const pool=cardPool(),aLeft=SIZE-count(s.playerA),bLeft=SIZE-count(s.playerB);if(!pool.length||aLeft<=0||bLeft<=0)return null;const pickerA=s.round%2===0,mine=pickerA?s.playerA:s.playerB,other=pickerA?s.playerB:s.playerA,maxSlots=Math.min(2,SIZE-count(mine),SIZE-count(other));let a=null,b=null;for(let i=0;i<40;i++){a=makeFor(mine,pool,maxSlots);b=makeFor(other,pool,maxSlots);if(a&&b&&a.id!==b.id&&canTake(other,b)&&canTake(mine,a))break}if(!a||!b)return null;s.current={id:id(),optionA:a,optionB:b,picker:pickerA?'A':'B'};write(s);return s.current}
function ensureChoice(s){if(s.status==='draft'&&!s.current&&count(s.playerA)<SIZE&&count(s.playerB)<SIZE)makeChoice(s)}
function choose(which){const s=read();if(!s?.current)return;const mine=s.current.picker==='A'?s.playerA:s.playerB,other=s.current.picker==='A'?s.playerB:s.playerA,chosen=which==='A'?s.current.optionA:s.current.optionB,rejected=which==='A'?s.current.optionB:s.current.optionA;if(!canTake(mine,chosen)||!canTake(other,rejected)){s.current=null;write(s);ensureChoice(s);return render()}addPackage(mine,chosen);addPackage(other,rejected);s.history.push({round:s.round+1,picker:s.current.picker,chosen,rejected});s.round++;s.current=null;if(count(s.playerA)===SIZE&&count(s.playerB)===SIZE)s.status='complete';write(s);ensureChoice(s);render()}
function start(kind){let s=read()||newSession({opponent:kind});s.opponent=kind;s.playerB.name=kind==='local'?'Player B':'CPU';addSharedCore(s);s.status='draft';write(s);ensureChoice(s);render()}
function copyCode(){const s=read();if(s)navigator.clipboard?.writeText?.(s.roomCode).then(()=>safe(()=>ppcNotice('✓ Draft room code copied')))}
function reset(){localStorage.removeItem(KEY);render()}
function close(){document.getElementById('ppcDraftRoot')?.remove();document.body.classList.remove('ppcDraftOpen')}
function pkgHtml(p,label){if(!p)return `<div class="draftPkg empty"><strong>OPTION ${label}</strong><p>No legal package available.</p></div>`;return `<button class="draftPkg" onclick="PPCDraftMode.choose('${label}')"><span class="draftPickLabel">OPTION ${label} · ${esc(p.type.toUpperCase())}</span><div class="draftPkgCards">${p.cards.map(c=>`${c.image?`<img src="${esc(c.image)}" alt="${esc(c.name)}">`:''}<strong>${c.quantity}× ${esc(c.name)}</strong>`).join('')}</div><small>${p.slotCost} deck slot${p.slotCost===1?'':'s'}</small><span class="draftPickBtn">Pick package</span></button>`}
function deckMini(p,s){return `<div class="draftDeckMini"><div><strong>${esc(p.name)}</strong><span>${count(p)} / ${SIZE}</span></div><div class="draftDeckBar"><i style="width:${count(p)/SIZE*100}%"></i></div><small>Shared ${s.sharedSlots||0} · Drafted ${Math.max(0,count(p)-(s.sharedSlots||0))} · Remaining ${SIZE-count(p)}</small></div>`}
function lobby(s){return `<div class="draftHero"><div><span class="eyebrow">POCKETNEXUS DRAFT</span><h1>Rival Draft</h1><p>Draft packages build two 20-card decks. The actual match is played in Pokémon TCG Pocket.</p></div><button class="secondary" onclick="PPCDraftMode.close()">Close</button></div><section class="draftLobby panel"><span class="eyebrow">DRAFT ROOM</span><h2>${esc(s.roomCode)}</h2><p class="muted">Room codes are generated automatically. Online joining is a later backend phase.</p><div class="row"><button onclick="PPCDraftMode.copyCode()">Copy Code</button><button class="secondary" onclick="PPCDraftMode.reset()">Generate New Room</button></div><div class="draftRuleGrid"><article><small>FORMAT</small><strong>Rival Draft</strong></article><article><small>DECK</small><strong>20 cards</strong></article><article><small>PACKAGES</small><strong>1× / 2× / Bundles</strong></article><article><small>SHARED CORE</small><strong>Enabled</strong></article></div><div class="draftStart"><button onclick="PPCDraftMode.start('cpu')">Draft vs CPU</button><button class="secondary" onclick="PPCDraftMode.start('local')">Local 2 Player</button></div></section>`}
function draft(s){ensureChoice(s);return `<div class="draftHero"><div><span class="eyebrow">RIVAL DRAFT</span><h1>Round ${s.round+1}</h1><p>${s.current?.picker==='A'?'Choose your package. The other package goes to your opponent.':'Opponent-side draft choice.'}</p></div><button class="secondary" onclick="PPCDraftMode.close()">Save & Exit</button></div>${s.sharedPackage?`<div class="draftShared panel"><span class="eyebrow">SHARED CORE · BOTH DECKS</span><strong>${esc(s.sharedPackage.label)}</strong><small>${s.sharedPackage.cards.map(c=>`${c.quantity}× ${esc(c.name)}`).join(' · ')}</small></div>`:''}<div class="draftScore">${deckMini(s.playerA,s)}<div class="draftVs">VS</div>${deckMini(s.playerB,s)}</div><section class="draftChoice"><div class="draftChoiceHead"><span class="eyebrow">CHOOSE A DRAFT PACKAGE</span><h2>Packages can be singles, 2-ofs, evolution groups, or Trainer bundles.</h2></div><div class="draftCards">${pkgHtml(s.current?.optionA,'A')}${pkgHtml(s.current?.optionB,'B')}</div></section><details class="panel draftHistory"><summary>Draft History (${s.history.length})</summary>${s.history.slice().reverse().map(h=>`<div><strong>${h.round?`Round ${h.round}`:'Shared Core'}</strong><span>${esc(h.chosen?.label||'—')}</span><small>${h.rejected?`Passed: ${esc(h.rejected.label)}`:'Added to both decks'}</small></div>`).join('')}</details>`}
function complete(s){return `<div class="draftHero"><div><span class="eyebrow">DRAFT COMPLETE</span><h1>Both decks are 20 / 20</h1><p>Build these decks in Pokémon TCG Pocket, play there, then return to PocketNexus to record the result.</p></div><button class="secondary" onclick="PPCDraftMode.close()">Close</button></div><div class="draftScore">${deckMini(s.playerA,s)}<div class="draftVs">VS</div>${deckMini(s.playerB,s)}</div><section class="panel"><h2>Deck audit</h2><p>✓ 20 cards each · ✓ maximum 2 copies enforced · ✓ shared package counted in both decks.</p><div class="row"><button class="secondary" onclick="PPCDraftMode.reset()">New Draft</button></div></section>`}
function styles(){if(document.getElementById('ppcDraftCss'))return;const e=document.createElement('style');e.id='ppcDraftCss';e.textContent=`.ppcDraftOpen{overflow:hidden}.ppcDraftRoot{position:fixed;inset:0;z-index:9999;background:var(--bg,#0d1016);overflow:auto;padding:28px}.ppcDraftShell{max-width:1180px;margin:auto}.draftHero,.draftScore,.draftCards,.draftRuleGrid,.draftStart{display:flex;gap:16px}.draftHero{justify-content:space-between;align-items:flex-start;margin-bottom:22px}.draftLobby{max-width:860px;margin:auto;text-align:center}.draftLobby h2{font-size:clamp(2rem,6vw,4rem);letter-spacing:.08em}.draftRuleGrid{display:grid;grid-template-columns:repeat(4,1fr);margin:22px 0}.draftRuleGrid article,.draftDeckMini,.draftShared{padding:14px;border:1px solid rgba(255,255,255,.1);border-radius:14px;background:rgba(255,255,255,.03)}.draftRuleGrid small,.draftRuleGrid strong,.draftShared>*{display:block}.draftStart,.draftCards{justify-content:center}.draftScore{align-items:center;margin:20px 0}.draftDeckMini{flex:1}.draftDeckMini>div:first-child{display:flex;justify-content:space-between}.draftDeckBar{height:7px;background:rgba(255,255,255,.08);border-radius:999px;margin:9px 0;overflow:hidden}.draftDeckBar i{display:block;height:100%;background:currentColor}.draftVs{font-weight:900}.draftChoice{padding:20px 0}.draftChoiceHead{text-align:center;margin-bottom:18px}.draftPkg{width:min(360px,46vw);min-height:390px;border:1px solid rgba(255,255,255,.12);border-radius:20px;background:rgba(255,255,255,.04);padding:18px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;color:inherit;cursor:pointer}.draftPkgCards{display:flex;flex-wrap:wrap;justify-content:center;gap:8px}.draftPkgCards img{max-height:190px;max-width:135px;border-radius:9px}.draftPkgCards strong{width:100%;font-size:.9rem}.draftPickLabel,.draftPickBtn{font-size:.78rem;font-weight:800;letter-spacing:.08em}.draftHistory>div{display:grid;grid-template-columns:120px 1fr 1fr;gap:12px;padding:10px 0;border-top:1px solid rgba(255,255,255,.08)}@media(max-width:700px){.ppcDraftRoot{padding:16px}.draftRuleGrid{grid-template-columns:1fr 1fr}.draftCards{gap:8px}.draftPkg{width:49%;min-height:320px;padding:10px}.draftPkgCards img{max-width:90px;max-height:130px}.draftHistory>div{grid-template-columns:1fr}.draftScore{gap:8px}.draftDeckMini{padding:10px}}`;document.head.appendChild(e)}
function render(){styles();let root=document.getElementById('ppcDraftRoot');if(!root){root=document.createElement('div');root.id='ppcDraftRoot';root.className='ppcDraftRoot';document.body.appendChild(root);document.body.classList.add('ppcDraftOpen')}let s=read();if(!s)s=newSession();root.innerHTML=`<main class="ppcDraftShell">${s.status==='complete'?complete(s):s.status==='draft'?draft(s):lobby(s)}</main>`}
function open(){safe(()=>loadCards());setTimeout(render,150);render()}
function installNav(){if(window.__ppcDraftNavInstalled)return;window.__ppcDraftNavInstalled=true;const base=window.nav;if(typeof base==='function'){window.nav=function(){const out=base.apply(this,arguments);queueMicrotask(()=>{const play=[...document.querySelectorAll('.navCategory')].find(x=>/Play/i.test(x.dataset.category||'')),menu=play?.querySelector('.navCategoryMenu');if(menu&&!menu.querySelector('[data-draft-nav]'))menu.insertAdjacentHTML('beforeend',`<button data-draft-nav class="navCategoryItem" role="menuitem" onclick="closeHeaderMenus();PPCDraftMode.open()"><span class="navCategoryIcon">◈</span><span><strong>Draft Mode</strong><small>Build rival 20-card decks with smart packages.</small></span></button>`)});return out};safe(()=>nav())}const old=window.openMobileMoreSheet;if(typeof old==='function')window.openMobileMoreSheet=function(){const out=old.apply(this,arguments);queueMicrotask(()=>{const grid=document.querySelector('.mobileMoreGroup .mobileMoreGrid');if(grid&&!grid.querySelector('[data-draft-mobile]'))grid.insertAdjacentHTML('beforeend',`<button data-draft-mobile type="button" class="mobileMoreItem" onclick="closeMobileMoreSheet();PPCDraftMode.open()"><span>◈</span><strong>Draft Mode</strong></button>`)});return out}}
window.PPCDraftMode={version:'8.69.2',open,close,render,start,choose,reset,copyCode,newSession,read,count};styles();installNav();
})();