/* PocketNexus V8.69.4 — Online Draft Rooms
   Supabase-authoritative room state + Realtime sync layered onto Draft Mode. */
(function(){
'use strict';
if(window.PPCDraftOnline)return;
const KEY='ppc_draft_v8690';
let roomChannel=null,busy=false,lastError='';
const safe=(fn,f=null)=>{try{return fn()}catch{return f}};
function client(){let c=safe(()=>window.getPPCCloudClient?.(),null);if(!c)safe(()=>window.initCloudAuth?.());return c||safe(()=>window.getPPCCloudClient?.(),null)}
function session(){return safe(()=>JSON.parse(localStorage.getItem(KEY)||'null'),null)}
function saveLocal(s){localStorage.setItem(KEY,JSON.stringify(s));return s}
function normalizeRow(data){return Array.isArray(data)?data[0]||null:data||null}
function notify(msg){safe(()=>window.ppcNotice?.(msg));}
function signedIn(){return !!safe(()=>window.cloudSession?.user?.id,false)}
function roleFor(s){return s?.online?.role||''}
function statusText(s){if(!s?.online?.roomId)return 'LOCAL';if(lastError)return 'SYNC ERROR';return s.online.connected?'LIVE':'RECONNECTING'}
function localStateForServer(s){const out=JSON.parse(JSON.stringify(s||{}));if(out.online){delete out.online.version;delete out.online.connected;delete out.online.lastSyncedAt;delete out.online.role}return out}
function applyRow(row,role){if(!row)return null;const incoming=row.state&&typeof row.state==='object'?JSON.parse(JSON.stringify(row.state)):{};incoming.id=incoming.id||row.id;incoming.roomCode=row.room_code;incoming.status=row.status||incoming.status||'lobby';incoming.opponent='online';incoming.playerA=incoming.playerA||{name:'Player A',cards:[]};incoming.playerB=incoming.playerB||{name:'Player B',cards:[]};incoming.playerA.name=incoming.playerA.name||'Player A';incoming.playerB.name=incoming.playerB.name||'Player B';incoming.online={...(incoming.online||{}),roomId:row.id,version:Number(row.version||1),role:role||roleFor(session())||'',connected:true,lastSyncedAt:new Date().toISOString(),hostPresent:!!row.host_user_id,guestPresent:!!row.guest_user_id};saveLocal(incoming);lastError='';safe(()=>PPCDraftMode.render());return incoming}
async function pull(){const s=session(),c=client();if(!s?.online?.roomId||!c)return null;const {data,error}=await c.rpc('get_draft_room',{p_room_id:s.online.roomId});if(error){lastError=error.message||'Could not refresh room';augment();return null}const row=normalizeRow(data);return row?applyRow(row,roleFor(s)):null}
function unsubscribe(){if(roomChannel){safe(()=>client()?.removeChannel?.(roomChannel));roomChannel=null}}
function subscribe(roomId,role){const c=client();if(!c||!roomId)return;unsubscribe();roomChannel=c.channel(`draft-room-${roomId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'draft_rooms',filter:`id=eq.${roomId}`},payload=>{const row=payload?.new;if(row)applyRow(row,role)}).subscribe(st=>{const s=session();if(s?.online?.roomId===roomId){s.online.connected=st==='SUBSCRIBED';saveLocal(s);augment()}})}
async function pushState(nextStatus=null){const s=session(),c=client();if(!s?.online?.roomId||!c)return false;if(busy)return false;busy=true;const expected=Number(s.online.version||1);const payload=localStateForServer(s);const {data,error}=await c.rpc('update_draft_room',{p_room_id:s.online.roomId,p_expected_version:expected,p_state:payload,p_status:nextStatus||s.status||null});busy=false;if(error){lastError=error.message||'Room changed';await pull();notify('Draft room changed on the other device. Synced to the latest state.');return false}applyRow(normalizeRow(data),roleFor(s));return true}
async function createRoom(){if(!signedIn())return notify('Sign in to PocketNexus before creating an online Draft Room.');const c=client();if(!c)return notify('Cloud connection is still loading.');busy=true;lastError='';let s=PPCDraftMode.newSession({opponent:'online'});s.opponent='online';s.playerA.name=safe(()=>cloudProfile?.display_name,'Player A')||'Player A';s.playerB.name='Waiting for opponent…';s.status='lobby';s.online={readyA:false,readyB:false};saveLocal(s);const {data,error}=await c.rpc('create_draft_room',{p_state:localStateForServer(s)});busy=false;if(error){lastError=error.message||'Could not create room';notify(lastError);PPCDraftMode.render();return}const row=normalizeRow(data),applied=applyRow(row,'A');if(applied){subscribe(row.id,'A');notify(`✓ Online room ${row.room_code} created`);augment()}}
async function joinRoom(raw){const code=String(raw||document.getElementById('draftJoinCode')?.value||'').trim().toUpperCase();if(!code)return notify('Enter a Draft Room code first.');if(!signedIn())return notify('Sign in to PocketNexus before joining an online Draft Room.');const c=client();if(!c)return notify('Cloud connection is still loading.');busy=true;lastError='';const {data,error}=await c.rpc('join_draft_room',{p_room_code:code});busy=false;if(error){lastError=error.message||'Could not join room';notify(lastError);augment();return}const row=normalizeRow(data),applied=applyRow(row,'B');if(applied){applied.playerB.name=safe(()=>cloudProfile?.display_name,'Player B')||'Player B';saveLocal(applied);await pushState('lobby');subscribe(row.id,'B');notify(`✓ Joined ${row.room_code}`);augment()}}
async function toggleReady(){const s=session();if(!s?.online?.roomId)return;const role=roleFor(s);if(role!=='A'&&role!=='B')return;s.online=s.online||{};s.online[role==='A'?'readyA':'readyB']=!s.online[role==='A'?'readyA':'readyB'];saveLocal(s);await pushState('lobby')}
async function startOnline(){const s=session();if(!s?.online?.roomId||roleFor(s)!=='A')return notify('Only the room host can start the online draft.');if(!s.online.readyA||!s.online.readyB)return notify('Both players must be ready first.');if(!s.online.guestPresent)return notify('Waiting for Player B to join.');const baseStart=window.PPCDraftOnline._baseStart;baseStart('online');const fresh=session();fresh.opponent='online';fresh.playerA.name=fresh.playerA.name||'Player A';fresh.playerB.name=fresh.playerB.name==='CPU'?'Player B':fresh.playerB.name;fresh.online={...s.online,...fresh.online,role:'A'};saveLocal(fresh);await pushState('draft')}
async function reconnect(){const s=session();if(!s?.online?.roomId||!signedIn())return false;const c=client();if(!c)return false;const {data,error}=await c.rpc('get_draft_room',{p_room_id:s.online.roomId});if(error||!data){lastError=error?.message||'Could not reconnect';augment();return false}const row=normalizeRow(data);applyRow(row,roleFor(s));subscribe(row.id,roleFor(s));return true}
function onlinePanel(s){if(!s?.online?.roomId)return `<section class="panel draftOnlinePanel"><div class="between"><div><span class="eyebrow">ONLINE DRAFT ROOM</span><h2>Play with a friend</h2><p class="muted">Create a server-synced room or enter a friend's generated room code.</p></div><span class="pill">SUPABASE REALTIME</span></div><div class="draftOnlineActions"><button onclick="PPCDraftOnline.createRoom()" ${busy?'disabled':''}>Create Online Room</button><div class="draftJoin"><input id="draftJoinCode" autocomplete="off" spellcheck="false" placeholder="PLASMA-DRAGON-7K" oninput="this.value=this.value.toUpperCase()"><button class="secondary" onclick="PPCDraftOnline.joinRoom()" ${busy?'disabled':''}>Join Room</button></div></div>${lastError?`<p class="dangerBox">${String(lastError).replace(/[&<>]/g,'')}</p>`:''}</section>`;
const role=roleFor(s),mine=role==='A'?!!s.online.readyA:!!s.online.readyB;return `<section class="panel draftOnlinePanel"><div class="between"><div><span class="eyebrow">ONLINE ROOM · ${statusText(s)}</span><h2>${s.roomCode}</h2><p class="muted">You are Player ${role||'?'} · ${s.online.guestPresent?'2/2 players connected':'Waiting for Player B'}</p></div><span class="pill">v${Number(s.online.version||1)}</span></div><div class="draftReadyGrid"><article><small>PLAYER A</small><strong>${s.online.readyA?'✓ READY':'NOT READY'}</strong></article><article><small>PLAYER B</small><strong>${s.online.readyB?'✓ READY':'NOT READY'}</strong></article></div><div class="row"><button onclick="PPCDraftOnline.toggleReady()">${mine?'Unready':'Ready'}</button>${role==='A'?`<button onclick="PPCDraftOnline.startOnline()" ${(!s.online.readyA||!s.online.readyB||!s.online.guestPresent)?'disabled':''}>Start Online Draft</button>`:''}<button class="secondary" onclick="PPCDraftOnline.pull()">Refresh Room</button></div>${lastError?`<p class="dangerBox">${String(lastError).replace(/[&<>]/g,'')}</p>`:''}</section>`}
function augment(){const s=session(),root=document.querySelector('.ppcDraftShell');if(!root)return;root.querySelector('.draftOnlinePanel')?.remove();if(s?.status==='lobby'){const hero=root.querySelector('.draftHero');if(hero)hero.insertAdjacentHTML('afterend',onlinePanel(s))}if(s?.online?.roomId){const isTurn=(s.current?.picker||'')===roleFor(s);root.querySelectorAll('.draftPkg').forEach(btn=>{if(s.status==='draft'&&!isTurn){btn.disabled=true;btn.title='Waiting for the other player';}});const hero=root.querySelector('.draftHero');if(hero&&!hero.querySelector('.draftLiveBadge'))hero.insertAdjacentHTML('beforeend',`<span class="pill draftLiveBadge">${statusText(s)} · PLAYER ${roleFor(s)||'?'}</span>`)}}
function install(){if(!window.PPCDraftMode||window.PPCDraftOnlineInstalled)return;window.PPCDraftOnlineInstalled=true;const baseRender=PPCDraftMode.render,baseOpen=PPCDraftMode.open,baseChoose=PPCDraftMode.choose,baseStart=PPCDraftMode.start;window.PPCDraftOnline._baseStart=baseStart;PPCDraftMode.render=function(){const r=baseRender.apply(this,arguments);queueMicrotask(augment);return r};PPCDraftMode.open=function(){const r=baseOpen.apply(this,arguments);setTimeout(()=>{augment();reconnect()},180);return r};PPCDraftMode.choose=function(which){const before=session();if(before?.online?.roomId){if((before.current?.picker||'')!==roleFor(before))return notify('Waiting for the other player to make this pick.');baseChoose.call(PPCDraftMode,which);pushState(session()?.status||null);return}return baseChoose.call(PPCDraftMode,which)};const style=document.createElement('style');style.textContent=`.draftOnlinePanel{margin:0 0 18px}.draftOnlineActions,.draftJoin{display:flex;gap:10px;align-items:center}.draftOnlineActions{justify-content:space-between;flex-wrap:wrap}.draftJoin input{min-width:220px;text-transform:uppercase}.draftReadyGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}.draftReadyGrid article{padding:12px;border:1px solid rgba(255,255,255,.1);border-radius:12px}.draftReadyGrid small,.draftReadyGrid strong{display:block}@media(max-width:650px){.draftOnlineActions,.draftJoin{align-items:stretch;flex-direction:column}.draftJoin input{min-width:0;width:100%}}`;document.head.appendChild(style);queueMicrotask(augment)}
window.PPCDraftOnline={version:'8.69.4',createRoom,joinRoom,toggleReady,startOnline,pull,reconnect,pushState,subscribe,unsubscribe,_baseStart:null};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0),{once:true});else setTimeout(install,0);
})();