/* V8.65 RC1 — Pocket Coach Matchup Drill-Down (presentation only) */
(function(){
 if(window.__ppcCoachMatchupDrilldown)return;
 window.__ppcCoachMatchupDrilldown=true;
 const registry=new Map();let seq=0;
 const h=v=>typeof window.esc==='function'?window.esc(String(v??'')):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const eq=(a,b)=>String(a||'').trim().toLowerCase()===String(b||'').trim().toLowerCase();
 function ensureStyles(){if(document.getElementById('coachMatchupDrilldownStyles'))return;const s=document.createElement('style');s.id='coachMatchupDrilldownStyles';s.textContent=`
.coachThreat[data-coach-matchup-key]{cursor:pointer;position:relative;transition:border-color .16s ease,transform .16s ease,background .16s ease}.coachThreat[data-coach-matchup-key]:hover,.coachThreat[data-coach-matchup-key]:focus-visible{border-color:rgba(129,140,248,.55);background:rgba(30,41,59,.72);transform:translateY(-1px);outline:none}.coachThreatOpen{display:block;margin-top:7px;font-size:10px;font-weight:800;color:#a5b4fc}.coachMatchupDetailBackdrop{position:fixed;inset:0;z-index:12000;background:rgba(2,6,23,.78);backdrop-filter:blur(8px);display:grid;place-items:center;padding:18px}.coachMatchupDetail{width:min(760px,100%);max-height:min(88vh,860px);overflow:auto;border:1px solid rgba(148,163,184,.22);border-radius:18px;background:#0f172a;box-shadow:0 24px 80px rgba(0,0,0,.45);padding:18px}.coachMatchupDetailTop{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.coachMatchupDetailTop h2{margin:3px 0 4px;font-size:20px}.coachMatchupDetailTop p{margin:0;color:var(--muted,#94a3b8);font-size:12px}.coachMatchupClose{min-width:40px}.coachMatchupMetricGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:15px 0}.coachMatchupMetric{padding:10px;border:1px solid rgba(148,163,184,.14);border-radius:11px;background:rgba(2,6,23,.35)}.coachMatchupMetric strong{display:block;font-size:17px}.coachMatchupMetric span{font-size:10px;color:var(--muted,#94a3b8);text-transform:uppercase;letter-spacing:.05em}.coachMatchupEvidence{padding:10px 12px;border-radius:11px;background:rgba(59,130,246,.09);border:1px solid rgba(96,165,250,.18);font-size:12px;color:#cbd5e1}.coachMatchupEvidence.low{background:rgba(234,179,8,.08);border-color:rgba(250,204,21,.2)}.coachMatchupDetailSections{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.coachMatchupDetailSection{padding:12px;border-radius:12px;background:rgba(2,6,23,.28);border:1px solid rgba(148,163,184,.12)}.coachMatchupDetailSection h3{font-size:12px;margin:0 0 8px;text-transform:uppercase;letter-spacing:.05em}.coachMatchupDetailSection.help h3{color:#86efac}.coachMatchupDetailSection.review h3{color:#fcd34d}.coachMatchupDetailCard{padding:8px 0;border-top:1px solid rgba(148,163,184,.1);font-size:12px}.coachMatchupDetailCard:first-of-type{border-top:0;padding-top:0}.coachMatchupDetailCard small{display:block;color:var(--muted,#94a3b8);margin-top:2px}.coachMatchupActions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.coachMatchupActions button{flex:1 1 180px}.coachMatchupSnapshot{margin-top:10px;font-size:10px;color:var(--muted,#94a3b8)}@media(max-width:640px){.coachMatchupDetailBackdrop{padding:10px}.coachMatchupDetail{padding:14px;border-radius:15px}.coachMatchupMetricGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.coachMatchupDetailSections{grid-template-columns:1fr}.coachMatchupDetailTop h2{font-size:18px}}
`;document.head.appendChild(s)}
 function register(deck,threat){const key='m'+(++seq);const recs=Array.isArray(deck?.recommendations)?deck.recommendations:[];registry.set(key,{deck,threat,helps:recs.filter(r=>r?.action==='consider-matchup-tech'&&eq(r?.opponentArchetype,threat?.opponentName)),reviews:recs.filter(r=>r?.action==='review-for-matchup'&&eq(r?.opponentArchetype,threat?.opponentName))});return key}
 function decorate(html,report){if(!html)return html;ensureStyles();const t=document.createElement('template');t.innerHTML=html;const decks=Array.isArray(report)?report:[];t.content.querySelectorAll('.coachMatchupDeck').forEach((deckEl,di)=>{const deck=decks[di]||{};const threats=Array.isArray(deck.topThreats)?deck.topThreats:[];deckEl.querySelectorAll('.coachThreat').forEach((el,ti)=>{const threat=threats[ti];if(!threat)return;const key=register(deck,threat);el.setAttribute('data-coach-matchup-key',key);el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`Open matchup details for ${threat.opponentName||'opponent'}`);el.insertAdjacentHTML('beforeend','<span class="coachThreatOpen">View matchup details →</span>')})});return t.innerHTML}
 const base=window.coachMatchupReportHtml;if(typeof base==='function')window.coachMatchupReportHtml=function(report){return decorate(base(report),report)};
 function deltaText(r){const d=r?.evidence?.deltaWinRate;if(d==null||!Number.isFinite(Number(d)))return'';const n=Number(d);return `${n>0?'+':''}${n.toFixed(1)} pts vs matchup baseline`}
 function cardsHtml(rows,kind){if(!rows.length)return '<div class="muted">No supported signal for this matchup.</div>';return rows.slice(0,6).map(r=>`<div class="coachMatchupDetailCard"><strong>${h(r.cardName||'Card')}</strong><small>${h(deltaText(r))}${r.confidence?`${deltaText(r)?' • ':''}${h(r.confidence)}`:''}${kind==='review'?' • review only':''}</small></div>`).join('')}
 window.coachCloseMatchupDetail=function(){document.getElementById('coachMatchupDetailBackdrop')?.remove()};
 window.coachOpenMatchupDetail=function(key){const x=registry.get(String(key));if(!x)return;ensureStyles();window.coachCloseMatchupDetail();const {deck,threat,helps,reviews}=x;const evidence=String(threat?.evidence||'low');const low=evidence==='low'||String(threat?.band||'').includes('insufficient');const snapshot=deck?.snapshotGeneratedAt?new Date(deck.snapshotGeneratedAt).toLocaleString():'';const backdrop=document.createElement('div');backdrop.id='coachMatchupDetailBackdrop';backdrop.className='coachMatchupDetailBackdrop';backdrop.innerHTML=`<section class="coachMatchupDetail" role="dialog" aria-modal="true" aria-labelledby="coachMatchupDetailTitle"><div class="coachMatchupDetailTop"><div><span class="eyebrow">MATCHUP DETAIL</span><h2 id="coachMatchupDetailTitle">${h(deck?.archetypeName||deck?.deckName||'Your deck')} vs ${h(threat?.opponentName||'Opponent')}</h2><p>${h(deck?.deckName||'Deck')} • ${h(String(threat?.band||'insufficient evidence').replace(/-/g,' '))}</p></div><button class="secondary coachMatchupClose" type="button" onclick="coachCloseMatchupDetail()" aria-label="Close matchup details">✕</button></div><div class="coachMatchupMetricGrid"><div class="coachMatchupMetric"><strong>${threat?.winRate==null?'—':Number(threat.winRate).toFixed(1)+'%'}</strong><span>Matchup WR</span></div><div class="coachMatchupMetric"><strong>${Number(threat?.opponentUsagePct||0).toFixed(1)}%</strong><span>Meta share</span></div><div class="coachMatchupMetric"><strong>${Number(threat?.matches||0)}</strong><span>Games</span></div><div class="coachMatchupMetric"><strong>${h(evidence)}</strong><span>Confidence</span></div></div><div class="coachMatchupEvidence ${low?'low':''}">${low?'Evidence is limited. Treat this matchup as a preparation signal, not a firm conclusion.':'Observed matchup data supports this direction, but it is still sample-dependent and does not prove that any individual card caused the result.'}</div><div class="coachMatchupDetailSections"><section class="coachMatchupDetailSection help"><h3>Cards helping / test</h3>${cardsHtml(helps,'help')}</section><section class="coachMatchupDetailSection review"><h3>Cards to review</h3>${cardsHtml(reviews,'review')}</section></div><div class="coachMatchupActions"><button type="button" onclick="coachBuildMatchupPlan('${key}')">Build Matchup Plan</button><button class="secondary" type="button" onclick="coachAskAboutMatchup('${key}')">Ask Pocket Coach</button><button class="secondary" type="button" onclick="coachOpenMetaFromMatchup()">Open Meta Center</button></div>${snapshot?`<div class="coachMatchupSnapshot">Report snapshot: ${h(snapshot)}</div>`:''}</section>`;backdrop.addEventListener('click',e=>{if(e.target===backdrop)window.coachCloseMatchupDetail()});document.body.appendChild(backdrop);setTimeout(()=>backdrop.querySelector('.coachMatchupClose')?.focus(),0)};
 window.coachAskAboutMatchup=function(key){const x=registry.get(String(key));if(!x)return;const deck=x.deck?.deckName||x.deck?.archetypeName||'my deck',opp=x.threat?.opponentName||'this matchup';window.coachCloseMatchupDetail();if(typeof window.coachUsePrompt==='function')window.coachUsePrompt(`Help me prepare ${deck} for the ${opp} matchup. Use the saved Matchup Report evidence, explain what I should practice, which cards are worth testing, and which cards are review-only.`);else{const input=document.getElementById('coachInput');if(input){input.value=`Help me prepare ${deck} for the ${opp} matchup.`;input.focus()}}};
 window.coachBuildMatchupPlan=function(key){const x=registry.get(String(key));if(!x)return;const deck=x.deck?.deckName||x.deck?.archetypeName||'my deck',opp=x.threat?.opponentName||'this matchup';window.coachCloseMatchupDetail();const prompt=`Build a verified matchup plan for ${deck} into ${opp}. Use only PocketNexus verified matchup-plan and verified card-gameplay evidence. Separate OPENING SETUP, PRESERVE / PIVOT TOOLS, PRESSURE OPTIONS, GLOBAL META, and YOUR RESULTS. Do not invent an optimal turn order or opponent target priority when verified opponent card facts are missing. Explain what is board-state dependent.`;if(typeof window.coachUsePrompt==='function')window.coachUsePrompt(prompt);else{const input=document.getElementById('coachInput');if(input){input.value=prompt;input.focus()}}};
 window.coachOpenMetaFromMatchup=function(){window.coachCloseMatchupDetail();if(typeof window.headerNavigate==='function')window.headerNavigate('meta')};
 document.addEventListener('click',e=>{const el=e.target?.closest?.('[data-coach-matchup-key]');if(el)window.coachOpenMatchupDetail(el.getAttribute('data-coach-matchup-key'))});
 document.addEventListener('keydown',e=>{const el=e.target?.closest?.('[data-coach-matchup-key]');if(el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();window.coachOpenMatchupDetail(el.getAttribute('data-coach-matchup-key'));return}if(e.key==='Escape'&&document.getElementById('coachMatchupDetailBackdrop'))window.coachCloseMatchupDetail()});
})();
