/* PocketNexus V8.68.1 — OBS2 preview stability hotfix.
   Keeps the existing OBS2 implementation intact, but prevents the embedded
   preview from being repeatedly destroyed/reloaded while Streamer renders. */
(function(){
'use strict';
if(window.PPCStreamerOBS2)return;
const MODES=['ranked','tournament','caster'],STORE_PREFIX='ppc_stream_overlay_v868_',CHANNEL_PREFIX='ppc-stream-v868-';
const SOURCE={ranked:'overlay-ranked.html',tournament:'overlay-tournament.html',caster:'overlay-caster.html'};
const DEFAULTS={ranked:{preset:'full',theme:'dark',opacity:92,scale:100,recentCount:5,anchor:'bottom-center',entrance:'fade'},tournament:{preset:'full',theme:'dark',opacity:94,scale:100,anchor:'bottom-center',entrance:'fade'},caster:{preset:'top',theme:'dark',opacity:96,scale:100,anchor:'top-center',entrance:'slide'}};
const safe=(fn,f=null)=>{try{return fn()}catch{return f}};
function mode(){return safe(()=>state.streamer.overlayMode,'ranked')||'ranked'}
function ensure(){const s=state.streamer||(state.streamer={});s.overlays=s.overlays||{};for(const m of MODES)s.overlays[m]={...DEFAULTS[m],...(s.overlays[m]||{})};return s.overlays}
function config(m=mode()){return ensure()[m]||ensure().ranked}
function sourceUrl(m=mode()){try{return new URL(SOURCE[m]||SOURCE.ranked,location.href).href}catch{return SOURCE[m]||SOURCE.ranked}}
function payloadFor(m){const d=safe(()=>window.__ppcObs2BaseBuild?window.__ppcObs2BaseBuild():buildStreamerOverlayState(),{})||{};d.config={...(d.config||{}),...config(m),overlayMode:m};d.overlayProduct=m;d.version='8.68.1';return d}
function publishOne(m){const d=payloadFor(m);safe(()=>localStorage.setItem(STORE_PREFIX+m,JSON.stringify(d)));safe(()=>{const c=new BroadcastChannel(CHANNEL_PREFIX+m);c.postMessage({type:'state',data:d,at:Date.now()});c.close()});return d}
function publishAll(){const out={};for(const m of MODES)out[m]=publishOne(m);return out}
function previewSrc(m){const u=new URL(SOURCE[m],location.href);u.searchParams.set('embedded','1');u.searchParams.set('v','868101');return u.href}
function refreshPreview(m=mode()){const f=document.querySelector(`iframe[data-obs-mode="${m}"]`);if(!f)return;const u=new URL(previewSrc(m));u.searchParams.set('refresh',String(Date.now()));f.src=u.href}
function set(key,value,m=mode()){if(['opacity','scale','recentCount'].includes(key))value=Number(value);if(/^show/.test(key))value=!!value;config(m)[key]=value;safe(()=>save());publishAll();return value}
function copySource(m=mode()){const u=sourceUrl(m);if(navigator.clipboard?.writeText)navigator.clipboard.writeText(u);else safe(()=>copyFallbackDialog(u,'OBS source'))}
function reset(m=mode()){state.streamer.overlays[m]={...DEFAULTS[m]};safe(()=>save());publishAll();safe(()=>streamerPage())}
function editorHtml(m){const c=config(m),label=m==='caster'?'Tournament Caster':m==='tournament'?'Tournament Player':'Ranked';return `<section class="pnObsStudio" data-mode="${m}"><header class="pnObsStudioHead"><div><span class="pnObsEyebrow">${label.toUpperCase()} STREAM STUDIO</span><h2>${label} OBS Studio</h2><p>Configure this broadcast without leaving PocketNexus.</p></div><div class="pnObsActions"><button class="secondary" onclick="PPCStreamerOBS2.copySource('${m}')">Copy OBS Source</button><button class="secondary" onclick="window.open('${SOURCE[m]}','_blank')">Open Full Overlay</button><button class="secondary" onclick="PPCStreamerOBS2.refreshPreview('${m}')">Refresh Preview</button></div></header><div class="pnObsStatusRow"><span class="pnObsStatus active">Preview: Active</span><span class="pnObsStatus" id="pnObsExternalStatus">OBS Browser Source: Waiting</span><span class="pnObsCanvas">1920 × 1080</span></div><div class="pnObsStudioGrid"><div class="pnObsPreviewCard"><div class="pnObsViewport"><iframe data-obs-mode="${m}" title="${label} OBS preview" src="${previewSrc(m)}"></iframe></div></div><aside class="pnObsSettings"><div class="pnObsField"><label>Layout</label><select onchange="PPCStreamerOBS2.set('preset',this.value,'${m}')"><option value="full">Full</option><option value="compact">Compact</option><option value="minimal">Minimal</option><option value="match">Match Focus</option></select></div><div class="pnObsField"><label>Theme</label><select onchange="PPCStreamerOBS2.set('theme',this.value,'${m}')"><option value="dark">Dark</option><option value="light">Light</option><option value="transparent">Transparent</option><option value="blue">PocketNexus Blue</option></select></div><details class="pnObsAdvanced"><summary>Advanced</summary><label>Opacity <input type="range" min="10" max="100" value="${c.opacity||90}" oninput="PPCStreamerOBS2.set('opacity',this.value,'${m}')"></label><label>Scale <input type="range" min="70" max="150" value="${c.scale||100}" oninput="PPCStreamerOBS2.set('scale',this.value,'${m}')"></label></details><button class="secondary dangerText" onclick="PPCStreamerOBS2.reset('${m}')">Reset ${label} Overlay</button></aside></div></section>`}
let applying=false,lastMode='';
function apply(){if(applying||safe(()=>state.page,'')!=='streamer')return;const app=document.getElementById('app');if(!app)return;ensure();const m=mode();const existing=app.querySelector(`.pnObsStudio[data-mode="${m}"]`);if(existing&&existing.querySelector(`iframe[data-obs-mode="${m}"]`)){publishAll();return}applying=true;try{app.querySelectorAll('.pnObsStudio').forEach(x=>x.remove());[...app.querySelectorAll('[data-streamer-section="obs"],#streamPreview')].forEach(x=>{const p=x.id==='streamPreview'?x.closest('.panel'):x;if(p)p.style.display='none'});const host=document.createElement('div');host.innerHTML=editorHtml(m);const studio=host.firstElementChild;app.appendChild(studio);const c=config(m);const sels=studio.querySelectorAll('select');if(sels[0])sels[0].value=c.preset||'full';if(sels[1])sels[1].value=c.theme||'dark';const f=studio.querySelector('iframe');if(f)f.addEventListener('load',()=>publishAll(),{once:true});lastMode=m;publishAll()}finally{applying=false}}
function install(){ensure();if(typeof window.buildStreamerOverlayState==='function'&&!window.__ppcObs2BaseBuild)window.__ppcObs2BaseBuild=window.buildStreamerOverlayState.bind(window);if(typeof window.streamerPage==='function'&&!window.streamerPage.__obs2Stable){const base=window.streamerPage;window.streamerPage=function(){const out=base.apply(this,arguments);requestAnimationFrame(()=>requestAnimationFrame(apply));return out};window.streamerPage.__obs2Stable=true}requestAnimationFrame(()=>requestAnimationFrame(apply))}
let tries=0,t=setInterval(()=>{install();if(++tries>40)clearInterval(t)},100);window.PPCStreamerOBS2={version:'8.68.1',ensure,config,set,reset,sourceUrl,copySource,publishAll,refreshPreview,apply,install};
})();