/* PocketNexus V8.68.3 — Limitless Live Table UI for Tournament/Caster OBS
   Public data only. Auto-follows public rounds/tables; never attempts judge/admin/private access. */
(function(){
'use strict';
if(window.PPCStreamerLimitlessLiveTable)return;
const safe=(fn,f=null)=>{try{return fn()}catch{return f}};
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
let data=null,timer=null,busy=false;
function s(){state.streamer=state.streamer||{};state.streamer.limitlessLive=state.streamer.limitlessLive||{};const x=state.streamer.limitlessLive;if(x.autoRefresh===undefined)x.autoRefresh=true;if(!x.refreshSeconds)x.refreshSeconds=25;return x}
function style(){if(document.getElementById('pnLimitlessLiveStyle'))return;const x=document.createElement('style');x.id='pnLimitlessLiveStyle';x.textContent=`
.pnLiveTable{margin:0 0 18px;padding:16px;border:1px solid rgba(130,170,255,.22);border-radius:16px;background:rgba(12,18,30,.72)}
.pnLiveTableHead{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px}.pnLiveTableHead h3{margin:3px 0}.pnLiveTableHead p{margin:0;color:var(--muted,#9aa4b5)}
.pnLiveEyebrow{font-size:11px;letter-spacing:.12em;font-weight:800;color:#8fb5ff}.pnLiveGrid{display:grid;grid-template-columns:minmax(240px,2fr) 1fr 1fr auto;gap:10px;align-items:end}.pnLiveField{display:grid;gap:6px}.pnLiveField label{font-size:12px;color:var(--muted,#9aa4b5);font-weight:700}.pnLiveField input,.pnLiveField select{width:100%}
.pnLiveMatch{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:stretch;margin-top:14px}.pnLivePlayer{padding:13px;border:1px solid rgba(255,255,255,.10);border-radius:13px;background:rgba(255,255,255,.035)}.pnLivePlayer small{display:block;color:var(--muted,#9aa4b5);margin-bottom:4px}.pnLivePlayer b{display:block;font-size:16px}.pnLivePlayer span{display:block;margin-top:5px;color:#b8c8e8;font-size:13px}.pnLiveDeckState{font-size:11px!important;opacity:.76}.pnLiveVs{display:grid;place-items:center;font-weight:900;color:var(--muted,#9aa4b5)}
.pnLiveActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.pnLiveStatus{font-size:12px;color:var(--muted,#9aa4b5);margin-top:9px}.pnLiveStatus.good{color:#79d79b}.pnLiveStatus.bad{color:#ff9292}.pnLiveAuto{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--muted,#9aa4b5);white-space:nowrap}.pnLiveAuto input{accent-color:#7ea7ff}.pnLiveMeta{display:flex;gap:12px;flex-wrap:wrap;margin-top:10px;font-size:11px;color:var(--muted,#9aa4b5)}
@media(max-width:820px){.pnLiveGrid{grid-template-columns:1fr 1fr}.pnLiveGrid .wide{grid-column:1/-1}.pnLiveMatch{grid-template-columns:1fr}.pnLiveVs{min-height:24px}}
@media(max-width:520px){.pnLiveGrid{grid-template-columns:1fr}.pnLiveGrid .wide{grid-column:auto}.pnLiveTableHead{display:block}.pnLiveTableHead>div:last-child{margin-top:10px}.pnLiveTableHead button{width:100%}}
`;document.head.appendChild(x)}
function currentMode(){return safe(()=>state.streamer.overlayMode,'ranked')||'ranked'}
function deckLabel(p){return p?.decklist?.archetype||p?.deck||'Archetype unavailable'}
function hasDeck(p){return !!p?.decklist?.cards}
function matchHtml(match){if(!match)return '<div class="pnLiveStatus">Load a tournament, then choose a round and table.</div>';const player=(p,label)=>`<div class="pnLivePlayer"><small>${label}</small><b>${esc(p?.name||'Unknown Player')}</b><span>${esc(deckLabel(p))}</span><span class="pnLiveDeckState">${hasDeck(p)?'Public decklist available • QR enabled':'Full decklist not public'}</span></div>`;return `<div class="pnLiveMatch">${player(match.playerA,'PLAYER A')}<div class="pnLiveVs">VS</div>${player(match.playerB,'PLAYER B')}</div>`}
function panel(){const m=currentMode(),cfg=s(),rounds=data?PPCLimitlessLiveTable.rounds(data):[],round=cfg.round??rounds.at(-1)??'',tables=data&&round!==''?PPCLimitlessLiveTable.tables(data,round):[],table=cfg.table??tables[0]??'',match=data&&round!==''&&table!==''?PPCLimitlessLiveTable.resolveTable(data,round,table):null;return `<section class="pnLiveTable" data-limitless-live><div class="pnLiveTableHead"><div><span class="pnLiveEyebrow">PUBLIC LIMITLESS LIVE TABLE</span><h3>${m==='caster'?'Caster Match Source':'Tournament Match Source'}</h3><p>Player names, archetypes, public decklists and QR panels feed the OBS overlay automatically.</p></div><div><label class="pnLiveAuto"><input type="checkbox" ${cfg.autoRefresh!==false?'checked':''} onchange="PPCStreamerLimitlessLiveTable.toggleAuto(this.checked)"> Auto-follow every ${Number(cfg.refreshSeconds||25)}s</label><button class="secondary" onclick="PPCStreamerLimitlessLiveTable.refresh()">Refresh Now</button></div></div><div class="pnLiveGrid"><div class="pnLiveField wide"><label>Limitless Tournament URL or ID</label><input id="pnLiveTournament" value="${esc(cfg.tournament||'')}" placeholder="https://play.limitlesstcg.com/tournament/..."></div><div class="pnLiveField"><label>Round</label><select id="pnLiveRound" onchange="PPCStreamerLimitlessLiveTable.roundChanged(this.value)"><option value="">—</option>${rounds.map(r=>`<option value="${esc(r)}" ${String(r)===String(round)?'selected':''}>Round ${esc(r)}</option>`).join('')}</select></div><div class="pnLiveField"><label>Table</label><select id="pnLiveTableSelect" onchange="PPCStreamerLimitlessLiveTable.tableChanged(this.value)"><option value="">—</option>${tables.map(t=>`<option value="${esc(t)}" ${String(t)===String(table)?'selected':''}>Table ${esc(t)}</option>`).join('')}</select></div><button onclick="PPCStreamerLimitlessLiveTable.load()">Load Tournament</button></div>${matchHtml(match)}${match?`<div class="pnLiveActions">${m==='caster'?`<button onclick="PPCStreamerLimitlessLiveTable.sendCaster()">Send + Auto-Follow This Table</button>`:`<button onclick="PPCStreamerLimitlessLiveTable.sendTournament('A')">Follow Player A</button><button class="secondary" onclick="PPCStreamerLimitlessLiveTable.sendTournament('B')">Follow Player B</button>`}</div>`:''}<div class="pnLiveMeta"><span>${cfg.followPlayerId?`Following player ID ${esc(cfg.followPlayerId)}`:`Following table ${esc(table||'—')}`}</span><span>${data?.fetchedAt?`Last update ${new Date(data.fetchedAt).toLocaleTimeString()}`:''}</span></div><div id="pnLiveStatus" class="pnLiveStatus">${data?`Loaded ${esc(data.details?.name||data.details?.title||data.id)} • public data only`:''}</div></section>`}
function mount(){if(safe(()=>state.page,'')!=='streamer')return;const m=currentMode();if(m==='ranked')return;style();const studio=document.querySelector(`.pnObsStudio[data-mode="${m}"]`);if(!studio)return;if(studio.querySelector('[data-limitless-live]'))return;studio.insertAdjacentHTML('afterbegin',panel());schedule()}
function status(txt,bad=false){const el=document.getElementById('pnLiveStatus');if(el){el.textContent=txt;el.className='pnLiveStatus '+(bad?'bad':'good')}}
function latestRound(d=data){const rs=d?PPCLimitlessLiveTable.rounds(d):[];return rs.at(-1)??''}
function findPlayerPairing(d,round,pid){return (d?.pairings||[]).find(p=>String(p.round)===String(round)&&(String(p.playerAId)===String(pid)||String(p.playerBId)===String(pid)))||null}
function followSelection(){const cfg=s(),m=currentMode(),r=latestRound();if(r==='')return;if(cfg.followPlayerId){const p=findPlayerPairing(data,r,cfg.followPlayerId);if(p){cfg.round=r;cfg.table=p.table;return}}if(cfg.followTable!==undefined&&cfg.followTable!==null&&cfg.followTable!==''){const ts=PPCLimitlessLiveTable.tables(data,r);if(ts.some(t=>String(t)===String(cfg.followTable))){cfg.round=r;cfg.table=cfg.followTable;return}}if(cfg.autoRefresh!==false){cfg.round=r;const ts=PPCLimitlessLiveTable.tables(data,r);if(!ts.some(t=>String(t)===String(cfg.table)))cfg.table=ts[0]??''}}
async function load(force=false,quiet=false){const input=(document.getElementById('pnLiveTournament')?.value||s().tournament||'').trim();if(!input){if(!quiet)status('Enter a Limitless tournament URL or ID.',true);return}if(busy)return;busy=true;if(!quiet)status('Loading public tournament data…');try{data=await PPCLimitlessLiveTable.fetchTournament(input,{force});const cfg=s();cfg.tournament=input;const rs=PPCLimitlessLiveTable.rounds(data);if(!rs.some(x=>String(x)===String(cfg.round)))cfg.round=rs.at(-1)??'';followSelection();const ts=PPCLimitlessLiveTable.tables(data,cfg.round);if(!ts.some(x=>String(x)===String(cfg.table)))cfg.table=ts[0]??'';safe(()=>save());if(quiet){autoPublish()}remount()}catch(e){if(!quiet)status(e?.message||'Could not load tournament.',true)}finally{busy=false}}
function remount(){document.querySelector('[data-limitless-live]')?.remove();mount()}
function roundChanged(v){const cfg=s();cfg.round=v;cfg.followPlayerId='';cfg.table=data?PPCLimitlessLiveTable.tables(data,v)[0]??'':'';cfg.followTable=cfg.table;safe(()=>save());remount()}
function tableChanged(v){const cfg=s();cfg.table=v;cfg.followTable=v;cfg.followPlayerId='';safe(()=>save());remount()}
function selected(){const cfg=s();return data?PPCLimitlessLiveTable.resolveTable(data,cfg.round,cfg.table):null}
function applyShared(match){if(!match)return false;const st=state.streamer;st.tournamentName=match.tournamentName||'Limitless Tournament';st.tournamentRound=`Round ${match.round}`;st.tournamentStage=st.tournamentStage||'Tournament';st.liveTable={...match,publicOnly:true,source:'Limitless public API',syncedAt:Date.now()};return true}
function sendCaster(quiet=false){const x=selected();if(!applyShared(x))return;const cfg=s();cfg.followPlayerId='';cfg.followTable=x.table;state.streamer.casterA=x.playerA?.name||'Player A';state.streamer.casterB=x.playerB?.name||'Player B';safe(()=>save());safe(()=>PPCStreamerOBS2.publishAll());if(!quiet)safe(()=>PPCStreamerOBS2.refreshPreview('caster'));if(!quiet)status(`Caster OBS updated: ${state.streamer.casterA} vs ${state.streamer.casterB}`)}
function sendTournament(side,quiet=false){const x=selected();if(!applyShared(x))return;const me=side==='B'?x.playerB:x.playerA,opp=side==='B'?x.playerA:x.playerB,cfg=s();cfg.followPlayerId=me?.id||'';cfg.followTable='';state.streamer.tournamentPlayerName=me?.name||'';state.streamer.controlOpponent=opp?.decklist?.archetype||opp?.deck||opp?.name||'';state.streamer.tournamentOpponentName=opp?.name||'';state.streamer.tournamentPublicDeck=me?.decklist||null;state.streamer.tournamentFollowSide=side;safe(()=>save());safe(()=>PPCStreamerOBS2.publishAll());if(!quiet)safe(()=>PPCStreamerOBS2.refreshPreview('tournament'));if(!quiet)status(`Tournament OBS now follows ${me?.name||'player'} across rounds.`)}
function autoPublish(){const m=currentMode();if(m==='caster')sendCaster(true);else if(m==='tournament'&&s().followPlayerId){const x=selected();if(x){const side=String(x.playerB?.id)===String(s().followPlayerId)?'B':'A';sendTournament(side,true)}}}
async function refresh(){return load(true,false)}
function toggleAuto(v){s().autoRefresh=!!v;safe(()=>save());schedule();status(v?'Auto-follow enabled.':'Auto-follow paused.')}
function schedule(){clearTimeout(timer);if(s().autoRefresh===false||safe(()=>state.page,'')!=='streamer'||currentMode()==='ranked'||!s().tournament)return;timer=setTimeout(async()=>{await load(true,true);schedule()},Math.max(15,Number(s().refreshSeconds||25))*1000)}
function hook(){if(typeof window.streamerPage==='function'&&!window.streamerPage.__limitlessLive){const base=window.streamerPage;window.streamerPage=function(){const out=base.apply(this,arguments);requestAnimationFrame(()=>requestAnimationFrame(mount));return out};window.streamerPage.__limitlessLive=true}requestAnimationFrame(()=>requestAnimationFrame(mount))}
let tries=0,t=setInterval(()=>{if(window.PPCLimitlessLiveTable&&window.PPCStreamerOBS2){hook();if(++tries>100)clearInterval(t)}},60);
window.PPCStreamerLimitlessLiveTable={version:'8.68.3',mount,load,refresh,roundChanged,tableChanged,sendCaster,sendTournament,selected,toggleAuto,schedule};
})();