-- PocketNexus V8.64.2 — Pocket Knowledge Engine v1
-- Applied to Supabase production on 2026-09-07.

create table if not exists public.game_knowledge (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('rule','card','set','archetype','meta','rank','tournament','mechanic','update','glossary')),
  entity_key text not null,
  title text not null,
  content text not null,
  source_name text not null default 'PocketNexus',
  source_url text,
  source_updated_at timestamptz,
  confidence text not null default 'verified' check (confidence in ('verified','derived','provisional')),
  metadata jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_vector tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(title,'')), 'A') ||
    setweight(to_tsvector('simple', coalesce(content,'')), 'B') ||
    setweight(to_tsvector('simple', coalesce(entity_key,'')), 'A')
  ) stored,
  unique(entity_type, entity_key)
);

create index if not exists game_knowledge_search_idx on public.game_knowledge using gin(search_vector);
create index if not exists game_knowledge_type_active_idx on public.game_knowledge(entity_type, active);
create index if not exists game_knowledge_updated_idx on public.game_knowledge(updated_at desc);

alter table public.game_knowledge enable row level security;
revoke all on public.game_knowledge from anon, authenticated;
grant select on public.game_knowledge to service_role;

create or replace function public.search_game_knowledge(p_query text, p_limit integer default 12)
returns table (
  id uuid,
  entity_type text,
  entity_key text,
  title text,
  content text,
  source_name text,
  source_url text,
  source_updated_at timestamptz,
  confidence text,
  metadata jsonb,
  score real
)
language sql
stable
security invoker
set search_path = public
as $$
  with terms as (
    select distinct regexp_replace(lower(w), '[^a-z0-9]+', '', 'g') as term
    from regexp_split_to_table(coalesce(p_query,''), E'\\s+') as w
    where length(regexp_replace(lower(w), '[^a-z0-9]+', '', 'g')) >= 2
      and regexp_replace(lower(w), '[^a-z0-9]+', '', 'g') not in (
        'what','when','where','which','who','why','how','the','and','for','with','from','this','that','should','would','could','about','into','your','you','are','was','were','have','has','had','does','did','can','all','any','its','his','her','our','their','game','pokemon','pocket','tcg'
      )
  ), q as (
    select case when count(*)=0 then null::tsquery
      else to_tsquery('simple', string_agg(term || ':*', ' | ' order by term)) end as query
    from terms
  )
  select g.id,g.entity_type,g.entity_key,g.title,g.content,g.source_name,g.source_url,g.source_updated_at,g.confidence,g.metadata,
         case when q.query is null then 0::real else ts_rank_cd(g.search_vector,q.query)::real end as score
  from public.game_knowledge g cross join q
  where g.active = true
    and (q.query is null or g.search_vector @@ q.query)
  order by score desc, g.updated_at desc
  limit greatest(1, least(coalesce(p_limit,12), 30));
$$;

revoke all on function public.search_game_knowledge(text, integer) from public;
grant execute on function public.search_game_knowledge(text, integer) to service_role;

insert into public.game_knowledge(entity_type,entity_key,title,content,source_name,source_url,source_updated_at,confidence,metadata)
values
('rule','deck-size','Deck construction — 20 cards','A legal Pokémon TCG Pocket battle deck contains exactly 20 cards. Energy is not part of those 20 cards because Energy is generated by the Energy Zone. Treat a saved deck with fewer or more than 20 cards as incomplete or illegal, not as a normal complete deck.','Pokémon','https://www.pokemon.com/uk/features/learn-how-to-build-a-deck-in-pokemon-tcg-pocket','2025-01-30T00:00:00Z','verified','{"topic":"deckbuilding","kind":"legality"}'::jsonb),
('rule','duplicate-limit','Deck construction — same-name copy limit','A Pokémon TCG Pocket deck may contain no more than two copies of cards with the same card name. Different artwork, rarity, set, or printing does not create extra copy allowance when the card name is the same. Count same-name copies together when auditing legality.','Pokémon','https://www.pokemon.com/uk/features/learn-how-to-build-a-deck-in-pokemon-tcg-pocket','2025-01-30T00:00:00Z','verified','{"topic":"deckbuilding","kind":"legality"}'::jsonb),
('rule','basic-pokemon-required','Deck construction — Basic Pokémon requirement','A usable Pokémon TCG Pocket deck must contain at least one Basic Pokémon. When analyzing a deck, distinguish this hard legality requirement from strategic advice about how many Basic Pokémon to run.','Pokémon','https://www.pokemon.com/uk/features/learn-how-to-build-a-deck-in-pokemon-tcg-pocket','2025-01-30T00:00:00Z','verified','{"topic":"deckbuilding","kind":"legality"}'::jsonb),
('mechanic','energy-system','Deck construction — Energy Zone','Pokémon TCG Pocket does not put Energy cards inside the 20-card deck. Energy comes from the Energy Zone. Energy types are a separate deck setting. When judging a deck, check whether the selected Energy types support the attacks the deck plans to use, and do not recommend adding Energy cards to fill deck slots.','Pokémon','https://www.pokemon.com/uk/strategy/learn-how-to-build-a-deck-in-pokemon-tcg-pocket','2025-01-30T00:00:00Z','verified','{"topic":"deckbuilding","kind":"mechanic"}'::jsonb),
('rule','deck-legality-vs-strategy','Deck construction — legality vs strategy','Pocket Coach must separate legal deck rules from strategic deckbuilding advice. Exactly 20 cards, at most two cards with the same name, and at least one Basic Pokémon are legality checks. Pokémon count, Trainer count, number of Basic Pokémon above one, evolution ratios, tech cards, and consistency choices are strategic decisions and should not be presented as mandatory rules.','PocketNexus deck analysis','https://www.pokemon.com/uk/features/learn-how-to-build-a-deck-in-pokemon-tcg-pocket','2025-01-30T00:00:00Z','derived','{"topic":"deckbuilding","kind":"analysis"}'::jsonb),
('rule','deck-primary-plan','Deck construction — primary game plan','With only 20 card slots, competitive deck construction should be analyzed around a primary win condition or main attacker plus cards that support that plan. Identify the main attacker or engine, setup pieces, search/draw/support cards, recovery or disruption, and any tech cards. Do not assume every strong card belongs in a deck if it does not support the deck plan.','PocketNexus deck analysis','https://www.pokemon.com/uk/features/learn-how-to-build-a-deck-in-pokemon-tcg-pocket','2025-01-30T00:00:00Z','derived','{"topic":"deckbuilding","kind":"strategy"}'::jsonb),
('rule','evolution-line-construction','Deck construction — evolution lines','When a deck contains Stage 1 or Stage 2 Pokémon, analyze whether the required lower-stage Pokémon are present and whether the counts are likely to make the evolution plan consistent. Missing required earlier stages are structural problems. Exact evolution ratios are strategic choices, not universal legality rules.','PocketNexus deck analysis',null,null,'derived','{"topic":"deckbuilding","kind":"structure"}'::jsonb),
('rule','basic-count-guidance','Deck construction — Basic Pokémon consistency','Pokémon official deckbuilding guidance notes that many decks benefit from roughly five or six Basic Pokémon, while some strategies use fewer or more. Pocket Coach should use this only as flexible consistency guidance, never as a hard requirement.','Pokémon','https://www.pokemon.com/uk/features/learn-how-to-build-a-deck-in-pokemon-tcg-pocket','2025-01-30T00:00:00Z','verified','{"topic":"deckbuilding","kind":"strategy-guidance"}'::jsonb),
('rule','deck-consistency-analysis','Deck construction — consistency and roles','When reviewing a deck, evaluate whether its 20 slots consistently execute the intended plan: enough opening Basic Pokémon for the strategy, complete evolution access when needed, sufficient search/draw/support, sensible duplicate counts for important cards, limited dead or highly situational cards, and Energy Zone settings that match the intended attacks. Avoid fixed Pokémon-versus-Trainer ratios unless current deck or meta evidence supports them.','PocketNexus deck analysis',null,null,'derived','{"topic":"deckbuilding","kind":"analysis"}'::jsonb),
('rule','win-points','Match victory points','Pokémon TCG Pocket battles are won by reaching the required point total through Knocking Out opposing Pokémon; Pokémon ex give additional points when Knocked Out. Pocket Coach should avoid inventing an exact point interaction when card-specific context is missing.','PocketNexus verified rules',null,null,'verified','{"topic":"battle"}'::jsonb)
on conflict(entity_type,entity_key) do update set title=excluded.title,content=excluded.content,source_name=excluded.source_name,source_url=excluded.source_url,source_updated_at=excluded.source_updated_at,confidence=excluded.confidence,metadata=excluded.metadata,active=true,updated_at=now();

insert into public.game_knowledge(entity_type,entity_key,title,content,source_name,source_updated_at,confidence,metadata)
select 'rank', 'threshold:'||id::text, display_name,
       'Rank threshold: '||display_name||' begins at '||min_rp||' RP'||case when max_rp is not null then ' and extends through '||max_rp||' RP.' else '.' end,
       'PocketNexus Rank Database', updated_at, 'verified',
       jsonb_build_object('rank_tier',rank_tier,'rank_level',rank_level,'min_rp',min_rp,'max_rp',max_rp,'is_master_ball',is_master_ball)
from public.rank_thresholds
on conflict(entity_type,entity_key) do update set title=excluded.title,content=excluded.content,source_updated_at=excluded.source_updated_at,metadata=excluded.metadata,updated_at=now();

insert into public.game_knowledge(entity_type,entity_key,title,content,source_name,source_updated_at,confidence,metadata)
select 'archetype', id, name,
       trim(concat_ws(' ',
         'Competitive archetype: '||name||'.',
         case when tier is not null then 'Tier: '||tier||'.' end,
         case when jsonb_array_length(coalesce(pokemon,'[]'::jsonb))>0 then 'Pokémon: '||pokemon::text||'.' end,
         case when jsonb_array_length(coalesce(key_cards,'[]'::jsonb))>0 then 'Key cards: '||key_cards::text||'.' end
       )),
       'PocketNexus Archetype Library', updated_at, 'derived',
       jsonb_build_object('tier',tier,'type',type,'pokemon',pokemon,'key_cards',key_cards,'aliases',aliases)
from public.meta_archetypes
where active=true
on conflict(entity_type,entity_key) do update set title=excluded.title,content=excluded.content,source_updated_at=excluded.source_updated_at,metadata=excluded.metadata,updated_at=now();
