import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const API="https://play.limitlesstcg.com/api/tournaments";
const WEB="https://play.limitlesstcg.com/tournament";
const PAGE_SIZE=50,COOLDOWN_MS=2*60*1000;
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function serverClient(){const url=Deno.env.get("SUPABASE_URL"),raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(!url||!raw)throw new Error("Supabase server credentials unavailable");const keys=JSON.parse(raw),key=keys.default??Object.values(keys)[0];if(!key)throw new Error("No Supabase server key found");return createClient(url,String(key),{auth:{persistSession:false,autoRefreshToken:false}})}
async function fetchJson(url:string,retries=2){let last:any;for(let i=0;i<=retries;i++){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"application/json","User-Agent":"PocketNexus/8.73"}});if(!r.ok)throw new Error(`Limitless ${r.status} ${r.statusText}`);return await r.json()}catch(e){last=e;if(i<retries)await sleep(500*Math.pow(2,i))}finally{clearTimeout(timer)}}throw last}
async function fetchHtml(url:string){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"text/html,application/xhtml+xml","User-Agent":"PocketNexus/8.73 (+https://beta.pocketnexus.app)"}});if(!r.ok)throw new Error(`Limitless page ${r.status} ${r.statusText}`);return await r.text()}finally{clearTimeout(timer)}}
function err(e:any){return e instanceof Error?e.message:String(e)}
function decodeHtml(s:string){return String(s||'').replace(/<[^>]*>/g,' ').replace(/&#(x?[0-9a-f]+);/gi,(_,n)=>{const x=String(n).toLowerCase().startsWith('x')?parseInt(String(n).slice(1),16):parseInt(n,10);return Number.isFinite(x)?String.fromCodePoint(x):_}).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\s+/g,' ').trim()}
function attr(attrs:string,name:string){const m=String(attrs||'').match(new RegExp(`${name}=["']([^"']*)["']`,'i'));return m?decodeHtml(m[1]):''}
function pageTournamentName(html:string){const h=String(html||'');const header=h.match(/<div class=["']tournament-header[^>]*>[\s\S]*?<div class=["']name["'][^>]*>([\s\S]*?)<\/div>/i);if(header)return decodeHtml(header[1]);const title=h.match(/<title>([\s\S]*?)<\/title>/i);return title?decodeHtml(title[1]).replace(/^(?:Pairings|Standings):\s*/i,'').replace(/\s*\|\s*Limitless\s*$/i,''):''}
function pageCurrentRound(html:string){const h=String(html||'');const rounds=[...h.matchAll(/<li\s+class=["'][^"']*active[^"']*["'][^>]*>\s*<a[^>]+href=["'][^"']*\/pairings(?:\?round=\d+)?[^"']*["'][^>]*>([\s\S]*?)<\/a>/gi)];if(rounds.length){const label=decodeHtml(rounds.at(-1)?.[1]||'');if(label)return label}const activeBracket=[...h.matchAll(/<div class=["']round["'][^>]*data-completed=["']0["'][^>]*>[\s\S]*?<div class=["']round-name["'][^>]*>([^<]+)<\/div>[\s\S]*?<div class=["']bracket-match[^"']*in-progress/gi)];if(activeBracket.length)return decodeHtml(activeBracket[0][1]);const bracket=h.match(/<div class=["']round["'][^>]*>[\s\S]*?<div class=["']round-name["'][^>]*>([^<]+)<\/div>[\s\S]*?<div class=["']live-bracket-player["'][^>]*data-id=/i);if(bracket)return decodeHtml(bracket[1]);return ''}
function stageForRound(round:string){const r=String(round||'').trim();if(/semi|top\s*4/i.test(r))return 'Top 4';if(/quarter|top\s*8/i.test(r))return 'Top 8';if(/final/i.test(r))return 'Finals';if(/top\s*(16|32|64)|cut|bracket/i.test(r))return 'Top Cut';if(/^\d+$|round/i.test(r))return 'Swiss';return r?'Top Cut':'Registration'}
function stageFromApi(details:any,pairings:any[]){const phases=Array.isArray(details?.phases)?details.phases:[],types=phases.map((p:any)=>String(p?.type||'').toUpperCase()),rows=Array.isArray(pairings)?pairings:[],bracketRows=rows.filter((p:any)=>Number(p?.phase||0)>1||/^(?:T(?:2|4|8|16|32|64)-|QF|SF|F)/i.test(String(p?.match||'')));if(bracketRows.length||types.some((t:string)=>/BRACKET|ELIM|TOP.?CUT|PLAYOFF/.test(t)))return 'Top Cut';if(rows.length||types.some((t:string)=>/SWISS/.test(t)))return 'Swiss';return 'Swiss'}
function parseStandings(html:string,id:string){const rows:any[]=[];for(const m of String(html||'').matchAll(/<tr\b([^>]*)data-placing=["']([^"']+)["']([^>]*)>([\s\S]*?)<\/tr>/gi)){const attrs=`${m[1]} data-placing="${m[2]}" ${m[3]}`,body=m[4];const link=body.match(new RegExp(`/tournament/${id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}/player/([^/"'?#]+)["'][^>]*>([\\s\\S]*?)<\\/a>`,'i'));if(!link)continue;const rec=body.match(/(\d+)\s*-\s*(\d+)\s*-\s*(\d+)/);rows.push({player:decodeHtml(link[1]),name:decodeHtml(link[2])||attr(attrs,'data-name'),placing:Number(m[2])||m[2],record:rec?{wins:Number(rec[1]),losses:Number(rec[2]),ties:Number(rec[3])}:null})}return rows}
function parseBracketPairings(html:string,id:string){const h=String(html||''),round=pageCurrentRound(h);if(!round||/^\d+$/.test(round))return [];const chunks=h.split(/(?=<div class=["']bracket-match)/i),out:any[]=[];for(const chunk of chunks){const slot=chunk.match(/<div class=["']bracket-match[^"']*["'][^>]*data-slot=["']([^"']+)["']/i);if(!slot)continue;const players=[...chunk.matchAll(new RegExp(`<div class=["']live-bracket-player["'][^>]*data-id=["']([^"']+)["'][^>]*>[\\s\\S]*?<a class=["'][^"']*name[^"']*["'][^>]*href=["']/tournament/${id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}/player/[^"']+["'][^>]*>([\\s\\S]*?)<\\/a>[\\s\\S]*?<div class=["']score["'][^>]*data-score=["']([^"']*)["']`,'gi'))].slice(0,2);if(players.length<2)continue;out.push({round,phase:round,table:decodeHtml(slot[1]),player1:{id:decodeHtml(players[0][1]),name:decodeHtml(players[0][2])},player2:{id:decodeHtml(players[1][1]),name:decodeHtml(players[1][2])},score:`${decodeHtml(players[0][3])}-${decodeHtml(players[1][3])}`})}return out}
async function lookupFromPages(id:string){const e=encodeURIComponent(id);const [detailsHtml,standingsHtml,pairingsHtml]=await Promise.all([fetchHtml(`${WEB}/${e}/details`),fetchHtml(`${WEB}/${e}/standings`),fetchHtml(`${WEB}/${e}/pairings`)]);const name=pageTournamentName(detailsHtml)||pageTournamentName(pairingsHtml)||id,currentRound=pageCurrentRound(pairingsHtml),stage=stageForRound(currentRound),standings=parseStandings(standingsHtml,id),pairings=parseBracketPairings(pairingsHtml,id);if(!name&&!standings.length&&!pairings.length)throw new Error('Limitless tournament page did not contain usable public data');if(!pairings.length&&currentRound)pairings.push({round:currentRound,phase:stage,table:null,player1:{},player2:{},score:null});return {ok:true,status:'lookup',tournamentId:id,details:{name,stage,phase:stage,source:'Limitless public tournament page'},standings,pairings,fetchedAt:new Date().toISOString(),source:'Limitless public tournament page',livePageFallback:true}}
async function lookupTournament(id:string){
  const clean=String(id||'').trim();
  if(!/^[A-Za-z0-9_-]{1,96}$/.test(clean))throw new Error('Invalid tournament ID');
  const e=encodeURIComponent(clean);
  const settled=await Promise.allSettled([fetchJson(`${API}/${e}/details`),fetchJson(`${API}/${e}/standings`),fetchJson(`${API}/${e}/pairings`)]);
  const details=settled[0].status==='fulfilled'?settled[0].value:null;
  const standings=settled[1].status==='fulfilled'&&Array.isArray(settled[1].value)?settled[1].value:[];
  const pairings=settled[2].status==='fulfilled'&&Array.isArray(settled[2].value)?settled[2].value:[];
  if(details||standings.length||pairings.length){const stage=stageFromApi(details,pairings),normalizedDetails=details?{...details,stage,phase:details?.phase??stage}:{stage,phase:stage};return {ok:true,status:'lookup',tournamentId:clean,details:normalizedDetails,standings,pairings,fetchedAt:new Date().toISOString(),source:'Limitless public API'}}
  return await lookupFromPages(clean);
}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});const db=serverClient();try{let body:any={};try{body=await req.json()}catch{}
if(body.scope==='lookup'){const result=await lookupTournament(body.tournamentId);return Response.json(result,{headers:{...CORS,'Cache-Control':'no-store'}})}
const scope=body.scope==='backfill'?'backfill':'recent',force=body.force===true,maxPages=Math.min(10,Math.max(1,Number(body.maxPages??(scope==='backfill'?4:3))||3));const {data:state}=await db.from('meta_collector_state').select('*').eq('collector','limitless-discovery').maybeSingle();const last=state?.last_started_at?new Date(state.last_started_at).getTime():0;if(!force&&last&&Date.now()-last<COOLDOWN_MS)return Response.json({ok:true,status:'cooldown',retryAfterSeconds:Math.ceil((COOLDOWN_MS-(Date.now()-last))/1000)},{headers:CORS});await db.from('meta_collector_state').update({last_started_at:new Date().toISOString(),updated_at:new Date().toISOString(),last_error:null}).eq('collector','limitless-discovery');const {data:source,error:sourceErr}=await db.from('meta_sources').select('id').eq('name','Limitless TCG').single();if(sourceErr||!source)throw sourceErr??new Error('Limitless source row missing');let page=scope==='backfill'?Math.max(1,Number(state?.next_backfill_page||1)):1;const startPage=page;let pagesFetched=0,totalRows=0,upserted=0,reachedEnd=false;const seen:string[]=[];for(let n=0;n<maxPages;n++,page++){const rows=await fetchJson(`${API}?game=POCKET&limit=${PAGE_SIZE}&page=${page}`);if(!Array.isArray(rows))throw new Error('Limitless tournament list was not an array');pagesFetched++;totalRows+=rows.length;seen.push(...rows.map((x:any)=>String(x?.id||'')).filter(Boolean));const {data:count,error:ingestErr}=await db.rpc('ingest_limitless_tournament_listings',{p_source_id:source.id,p_rows:rows,p_page:page});if(ingestErr)throw ingestErr;upserted+=Number(count||0);if(rows.length<PAGE_SIZE){reachedEnd=true;break}await sleep(250)}const nextBackfill=scope==='backfill'?(reachedEnd?1:page):Number(state?.next_backfill_page||1),now=new Date().toISOString();await db.from('meta_collector_state').update({last_success_at:now,last_error:null,next_backfill_page:nextBackfill,total_discovered:Number(state?.total_discovered||0)+upserted,metadata:{scope,startPage,pagesFetched,totalRows,reachedEnd,lastIds:seen.slice(0,10)},updated_at:now}).eq('collector','limitless-discovery');await db.from('meta_sources').update({last_success_at:now,last_error:null,updated_at:now}).eq('name','Limitless TCG');return Response.json({ok:true,status:'success',scope,startPage,pagesFetched,totalRows,upserted,reachedEnd,nextBackfillPage:nextBackfill},{headers:CORS})}catch(e){const message=err(e),now=new Date().toISOString();try{await db.from('meta_collector_state').update({last_error:message,updated_at:now}).eq('collector','limitless-discovery')}catch{}try{await db.from('meta_sources').update({last_error:message,updated_at:now}).eq('name','Limitless TCG')}catch{}return Response.json({ok:false,error:message},{status:500,headers:CORS})}});