function statisticsPage(){
 const legacyTab=state.battlePrefs.statsTab||"overview";
 const tab=({insights:"coaching",matchups:"intelligence",turn:"overview",sessions:"overview",trends:"overview"}[legacyTab]||legacyTab);
 if(tab!==legacyTab){state.battlePrefs.statsTab=tab;save();}
 const range=state.battlePrefs.statsRange||"all",windowMatches=statisticsWindowMatches(range),o=BattleAnalytics.overall(windowMatches),st=BattleAnalytics.streaks(windowMatches),tr=BattleAnalytics.trends(),turn=BattleAnalytics.turnOrder(windowMatches),rpInfo=analyticsRpSummary(windowMatches),intel=analyticsMatchupIntelligence(windowMatches);
 const tabs=[["overview","Overview"],["prep","Tournament Prep"],["coaching","Coaching"],["decks","Decks"],["personalmeta","Personal Meta"],["intelligence","Matchups"],["rank","Rank Progress"]];
 const rp=rpInfo.net;let body="";
 if(tab==="prep")body=tournamentPrepHtml(windowMatches);
 else if(tab==="personalmeta")body=personalMetaMatrixHtml(windowMatches);
 else if(tab==="coaching")body=actionableCoachingHtml(windowMatches);
 else if(tab==="insights")body=competitiveInsightsHtml(windowMatches);
 else if(tab==="decks"){const rows=analyticsDeckRp(windowMatches);body=`<div class="panel performanceDataPanel deckPerformancePanel"><div class="between"><div><h2>Deck Performance + RP</h2><p class="muted">See which decks win games and climb rank.</p></div><span class="pill">${o.n} matches</span></div><div class="tableScroll"><table class="performanceTable"><tr><th>Deck</th><th>Matches</th><th>Record</th><th>Win %</th><th>Net RP</th><th>Avg RP / ranked match</th></tr>${rows.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${x.n}</td><td>${x.w}-${x.l}</td><td>${x.wr.toFixed(1)}%</td><td class="${x.rp>=0?"good":"bad"}">${x.rp>0?"+":""}${x.rp}</td><td>${x.rpMatches?(x.avgRp>0?"+":"")+x.avgRp.toFixed(1):"—"}</td></tr>`).join("")||`<tr><td colspan="6" class="muted">No matches in this range.</td></tr>`}</table></div></div>`;}
 else if(tab==="matchups")body=`<div class="panel">${matchupMatrixHtml(windowMatches)}</div><div class="panel"><h2>Opponent Matchups</h2>${BattleAnalytics.byOpponent(windowMatches).map(x=>`<div class="between deckrow"><strong>${esc(x.name)}</strong><span>${x.w}-${x.l} • ${x.wr.toFixed(1)}% (${x.n})</span></div>`).join("")||`<p class="muted">No matchup data in this range.</p>`}</div>`;
 else if(tab==="intelligence")body=`<div class="panel intelligenceHeaderPanel"><div class="between"><div><span class="eyebrow">PERSONAL MATCHUPS</span><h2>Matchup Intelligence</h2><p class="muted">Best and hardest opponents using your own Battle Tracker data. Small samples are filtered out.</p></div><select style="width:auto" onchange="state.battlePrefs.matchupIntelMin=Number(this.value);save();statisticsPage()">${[1,3,5,10].map(n=>`<option value="${n}" ${intel.min===n?"selected":""}>Min ${n} matches</option>`).join("")}</select></div></div><div class="intelGrid"><div class="panel intelPanel intelBest"><div class="intelPanelHead"><span class="intelIcon good">↗</span><h2>Best Matchups</h2></div>${intel.best.map((x,i)=>`<div class="intelRow"><span class="intelRank">#${i+1}</span><div><strong>${esc(x.name)}</strong><div class="muted tiny">${x.w}-${x.l} • ${x.n} matches</div></div><div class="intelScore good">${x.wr.toFixed(1)}%<small>${x.rp?`${x.rp>0?"+":""}${x.rp} RP`:""}</small></div></div>`).join("")||`<p class="muted">Not enough matchup data yet.</p>`}</div><div class="panel intelPanel intelHard"><div class="intelPanelHead"><span class="intelIcon bad">!</span><h2>Hardest Matchups</h2></div>${intel.worst.map((x,i)=>`<div class="intelRow"><span class="intelRank">#${i+1}</span><div><strong>${esc(x.name)}</strong><div class="muted tiny">${x.w}-${x.l} • ${x.n} matches</div></div><div class="intelScore bad">${x.wr.toFixed(1)}%<small>${x.rp?`${x.rp>0?"+":""}${x.rp} RP`:""}</small></div></div>`).join("")||`<p class="muted">Not enough matchup data yet.</p>`}</div></div><div class="panel performanceDataPanel"><div class="between"><div><span class="eyebrow">ALL QUALIFYING MATCHUPS</span><h2>Full Matchup Report</h2></div><span class="pill">${intel.rows.length} matchups</span></div><div class="tableScroll"><table class="performanceTable"><tr><th>Opponent</th><th>Record</th><th>Win %</th><th>Matches</th><th>Net RP</th><th>Avg RP</th></tr>${intel.rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.w}-${x.l}</td><td class="${x.wr>=55?"good":x.wr<=45?"bad":""}">${x.wr.toFixed(1)}%</td><td>${x.n}</td><td class="${x.rp>=0?"good":"bad"}">${x.rp>0?"+":""}${x.rp}</td><td>${x.avgRp?(x.avgRp>0?"+":"")+x.avgRp.toFixed(1):"—"}</td></tr>`).join("")||`<tr><td colspan="6" class="muted">No qualifying matchups.</td></tr>`}</table></div></div>`;
 else if(tab==="turn")body=`<div class="metricgrid"><div class="metric"><div class="l">Going First</div><div class="n">${turn.first.n?turn.first.wr.toFixed(1)+"%":"—"}</div><div class="muted">${turn.first.w}-${turn.first.l} • ${turn.first.n}</div></div><div class="metric"><div class="l">Going Second</div><div class="n">${turn.second.n?turn.second.wr.toFixed(1)+"%":"—"}</div><div class="muted">${turn.second.w}-${turn.second.l} • ${turn.second.n}</div></div></div>`;
 else if(tab==="rank")body=`<div class="statsHeroGrid"><div class="metric statsHeroMetric"><div class="l">Net RP</div><div class="n ${rp>=0?"good":"bad"}">${rp>0?"+":""}${rp}</div><small>${rpInfo.n} ranked matches</small></div><div class="metric statsHeroMetric"><div class="l">Avg RP / Match</div><div class="n">${rpInfo.n?(rpInfo.avg>0?"+":"")+rpInfo.avg.toFixed(1):"—"}</div><small>with RP data</small></div><div class="metric statsHeroMetric"><div class="l">Best Gain</div><div class="n good">${rpInfo.best?"+"+rpInfo.best:"—"}</div><small>single match</small></div><div class="metric statsHeroMetric"><div class="l">Worst Loss</div><div class="n bad">${rpInfo.worst||"—"}</div><small>single match</small></div></div>${rpProgressionSvg(windowMatches)}<div style="margin-top:14px">${rankChartSvg(windowMatches)}</div>`;
 else if(tab==="sessions")body=`<div class="panel"><h2>Session History</h2>${sessionHistoryHtml()}</div>`;
 else if(tab==="trends")body=`<div class="metricgrid">${[["Last 5",tr.last5],["Last 10",tr.last10],["Last 25",tr.last25],["Last 50",tr.last50],["Last 7 Days",tr.d7],["Last 30 Days",tr.d30],["All Time",tr.all]].map(([n,x])=>`<div class="metric"><div class="l">${n}</div><div class="n">${x.n?x.wr.toFixed(1)+"%":"—"}</div><div class="muted">${x.n} matches</div></div>`).join("")}</div>`;
 else body=`<div class="statsHeroGrid"><div class="metric statsHeroMetric"><div class="l">Win Rate</div><div class="n">${o.n?o.wr.toFixed(1)+"%":"—"}</div><small>${esc(statisticsRangeLabel(range))}</small></div><div class="metric statsHeroMetric"><div class="l">Record</div><div class="n">${o.w}-${o.l}</div><small>${o.n} matches</small></div><div class="metric statsHeroMetric"><div class="l">RP Change</div><div class="n ${rp>=0?"good":"bad"}">${rp>0?"+":""}${rp}</div><small>${rpInfo.n} ranked matches</small></div><div class="metric statsHeroMetric"><div class="l">Overall Battle Streak</div><div class="n">${st.type==="none"?"—":(st.type==="win"?"W":"L")+st.count}</div><small>All recorded battle results</small><small>best W${st.bestWin}</small></div></div><div class="statsChartGrid">${winRateOverTimeSvg(windowMatches)}${winLossTrendSvg(windowMatches)}</div><div class="panel" style="margin-top:14px"><div class="between"><h2>Recent Form</h2><span class="pill">${esc(statisticsRangeLabel(range))}</span></div><div class="recentForm">${windowMatches.slice().sort((a,b)=>b.timestamp-a.timestamp).slice(0,10).reverse().map(m=>`<span class="recentDot ${m.result==="win"?"w":"l"}">${m.result==="win"?"W":"L"}</span>`).join("")||`<span class="muted">No matches in this range.</span>`}</div></div><div class="uxOverviewGrid"><div class="panel"><h2>Turn Order</h2><div class="between deckrow"><span>Going First</span><strong>${turn.first.n?turn.first.wr.toFixed(1)+"%":"—"}</strong></div><div class="between deckrow"><span>Going Second</span><strong>${turn.second.n?turn.second.wr.toFixed(1)+"%":"—"}</strong></div><button class="secondary uxInlineAction" onclick="state.battlePrefs.statsTab='coaching';save();statisticsPage()">See what to focus on →</button></div><div class="panel"><h2>Recent Trend</h2><div class="between deckrow"><span>Last 10</span><strong>${tr.last10.n?tr.last10.wr.toFixed(1)+"%":"—"}</strong></div><div class="between deckrow"><span>Last 30 days</span><strong>${tr.d30.n?tr.d30.wr.toFixed(1)+"%":"—"}</strong></div><button class="secondary uxInlineAction" onclick="state.battlePrefs.statsTab='rank';save();statisticsPage()">View rank progress →</button></div></div>`;
 document.getElementById("app").innerHTML=`<div class="between statsPageHeader cohesivePageHeader"><div><span class="eyebrow">PERFORMANCE</span><h1>What should you improve next?</h1><p class="muted">Start with your clearest practice priority, then use the numbers underneath to understand why.</p></div><button onclick="state.page='matches';render()">Record Match</button></div>${tab==='overview'?`<section class="performanceCoachFirst">${actionableCoachingHtml(windowMatches)}</section>`:''}<div class="performanceNavShell">${statisticsRangeControls()}<div class="analyticsTabs cohesiveAnalyticsTabs">${tabs.filter(([k])=>["overview","prep","intelligence","personalmeta"].includes(k)).map(([k,n])=>`<button class="secondary ${tab===k?"active":""}" onclick="state.battlePrefs.statsTab='${k}';save();statisticsPage()">${n}</button>`).join("")}<details class="performanceMore"><summary>More ▾</summary><div>${tabs.filter(([k])=>["coaching","decks","rank"].includes(k)).map(([k,n])=>`<button class="secondary ${tab===k?"active":""}" onclick="state.battlePrefs.statsTab='${k}';save();statisticsPage()">${n}</button>`).join("")}</div></details></div></div>${body}`;
}

function exportBattleJSON(){downloadText("battle-log-v7.json",JSON.stringify({version:7,matches:normalizedMatches(),sessions:state.sessions,rankHistory:state.rankHistory},null,2),"application/json")}
function exportBattleCSV(){
 const rows=[["Date","Result","My Deck","My Archetype","Opponent Archetype","First/Second","Rank Before","Rank After","Rank Change","Game Mode","Session","Tournament","Duration","Notes","Tags"]];
 normalizedMatches().forEach(m=>rows.push([new Date(m.timestamp).toISOString(),m.result,m.deckName,m.deckArchetype,m.opponentArchetype,m.turnOrder,m.rankBefore?.points??"",m.rankAfter?.points??"",m.rankChange,m.gameMode,m.sessionId||"",m.tournament,m.durationMinutes??"",m.notes,(m.tags||[]).join("|")]));
 const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");downloadText("battle-log-v7.csv",csv,"text/csv");
}
function downloadText(name,text,type="text/plain"){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function backupAllData(){downloadText("pokemon-pocket-companion-backup-v8.2.json",JSON.stringify({version:"8.2",exportedAt:Date.now(),state},null,2),"application/json")}
function restoreBackupPrompt(){
 PPCUI.open({eyebrow:"LOCAL BACKUP",title:"Restore a JSON backup",message:"Paste a Pocket Companion backup below. Your current data will be downloaded before replacement.",html:`<label>Backup JSON</label><textarea id="restoreBackupJson" rows="10" placeholder='{"version":"...","state":{...}}'></textarea>`,actions:[{label:"Cancel",className:"secondary",onclick:"PPCUI.close()"},{label:"Review Backup",onclick:"reviewPastedBackup()"}]});
}
function reviewPastedBackup(){
 const raw=document.getElementById("restoreBackupJson")?.value?.trim();if(!raw)return PPCUI.notice("Paste a backup first.",{title:"Backup required",tone:"warning"});
 try{
   const x=JSON.parse(raw);if(!x||!x.state||typeof x.state!=="object")throw new Error("Invalid backup structure");
   window.__pendingLocalBackup=x.state;
   const old=repairStateShape({...x.state}),current=localCloudCounts(),incoming={decks:old.decks.length,matches:old.matches.length,collection:Object.values(old.collection||{}).filter(r=>Number(r?.owned||0)||Number(r?.wanted||0)||Number(r?.tradeable||0)).length};
   PPCUI.open({eyebrow:"LOCAL BACKUP",title:"Replace this browser?",message:"A download of the current browser data will be created first.",html:`<div class="comparisonGrid"><div><span>Current browser</span><strong>${current.decks} decks</strong><small>${current.matches} matches • ${current.collection} collection cards</small></div><div><span>Backup</span><strong>${incoming.decks} decks</strong><small>${incoming.matches} matches • ${incoming.collection} collection cards</small></div></div>`,actions:[{label:"Cancel",className:"secondary",onclick:"PPCUI.close()"},{label:"Restore Backup",className:"danger",onclick:"performPastedBackupRestore()"}]});
 }catch(e){PPCUI.notice(esc(e?.message||String(e)),{title:"Backup could not be read",tone:"danger"})}
}
function performPastedBackupRestore(){
 if(!window.__pendingLocalBackup)return PPCUI.notice("Review the backup again first.",{tone:"warning"});
 backupAllData();makeLocalCloudBackup("Before pasted JSON restore");
 state=repairStateShape(window.__pendingLocalBackup);window.__pendingLocalBackup=null;ensureStableLocalIds();safeStorageSet(STORE,JSON.stringify(state));PPCUI.close();render();requestAnimationFrame(()=>PPCUI.notice("Backup restored successfully.",{title:"Restore complete"}));
}

function battleDiagnosticsHtml(){
 const raw=state.matches||[],norm=raw.map(normalizeMatch).filter(Boolean),legacy=norm.filter(x=>x.legacy).length,withDeck=norm.filter(x=>x.deckId).length,withOpp=norm.filter(x=>x.opponentArchetype&&x.opponentArchetype!=="Unknown").length,rankLinked=state.rankHistory.filter(x=>x.matchId).length;
 return `<div class="panel"><h2>Battle Tracker Diagnostics</h2><div class="debugGrid"><div class="metric"><div class="l">Matches stored</div><div class="n">${raw.length}</div></div><div class="metric"><div class="l">Normalized</div><div class="n">${norm.length}</div></div><div class="metric"><div class="l">Legacy detected</div><div class="n">${legacy}</div></div><div class="metric"><div class="l">Sessions</div><div class="n">${state.sessions.length}</div></div><div class="metric"><div class="l">With deck IDs</div><div class="n">${withDeck}</div></div><div class="metric"><div class="l">Without deck IDs</div><div class="n">${norm.length-withDeck}</div></div><div class="metric"><div class="l">With opponent archetype</div><div class="n">${withOpp}</div></div><div class="metric"><div class="l">Rank-linked</div><div class="n">${rankLinked}</div></div></div><button style="margin-top:12px" onclick="ppcNotice('Battle data check complete. No data was modified.')">Run Battle Data Check</button></div>`;
}

function quickRematch(){
 if(!battleSaveNotice)return;state.battlePrefs.lastDeckId=battleSaveNotice.deckId||state.battlePrefs.lastDeckId;battleDraft.turnOrder=battleSaveNotice.turnOrder||state.battlePrefs.lastTurnOrder||"unknown";const opp=battleSaveNotice.opponentArchetype;battleSaveNotice=null;matches();setTimeout(()=>{chooseRecentOpponent(opp);document.querySelector('.quickRecordPanel')?.scrollIntoView({behavior:'smooth'})},0)
}
function undoLastBattleMatch(){
 const id=battleSaveNotice?.matchId;if(!id)return;
 PPCUI.open({eyebrow:"UNDO MATCH",title:"Remove the match you just recorded?",message:"Only the just-recorded match will be removed. Ranked RP will be rolled back when a linked value is available.",actions:[{label:"Cancel",className:"secondary",onclick:"PPCUI.close()"},{label:"Undo Match",className:"danger",onclick:"PPCUI.close();performUndoLastBattleMatch()"}]});
}
async function performUndoLastBattleMatch(){
 const id=battleSaveNotice?.matchId;if(!id)return;const idx=state.matches.findIndex(m=>String(m.id)===String(id));if(idx<0)return;const m=normalizeMatch(state.matches[idx]);
 if(m.rankSync==="cloud"){
   try{const svc=rankSessionService(),payload=svc?.getData?.(),sid=payload?.session?.id;if(svc&&sid){const out=await svc.undoMatch(sid,m.id);if(!out?.ok)return ppcNotice(rankSessionStatusMessage(out?.status||out?.error));rankSessionApply(svc.getData?.())}}
   catch(e){return ppcNotice("Could not undo the synced RP result: "+(e?.message||String(e)))}
 }else if(m.gameMode==="ranked"&&Number.isFinite(Number(m.rankBefore?.points))){state.rank={...(state.rank||{}),tier:pocketRankTierFromRP(m.rankBefore.points),points:Number(m.rankBefore.points),streak:Number(m.rankStreakBefore||0)}}
 state.matches.splice(idx,1);deleteRankHistoryForMatch(id);battleSaveNotice=null;save();matches();
}
function dismissBattleNotice(){battleSaveNotice=null;matches()}
// V8.21.1 Battle Sessions Cleanup
function rankedBattleSnapshot(){
 const svc=rankSessionService(),payload=svc?.getData?.(),session=payload?.status==="session-active"?payload.session:null;
 const ranked=completedMatches().filter(m=>m.gameMode==="ranked");
 const todayKey=new Date().toDateString(),today=ranked.filter(m=>new Date(m.timestamp).toDateString()===todayKey),todayRecord=wl(today);
 const historyStreak=streakInfo(ranked),currentStreak=Math.max(0,Number(session?.current_win_streak??state.rank?.streak??0)||0);
 const bestStreak=Math.max(currentStreak,Number(session?.best_win_streak??historyStreak.bestWin??0)||0);
 const currentRP=Math.max(0,Number(state.rank?.points??0)||0);
 return {payload,session,ranked,today,todayRecord,currentStreak,bestStreak,currentRP};
}
function battleRankTargetInfo(rp){
 const data=rankBorderService()?.getData?.(),borders=Array.isArray(data?.borders)?data.borders.filter(b=>b.available):[];
 if(!borders.length)return null;
 const wanted=Number(state.rankBorder?.targetRank||10000),target=borders.find(b=>b.targetRank===wanted)||borders.find(b=>b.targetRank===10000)||borders[0];
 if(!target)return null;
 const safe=Number(target.recommendedSafeRP||target.predictedFinalRP||0),pred=Number(target.predictedFinalRP||0);
 return {...target,label:rankBorderLabel(target.targetRank),safe,pred,gap:safe-Number(rp||0)};
}
function battleRankOverviewHtml(){
 const x=rankedBattleSnapshot(),target=battleRankTargetInfo(x.currentRP),signedIn=!!cloudSession?.user;
 const targetHtml=target?`<div class="rankFlowTarget"><div><span>${esc(target.label)} estimated safe target</span><strong>${rankBorderFmt(target.safe)} RP</strong></div><div><span>Your gap</span><strong class="${target.gap<=0?'good':'bad'}">${target.gap<=0?'+':''}${rankBorderFmt(Math.abs(target.gap))}${target.gap<=0?' above':' to go'}</strong></div></div>`:`<div class="rankFlowTarget muted">Rank-border estimate will appear here when enough data is available.</div>`;
 return `<section class="panel battleRankOverview"><div class="between"><div><span class="eyebrow">RANKED PLAY</span><h2>${rankBorderFmt(x.currentRP)} RP</h2><p class="muted">Ranked results automatically update your RP, rank, streak, and progression history.</p></div><div class="row"><span class="pill">AUTO RP</span><button class="secondary" onclick="goPage('rank')">Rank Details →</button></div></div><div class="rankFlowMetrics"><div><span>Ranked Streak</span><strong>W${rankBorderFmt(x.currentStreak)}</strong><small>Best W${rankBorderFmt(x.bestStreak)}</small></div><div><span>Today's Ranked</span><strong>${x.todayRecord.w}-${x.todayRecord.l}</strong><small>${x.todayRecord.n?x.todayRecord.wr.toFixed(0)+'% WR':'No ranked games yet'}</small></div><div><span>RP Tracking</span><strong>Automatic</strong><small>Detailed mode can enter the exact RP shown in-game</small></div><div><span>Current RP</span><strong>${rankBorderFmt(x.currentRP)}</strong><small>Synced progression value</small></div></div>${targetHtml}<div class="notice"><strong>Rank progression:</strong> Ranked wins and losses update RP automatically. If Pokémon TCG Pocket shows a different value, use Detailed mode to enter the exact RP After value.</div></section>`;
}
function battleResultSummaryHtml(n){
 if(!n)return "";
 const ranked=n.gameMode==="ranked"||n.rankSync;
 if(!ranked)return `<div class="battleSaveBanner persistent"><div><strong>Casual match recorded</strong><div>${n.result==="win"?"WIN":"LOSS"} — ${esc(n.deckName)} vs ${esc(n.opponentArchetype)} • No RP change</div></div><div class="row"><button onclick="quickRematch()">Rematch</button><button class="secondary" onclick="undoLastBattleMatch()">Undo</button><button class="secondary" onclick="dismissBattleNotice()">Done</button></div></div>`;
 const after=Number(n.rankAfterPoints),before=Number(n.rankBeforePoints),streak=Number(n.currentStreak||0),hasRP=(n.rankSync==="manual"||n.rankSync==="auto")&&Number.isFinite(before)&&Number.isFinite(after),change=hasRP?after-before:0;
 return `<div class="battleSaveBanner persistent rankResultBanner"><div><strong>${n.result==="win"?'Ranked win recorded':'Ranked loss recorded'}</strong><div class="rankResultLine">${hasRP?`<span class="${change>=0?'good':'bad'}">${change>=0?'+':''}${rankBorderFmt(change)} RP</span><span>${rankBorderFmt(before)} → <b>${rankBorderFmt(after)} RP</b></span>`:`<span>Ranked result saved</span>`}<span>Tracked streak: <b>W${rankBorderFmt(streak)}</b></span></div></div><div class="row"><button onclick="quickRematch()">Rematch</button><button class="secondary" onclick="goPage('rank')">Rank Details</button><button class="secondary" onclick="undoLastBattleMatch()">Undo</button><button class="secondary" onclick="dismissBattleNotice()">Done</button></div></div>`;
}
