/* V8.59.0 Pocket Sync Foundation */
const pocketSyncState={loading:false,loaded:false,capabilities:[],connections:[],runs:[],error:''};
function pocketSyncClient(){return window.getPPCCloudClient?.()||window.cloudClient||null}
function pocketSyncSession(){return window.getPPCCloudSession?.()||window.cloudSession||null}
function pocketSyncSignedIn(){return !!pocketSyncClient()&&!!pocketSyncSession()?.user}
function pocketSyncFallbackCapabilities(){return [
 {source_key:'official_pocket_api',display_name:'Official Pokémon TCG Pocket Sync',source_kind:'official_api',availability:'research',official:true,auth_method:'official_oauth_required',scopes:['collection','rank_history','battle_history'],notes:'Reserved for a verified official third-party authorization/API flow. No passwords, cookies, or reusable game-session tokens are accepted.'},
 {source_key:'companion_backup',display_name:'PocketNexus Backup',source_kind:'companion_backup',availability:'available',official:false,auth_method:'none',scopes:['companion_data'],notes:'Moves PocketNexus data between browsers/devices; this does not read Pokémon TCG Pocket save data.'},
 {source_key:'manual_tracking',display_name:'Manual PocketNexus Tracking',source_kind:'manual',availability:'available',official:false,auth_method:'none',scopes:['collection','rank_history','battle_history'],notes:'Existing manual/local tracking remains available while an official Pocket data source is researched.'}
]}
function pocketSyncStatusLabel(v){return ({available:'Available',research:'Research Gate',unavailable:'Unavailable',ready:'Ready',syncing:'Syncing',error:'Error',paused:'Paused',disconnected:'Not connected'})[v]||String(v||'Unknown')}
function pocketSyncStatusClass(v){return ['available','ready','completed'].includes(v)?'ok':['research','paused','partial'].includes(v)?'warn':['error','failed','unavailable'].includes(v)?'danger':'muted'}
function pocketSyncScopeName(s){return ({collection:'Collection',rank_history:'Rank / RP History',battle_history:'Battle History',companion_data:'Companion Data'})[s]||s.replaceAll('_',' ')}
async function loadPocketSyncState(){
 if(pocketSyncState.loading)return;
 pocketSyncState.loading=true;pocketSyncState.error='';
 try{
  const c=pocketSyncClient();
  if(!c){pocketSyncState.capabilities=pocketSyncFallbackCapabilities();pocketSyncState.connections=[];pocketSyncState.runs=[];return}
  const caps=await c.from('pocket_sync_capabilities').select('*').order('source_key');
  if(caps.error)throw caps.error;
  pocketSyncState.capabilities=caps.data||pocketSyncFallbackCapabilities();
  if(pocketSyncSignedIn()){
   const [connections,runs]=await Promise.all([
    c.from('pocket_sync_connections').select('*').order('updated_at',{ascending:false}),
    c.from('pocket_sync_runs').select('*').order('started_at',{ascending:false}).limit(12)
   ]);
   if(connections.error)throw connections.error;if(runs.error)throw runs.error;
   pocketSyncState.connections=connections.data||[];pocketSyncState.runs=runs.data||[];
  }else{pocketSyncState.connections=[];pocketSyncState.runs=[]}
  pocketSyncState.loaded=true;
 }catch(e){console.warn('Pocket Sync state',e);pocketSyncState.error=e?.message||String(e);pocketSyncState.capabilities=pocketSyncState.capabilities.length?pocketSyncState.capabilities:pocketSyncFallbackCapabilities()}
 finally{pocketSyncState.loading=false}
}
async function refreshPocketSync(){await loadPocketSyncState();pocketSyncPage(false);ppcNotice(pocketSyncState.error?'Pocket Sync status could not fully refresh.':'Pocket Sync status refreshed.')}
function pocketSyncSourceCard(x){
 const conn=pocketSyncState.connections.find(c=>c.source_key===x.source_key);
 const scopes=(x.scopes||[]).map(s=>`<span class="pill">${esc(pocketSyncScopeName(s))}</span>`).join('');
 const primary=x.source_key==='official_pocket_api';
 return `<article class="pocketSyncSource ${primary?'featured':''}"><div class="between"><div><span class="eyebrow">${x.official?'OFFICIAL SOURCE':'SUPPORTED MODE'}</span><h3>${esc(x.display_name)}</h3></div><span class="badge ${pocketSyncStatusClass(x.availability)}">${esc(pocketSyncStatusLabel(x.availability))}</span></div><p class="muted">${esc(x.notes||'')}</p><div class="row wrap">${scopes}</div>${conn?`<div class="pocketSyncConnection"><strong>${esc(pocketSyncStatusLabel(conn.status))}</strong><small>${conn.last_sync_at?`Last sync ${esc(new Date(conn.last_sync_at).toLocaleString())}`:'No completed sync yet'}</small></div>`:''}${primary?`<div class="infoBox"><strong>Connection stays disabled until a verified Pocket authorization/API exists.</strong><br>We will not ask for your Nintendo/Pokémon password, browser cookies, or reusable game-session tokens.</div>`:''}</article>`
}
function pocketSyncRunHtml(r){const counts=r.imported_counts||{};const countText=Object.entries(counts).map(([k,v])=>`${pocketSyncScopeName(k)}: ${v}`).join(' • ')||'No import counts recorded';return `<div class="pocketSyncRun"><span class="badge ${pocketSyncStatusClass(r.status)}">${esc(r.status)}</span><div><strong>${esc(pocketSyncStatusLabel(r.status))}</strong><small>${esc(new Date(r.started_at).toLocaleString())} • ${esc(countText)}</small></div></div>`}
function pocketSyncPage(initial=true){
 const root=document.getElementById('app');if(!root)return;
 const signed=pocketSyncSignedIn();const caps=pocketSyncState.capabilities.length?pocketSyncState.capabilities:pocketSyncFallbackCapabilities();
 root.innerHTML=`<section class="pocketSyncPage"><div class="panel pocketSyncHero"><div><span class="eyebrow">V8.59 • POCKET SYNC</span><h1>One place for Collection, Rank & Battle History</h1><p>The sync architecture is now live. Automatic Pokémon TCG Pocket importing remains behind a research gate until a legitimate read-only source is verified.</p><div class="row wrap"><button onclick="refreshPocketSync()">Refresh Source Status</button><button class="secondary" onclick="goPage('collection')">Open Collection</button><button class="secondary" onclick="goPage('rank')">Open Rank</button><button class="secondary" onclick="state.battlePrefs.experienceMode='standard';save();goPage('matches')">Open Battle Tracker</button></div></div><div class="pocketSyncHeroStatus"><span>Automatic Pocket source</span><strong>Research Gate</strong><small>No private-endpoint credentials accepted</small></div></div>
 <div class="pocketSyncPipeline"><article><span>1</span><strong>Pocket data source</strong><small>Must be official or otherwise legitimate and read-only.</small></article><article><span>2</span><strong>Normalize</strong><small>Map Collection, RP changes and battles into Companion records.</small></article><article><span>3</span><strong>Review</strong><small>Show provenance, imported counts and any conflicts.</small></article><article><span>4</span><strong>Sync</strong><small>Update your existing Collection, Rank and Battle tools.</small></article></div>
 <div class="pocketSyncGrid"><section class="panel"><div class="between"><div><span class="eyebrow">SOURCE READINESS</span><h2>Sync Sources</h2></div><span class="pill">${caps.length} tracked</span></div><div class="pocketSyncSources">${caps.map(pocketSyncSourceCard).join('')}</div></section>
 <section class="panel"><span class="eyebrow">DATA TARGETS</span><h2>What V8.59 is preparing</h2><div class="pocketSyncTargets"><article><strong>◇ Collection</strong><span>Owned quantities mapped to canonical card IDs.</span><small>Protects existing manual edits until conflict rules are finalized.</small></article><article><strong>↗ Rank / RP History</strong><span>Timestamped RP snapshots and ranked result history.</span><small>Designed to feed Rank Intelligence without inventing results.</small></article><article><strong>◉ Battle History</strong><span>Normalized match outcomes ready for Battle Tracker.</span><small>Imported records will keep source/provenance metadata.</small></article></div><div class="infoBox"><strong>Current research result:</strong> Pocket can link save data to Nintendo, Google, or Apple accounts and keeps ranked point Battle History in-game, but we have not verified a public third-party API that exposes Pocket Collection or ranked history.</div></section></div>
 <div class="pocketSyncGrid"><section class="panel"><span class="eyebrow">ACCOUNT</span><h2>${signed?'Cloud sync foundation ready':'Sign in for sync history'}</h2><p class="muted">${signed?'Your Pocket Sync connections and run history are protected by per-user RLS. No credential fields are stored in the new sync tables.':'Guest mode stays available. A Companion account is only needed for cloud-backed connection and sync history.'}</p>${signed?`<div class="row"><span class="badge ok">SIGNED IN</span><span class="pill">${pocketSyncState.connections.length} connections</span></div>`:`<button onclick="goPage('account')">Open Account & Cloud</button>`}</section>
 <section class="panel"><div class="between"><div><span class="eyebrow">SYNC ACTIVITY</span><h2>Recent Runs</h2></div><span class="pill">${pocketSyncState.runs.length}</span></div>${pocketSyncState.error?`<div class="dangerBox">${esc(pocketSyncState.error)}</div>`:''}<div class="pocketSyncRuns">${pocketSyncState.runs.length?pocketSyncState.runs.map(pocketSyncRunHtml).join(''):`<p class="muted">No automatic Pocket sync has run yet. This is expected while the source research gate is active.</p>`}</div></section></div>
 <section class="panel pocketSyncRules"><span class="eyebrow">NON-NEGOTIABLE SYNC RULES</span><h2>Safe by design</h2><div class="pocketSyncRuleGrid"><article><strong>✓ Read-only source</strong><span>Sync should read player data, not automate gameplay.</span></article><article><strong>✓ Explicit consent</strong><span>The player chooses when to connect or disconnect.</span></article><article><strong>✓ No Pocket credentials</strong><span>No Nintendo/Pokémon passwords, cookies or reusable session tokens.</span></article><article><strong>✓ Provenance</strong><span>Every automated import records where and when it came from.</span></article></div></section></section>`;
 if(initial&&!pocketSyncState.loaded&&!pocketSyncState.loading){loadPocketSyncState().then(()=>{if(state.page==='sync')pocketSyncPage(false)})}
}
window.pocketSyncPage=pocketSyncPage;window.refreshPocketSync=refreshPocketSync;

/* V8.59.1 Pocket Sync ingestion + review layer */
const pocketImportState={raw:'',sourceKey:'staged_json',adapterId:'staged_json',adapterDiagnostics:null,preview:null,lastApplied:null};
function pocketImportStableKey(parts){let h=2166136261;for(const ch of parts.join('|')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function pocketImportCardMap(){const m=new Map();(window.CARDS||CARDS||[]).forEach(c=>{m.set(String(c.id),c);const set=String(c.setCode||'').toLowerCase(),num=String(c.number||'').replace(/^0+/,'');if(set&&num)m.set(`${set}:${num}`,c)});return m}
function pocketImportArray(x,...keys){if(Array.isArray(x))return x;for(const k of keys)if(Array.isArray(x?.[k]))return x[k];return []}
function normalizePocketCollectionRecord(r,i,map){const rawId=String(r.card_id??r.cardId??r.id??'').trim(),set=String(r.set_code??r.setCode??r.set??'').trim().toLowerCase(),num=String(r.number??r.card_number??'').trim().replace(/^0+/,'');const card=map.get(rawId)||map.get(`${set}:${num}`);if(!card)return {domain:'collection',status:'invalid',sourceKey:rawId||`${set}:${num}`||`row-${i}`,reason:'Card could not be mapped to the canonical cards.json ID.'};const owned=Math.max(0,Math.floor(Number(r.owned_quantity??r.owned??r.quantity??r.count??0)||0));return {domain:'collection',status:'ready',sourceKey:rawId||`${set}:${num}`||String(card.id),key:String(card.id),payload:{cardId:String(card.id),owned,wanted:Math.max(0,Math.floor(Number(r.wanted_quantity??r.wanted??0)||0)),tradeable:Math.min(owned,Math.max(0,Math.floor(Number(r.trade_quantity??r.tradeable??0)||0)))},provenance:{sourceCardId:rawId||null,setCode:set||null,number:num||null}}}
function normalizePocketRankRecord(r,i){const ts=normalizeTimestampValue?.(r.timestamp,r.played_at,r.date,r.created_at)||Date.now(),points=Number(r.points??r.rp??r.rank_points??r.rankPoints);if(!Number.isFinite(points))return {domain:'rank_history',status:'invalid',sourceKey:String(r.id??`row-${i}`),reason:'Rank record is missing a numeric RP/points value.'};const result=typeof normalizeResultValue==='function'?normalizeResultValue(r.result):String(r.result||'').toLowerCase();const key=String(r.id||`sync-rank-${pocketImportStableKey([ts,points,result])}`);return {domain:'rank_history',status:'ready',sourceKey:String(r.id??key),key,payload:{id:key,timestamp:ts,tier:String(r.tier??r.rank??''),points,result,change:Number(r.change??r.rp_change??0)||0,source:'pocket_sync'}}}
function normalizePocketBattleRecord(r,i){const ts=normalizeTimestampValue?.(r.timestamp,r.played_at,r.date,r.created_at)||Date.now(),result=typeof normalizeResultValue==='function'?normalizeResultValue(r.result):String(r.result||'').toLowerCase();if(!['win','loss','tie'].includes(result))return {domain:'battle_history',status:'invalid',sourceKey:String(r.id??`row-${i}`),reason:'Battle result must normalize to win, loss, or tie.'};const sourceId=String(r.id??r.match_id??''),key=sourceId||`sync-match-${pocketImportStableKey([ts,result,r.opponent??r.opponentArchetype??'',r.deck??r.deckName??''])}`;const payload={id:key,timestamp:ts,deckId:String(r.deck_id??r.deckId??''),deckName:String(r.deck_name??r.deckName??r.deck??'Imported Pocket Deck'),deckArchetype:String(r.deck_archetype??r.deckArchetype??''),opponentArchetype:String(r.opponent_archetype??r.opponentArchetype??r.opponent??'Unknown'),opponentName:String(r.opponent_name??r.opponentName??''),result,turnOrder:String(r.turn_order??r.turnOrder??'unknown'),gameMode:String(r.game_mode??r.gameMode??'ranked'),rankBefore:r.rank_before??r.rankBefore??{tier:'',points:null},rankAfter:r.rank_after??r.rankAfter??{tier:'',points:null},rankChange:Number(r.rank_change??r.rankChange??0)||0,sessionId:null,tournament:'',durationMinutes:null,notes:String(r.notes??''),tags:['pocket-sync'],source:'pocket_sync',sourceRecordId:sourceId||null};return {domain:'battle_history',status:'ready',sourceKey:sourceId||key,key,payload}}
function classifyPocketImportItem(item,seen){if(item.status==='invalid')return item;const sk=`${item.domain}:${item.key}`;if(seen.has(sk))return {...item,status:'duplicate',reason:'Duplicate record inside this import batch.'};seen.add(sk);if(item.domain==='collection'){const old=state.collection?.[item.key];if(old&&Number(old.owned||0)!==Number(item.payload.owned||0))return {...item,status:'conflict',reason:`Existing owned quantity is ${Number(old.owned||0)}; import says ${Number(item.payload.owned||0)}.`,existing:{...old}}}if(item.domain==='rank_history'){const old=(state.rankHistory||[]).find(x=>String(x.id)===item.key);if(old)return {...item,status:'duplicate',reason:'Rank record ID already exists.',existing:old}}if(item.domain==='battle_history'){const old=(state.matches||[]).find(x=>String(x.id)===item.key);if(old)return {...item,status:'duplicate',reason:'Battle record ID already exists.',existing:old}}return item}
function normalizePocketImport(raw){const source=raw?.domains&&typeof raw.domains==='object'?raw.domains:raw;const map=pocketImportCardMap(),seen=new Set(),items=[];pocketImportArray(source,'collection','cards','owned_cards').forEach((r,i)=>items.push(classifyPocketImportItem(normalizePocketCollectionRecord(r,i,map),seen)));pocketImportArray(source?.rank_history,'records','rankHistory').forEach((r,i)=>items.push(classifyPocketImportItem(normalizePocketRankRecord(r,i),seen)));pocketImportArray(source?.battle_history,'matches','battles','battleHistory').forEach((r,i)=>items.push(classifyPocketImportItem(normalizePocketBattleRecord(r,i),seen)));if(source&&typeof source==='object'){if(Array.isArray(source.rankHistory))source.rankHistory.forEach((r,i)=>items.push(classifyPocketImportItem(normalizePocketRankRecord(r,i),seen)));if(Array.isArray(source.matches))source.matches.forEach((r,i)=>items.push(classifyPocketImportItem(normalizePocketBattleRecord(r,i),seen)))}const counts={};items.forEach(x=>counts[x.status]=(counts[x.status]||0)+1);return {items,counts,total:items.length}}
async function previewPocketImport(){const ta=document.getElementById('pocketImportJson');const select=document.getElementById('pocketAdapterSelect');try{const adapterId=select?.value||pocketImportState.adapterId||'staged_json';pocketImportState.adapterId=adapterId;pocketImportState.raw=ta?.value||'';const svc=window.PPCPocketSyncAdapters;if(!svc)throw new Error('Pocket Sync Adapter Framework did not load.');const result=await svc.run(adapterId,{input:pocketImportState.raw,session:pocketSyncSession()});pocketImportState.adapterDiagnostics=result.diagnostics;pocketImportState.sourceKey=result.envelope?.source?.key||adapterId;pocketImportState.preview=normalizePocketImport(result.envelope);pocketSyncPage(false)}catch(e){console.warn('Pocket adapter preview',e);pocketImportState.preview=null;pocketImportState.adapterDiagnostics=null;ppcNotice(e?.message||'Adapter could not preview this payload.')}}
function pocketImportRowsHtml(){const p=pocketImportState.preview;if(!p)return '<p class="muted">No staged data yet. Paste a supported JSON payload and choose Preview Import.</p>';return `<div class="pocketImportSummary"><span class="badge ok">${p.counts.ready||0} READY</span><span class="badge warn">${p.counts.conflict||0} CONFLICTS</span><span class="badge">${p.counts.duplicate||0} DUPLICATES</span><span class="badge danger">${p.counts.invalid||0} INVALID</span></div><div class="pocketImportRows">${p.items.slice(0,40).map(x=>`<article><span class="badge ${pocketSyncStatusClass(x.status)}">${esc(x.status)}</span><div><strong>${esc(pocketSyncScopeName(x.domain))} • ${esc(x.key||x.sourceKey)}</strong><small>${esc(x.reason||'Normalized and ready to merge.')}</small></div></article>`).join('')}</div>${p.items.length>40?`<p class="muted">Showing first 40 of ${p.items.length} records.</p>`:''}`}
async function recordPocketImportBatch(preview,applied){if(!pocketSyncSignedIn())return;const c=pocketSyncClient(),uid=pocketSyncSession()?.user?.id;if(!c||!uid)return;const fp=pocketImportStableKey([pocketImportState.sourceKey,pocketImportState.raw]);const received={total:preview.total},normalized={ready:preview.counts.ready||0,duplicate:preview.counts.duplicate||0,invalid:preview.counts.invalid||0},conflicts={collection:preview.items.filter(x=>x.status==='conflict'&&x.domain==='collection').length,rank_history:preview.items.filter(x=>x.status==='conflict'&&x.domain==='rank_history').length,battle_history:preview.items.filter(x=>x.status==='conflict'&&x.domain==='battle_history').length};const batch=await c.from('pocket_sync_import_batches').upsert({user_id:uid,source_key:pocketImportState.sourceKey,status:'applied',source_label:'Pocket Sync staged import',source_fingerprint:fp,received_counts:received,normalized_counts:normalized,conflict_counts:conflicts,applied_counts:applied,reviewed_at:new Date().toISOString(),applied_at:new Date().toISOString()},{onConflict:'user_id,source_fingerprint'}).select('id').single();if(batch.error){console.warn('Pocket import batch',batch.error);return}const rows=preview.items.slice(0,1000).map(x=>({batch_id:batch.data.id,user_id:uid,domain:x.domain,source_record_key:String(x.sourceKey),normalized_key:String(x.key||x.sourceKey),status:x.status==='ready'?'applied':x.status,normalized_payload:x.payload||{},existing_snapshot:x.existing||null,conflict_reason:x.reason||null,provenance:x.provenance||{},applied_at:x.status==='ready'?new Date().toISOString():null}));if(rows.length){const res=await c.from('pocket_sync_import_items').upsert(rows,{onConflict:'batch_id,domain,source_record_key'});if(res.error)console.warn('Pocket import items',res.error)}}
async function applyPocketImport(){const p=pocketImportState.preview;if(!p){ppcNotice('Preview an import first.');return}const ready=p.items.filter(x=>x.status==='ready'),applied={collection:0,rank_history:0,battle_history:0};for(const x of ready){if(x.domain==='collection'){state.collection[x.key]={owned:x.payload.owned,wanted:x.payload.wanted,tradeable:x.payload.tradeable};applied.collection++}else if(x.domain==='rank_history'){state.rankHistory.push(x.payload);applied.rank_history++}else if(x.domain==='battle_history'){state.matches.push(x.payload);applied.battle_history++}}save();await recordPocketImportBatch(p,applied);pocketImportState.lastApplied=applied;pocketImportState.preview=null;pocketImportState.raw='';await loadPocketSyncState();pocketSyncPage(false);ppcNotice(`Pocket import applied: ${applied.collection} collection • ${applied.rank_history} rank • ${applied.battle_history} battles.`)}

/* V8.59.3 Automatic Sync Orchestrator bridge */
const pocketOrchestratorState={schedules:[],loading:false,error:'',lastRun:null};
async function recordPocketImportBatchWithContext(preview,applied,ctx={}){
 if(!pocketSyncSignedIn())return null;
 const c=pocketSyncClient(),uid=pocketSyncSession()?.user?.id;if(!c||!uid)return null;
 const sourceKey=ctx.sourceKey||pocketImportState.sourceKey||'unknown';
 const fp=pocketImportStableKey([sourceKey,ctx.rawFingerprintInput??pocketImportState.raw??preview]);
 const received={total:preview.total},normalized={ready:preview.counts.ready||0,duplicate:preview.counts.duplicate||0,invalid:preview.counts.invalid||0};
 const conflicts={collection:preview.items.filter(x=>x.status==='conflict'&&x.domain==='collection').length,rank_history:preview.items.filter(x=>x.status==='conflict'&&x.domain==='rank_history').length,battle_history:preview.items.filter(x=>x.status==='conflict'&&x.domain==='battle_history').length};
 const batch=await c.from('pocket_sync_import_batches').upsert({user_id:uid,source_key:sourceKey,status:ctx.status||'applied',source_label:ctx.sourceLabel||'Pocket Sync automatic import',source_fingerprint:fp,received_counts:received,normalized_counts:normalized,conflict_counts:conflicts,applied_counts:applied||{},reviewed_at:new Date().toISOString(),applied_at:ctx.status==='staged'?null:new Date().toISOString()},{onConflict:'user_id,source_fingerprint'}).select('id').single();
 if(batch.error){console.warn('Pocket import batch',batch.error);return null}
 const rows=preview.items.slice(0,1000).map(x=>({batch_id:batch.data.id,user_id:uid,domain:x.domain,source_record_key:String(x.sourceKey),normalized_key:String(x.key||x.sourceKey),status:x.status==='ready'&&ctx.status!=='staged'?'applied':x.status,normalized_payload:x.payload||{},existing_snapshot:x.existing||null,conflict_reason:x.reason||null,provenance:{...(x.provenance||{}),trigger_kind:ctx.triggerKind||'manual'},applied_at:x.status==='ready'&&ctx.status!=='staged'?new Date().toISOString():null}));
 if(rows.length){const res=await c.from('pocket_sync_import_items').upsert(rows,{onConflict:'batch_id,domain,source_record_key'});if(res.error)console.warn('Pocket import items',res.error)}
 return batch.data.id;
}
async function processPocketSyncEnvelope(envelope,options={}){
 const preview=normalizePocketImport(envelope),applied={collection:0,rank_history:0,battle_history:0};
 if(options.autoApplyReady!==false){
  for(const x of preview.items.filter(x=>x.status==='ready')){
   if(x.domain==='collection'){state.collection[x.key]={owned:x.payload.owned,wanted:x.payload.wanted,tradeable:x.payload.tradeable};applied.collection++}
   else if(x.domain==='rank_history'){state.rankHistory.push(x.payload);applied.rank_history++}
   else if(x.domain==='battle_history'){state.matches.push(x.payload);applied.battle_history++}
  }
  if(applied.collection||applied.rank_history||applied.battle_history)save();
 }
 if(options.recordBatch!==false)await recordPocketImportBatchWithContext(preview,applied,{...options,status:options.autoApplyReady===false?'staged':'applied'});
 return {preview,applied};
}
window.processPocketSyncEnvelope=processPocketSyncEnvelope;
async function loadPocketOrchestratorState(){
 const svc=window.PPCPocketSyncOrchestrator;if(!svc||!pocketSyncSignedIn()){pocketOrchestratorState.schedules=[];return}
 pocketOrchestratorState.loading=true;pocketOrchestratorState.error='';
 try{pocketOrchestratorState.schedules=await svc.listSchedules()}catch(e){pocketOrchestratorState.error=e?.message||String(e)}finally{pocketOrchestratorState.loading=false}
}
function pocketOrchestratorSchedule(adapterId){return pocketOrchestratorState.schedules.find(x=>x.adapter_id===adapterId)||null}
async function runPocketAdapterNow(adapterId){
 const svc=window.PPCPocketSyncOrchestrator;if(!svc){ppcNotice('Automatic Sync Orchestrator did not load.');return}
 try{ppcNotice('Pocket Sync started…');const out=await svc.run(adapterId,{triggerKind:'manual',autoApplyReady:true,input:{}});pocketOrchestratorState.lastRun={adapterId,ok:true,attempts:out.attempts,at:Date.now()};await Promise.all([loadPocketOrchestratorState(),loadPocketSyncState()]);pocketSyncPage(false);ppcNotice(`Automatic sync completed in ${out.attempts} attempt${out.attempts===1?'':'s'}.`)}catch(e){pocketOrchestratorState.lastRun={adapterId,ok:false,error:e?.message||String(e),at:Date.now()};await Promise.all([loadPocketOrchestratorState(),loadPocketSyncState()]);pocketSyncPage(false);ppcNotice(e?.message||'Automatic sync failed.')}
}
async function savePocketSchedule(adapterId){
 if(!pocketSyncSignedIn()){ppcNotice('Sign in to save automatic sync settings.');return}
 const enabled=!!document.getElementById(`orchEnabled-${adapterId}`)?.checked;
 const cadence=Number(document.getElementById(`orchCadence-${adapterId}`)?.value||60);
 const retryLimit=Number(document.getElementById(`orchRetry-${adapterId}`)?.value||2);
 const autoApply=!!document.getElementById(`orchApply-${adapterId}`)?.checked;
 try{await window.PPCPocketSyncOrchestrator.saveSchedule(adapterId,{enabled,cadenceMinutes:cadence,retryLimit,autoApplyReady:autoApply});await loadPocketOrchestratorState();pocketSyncPage(false);ppcNotice(enabled?'Automatic sync schedule saved.':'Automatic sync paused.')}catch(e){ppcNotice(e?.message||'Could not save sync schedule.')}
}
function pocketOrchestratorPanelHtml(){
 const svc=window.PPCPocketSyncOrchestrator,adapters=window.PPCPocketSyncAdapters?.list?.().filter(a=>a.availability==='available')||[];
 return `<section class="panel pocketOrchestrator"><div class="between"><div><span class="eyebrow">V8.59.3 • AUTOMATIC SYNC ORCHESTRATOR</span><h2>Run → Retry → Record → Ingest</h2></div><span class="badge ${svc?'ok':'danger'}">${svc?'READY':'NOT LOADED'}</span></div><p class="muted">The orchestrator can trigger any available read-only adapter, retry transient failures, record each cloud-backed run, and automatically send successful output through the V8.59.1 ingestion layer. Conflicts remain staged instead of being overwritten.</p>${!pocketSyncSignedIn()?'<div class="infoBox"><strong>Guest mode:</strong> manual adapter runs still work, but saved schedules and cloud run history require a Companion account.</div>':''}<div class="pocketOrchestratorGrid">${adapters.map(a=>{const sc=pocketOrchestratorSchedule(a.id);return `<article class="pocketOrchestratorCard"><div class="between"><strong>${esc(a.label)}</strong><span class="badge ${sc?.enabled?'ok':'muted'}">${sc?.enabled?'AUTO ON':'AUTO OFF'}</span></div><small>${esc(a.description||'')}</small><div class="row wrap"><button onclick="runPocketAdapterNow('${esc(a.id)}')" ${svc?.isRunning?.(a.id)?'disabled':''}>Run Now</button>${pocketSyncSignedIn()?`<label class="check"><input id="orchEnabled-${esc(a.id)}" type="checkbox" ${sc?.enabled?'checked':''}> Automatic</label><label>Every<select id="orchCadence-${esc(a.id)}"><option value="15" ${Number(sc?.cadence_minutes)===15?'selected':''}>15 min</option><option value="60" ${!sc||Number(sc?.cadence_minutes)===60?'selected':''}>1 hour</option><option value="360" ${Number(sc?.cadence_minutes)===360?'selected':''}>6 hours</option><option value="1440" ${Number(sc?.cadence_minutes)===1440?'selected':''}>24 hours</option></select></label><label>Retries<select id="orchRetry-${esc(a.id)}"><option value="0" ${Number(sc?.retry_limit)===0?'selected':''}>0</option><option value="1" ${Number(sc?.retry_limit)===1?'selected':''}>1</option><option value="2" ${!sc||Number(sc?.retry_limit)===2?'selected':''}>2</option><option value="3" ${Number(sc?.retry_limit)===3?'selected':''}>3</option></select></label><label class="check"><input id="orchApply-${esc(a.id)}" type="checkbox" ${sc?.auto_apply_ready!==false?'checked':''}> Auto-apply ready records</label><button class="secondary" onclick="savePocketSchedule('${esc(a.id)}')">Save</button>`:''}</div>${sc?`<div class="row wrap"><span class="pill">Last ${esc(sc.last_status||'never')}</span><span class="pill">Next ${sc.next_due_at?new Date(sc.next_due_at).toLocaleString():'paused'}</span>${sc.last_error?`<span class="badge danger">${esc(sc.last_error)}</span>`:''}</div>`:''}</article>`}).join('')}</div><div class="infoBox"><strong>Scheduling note:</strong> V8.59.3 browser schedules run while PocketNexus is open. The same schedule records are cloud-backed so a future approved server-side source can use them without changing the adapter or ingestion contract.</div></section>`
}

function pocketAdapterCardsHtml(){const svc=window.PPCPocketSyncAdapters,rows=svc?.list?.()||[];return `<div class="pocketAdapterGrid">${rows.map(a=>`<article class="pocketAdapterCard"><div class="between"><strong>${esc(a.label)}</strong><span class="badge ${pocketSyncStatusClass(a.availability)}">${esc(pocketSyncStatusLabel(a.availability))}</span></div><small>${esc(a.description||'')}</small><div class="row wrap"><span class="pill">${esc(a.id)}</span><span class="pill">v${esc(a.version)}</span><span class="pill">READ-ONLY</span>${a.official?'<span class="pill">OFFICIAL SLOT</span>':''}</div><div class="row wrap">${(a.scopes||[]).map(x=>`<span class="pill">${esc(pocketSyncScopeName(x))}</span>`).join('')}</div></article>`).join('')}</div>`}
function pocketAdapterSelectHtml(){const rows=window.PPCPocketSyncAdapters?.list?.()||[];return `<label class="pocketAdapterSelectLabel">Adapter<select id="pocketAdapterSelect">${rows.map(a=>`<option value="${esc(a.id)}" ${a.id===pocketImportState.adapterId?'selected':''} ${a.availability!=='available'?'disabled':''}>${esc(a.label)}${a.availability!=='available'?` — ${esc(pocketSyncStatusLabel(a.availability))}`:''}</option>`).join('')}</select></label>`}
function pocketAdapterDiagnosticsHtml(){const d=pocketImportState.adapterDiagnostics;if(!d)return '<p class="muted">Run a preview to see adapter diagnostics.</p>';return `<div class="pocketAdapterDiagnostics"><span class="badge ok">CONTRACT ${esc(d.schema_version)}</span><span class="pill">${esc(d.adapter_id)}</span><span class="pill">${Number(d.duration_ms)||0} ms</span><span class="pill">Collection ${Number(d.counts?.collection)||0}</span><span class="pill">Rank ${Number(d.counts?.rank_history)||0}</span><span class="pill">Battles ${Number(d.counts?.battle_history)||0}</span></div>`}
function pocketAdapterFrameworkPanelHtml(){return `<section class="panel pocketAdapters"><div class="between"><div><span class="eyebrow">V8.59.2 • SYNC ADAPTER FRAMEWORK</span><h2>One contract for every legitimate source</h2></div><span class="pill">SCHEMA ${esc(window.PPCPocketSyncAdapters?.schemaVersion||'1.0')}</span></div><p class="muted">Adapters are isolated from Collection, Rank, and Battle Tracker. A source only needs to produce the standard read-only envelope; the V8.59.1 ingestion layer handles normalization, duplicate detection, conflict review, and merge.</p>${pocketAdapterCardsHtml()}<div class="infoBox"><strong>Adapter boundary:</strong> adapters may identify source, scopes, provenance, and records. The framework rejects password, cookie, reusable session-token, client-secret, and service-role fields. The official Pocket adapter remains disabled behind the research gate.</div></section>`}
function pocketIngestionPanelHtml(){return `<section class="panel pocketIngestion"><div class="between"><div><span class="eyebrow">V8.59.1 • INGESTION LAYER</span><h2>Adapter → Normalize → Deduplicate → Review → Merge</h2></div><span class="pill">SOURCE-AGNOSTIC</span></div><p class="muted">V8.59.2 now routes staged data through the same adapter contract a future legitimate source will use.</p>${pocketAdapterSelectHtml()}<textarea id="pocketImportJson" rows="8" spellcheck="false" placeholder='{"collection":[{"card_id":"...","owned":2}],"rank_history":[{"timestamp":"2026-09-03T12:00:00Z","rp":1200}],"battle_history":[{"timestamp":"2026-09-03T12:10:00Z","result":"win"}]}' >${pocketImportState.raw?esc(pocketImportState.raw):''}</textarea><div class="row wrap"><button onclick="previewPocketImport()">Run Adapter + Preview</button>${pocketImportState.preview?'<button onclick="applyPocketImport()">Apply Ready Records</button>':''}<button class="secondary" onclick="document.getElementById('pocketImportJson').value='';pocketImportState.preview=null;pocketImportState.adapterDiagnostics=null;pocketSyncPage(false)">Clear</button></div>${pocketAdapterDiagnosticsHtml()}${pocketImportRowsHtml()}<div class="infoBox"><strong>Conflict rule:</strong> existing Collection quantities are never silently overwritten when they disagree. Conflicts stay staged for review. Duplicate Rank/Battle IDs are skipped. Every cloud-backed batch stores provenance and counts, not account credentials.</div></section>`}
const pocketSyncPageV8590=pocketSyncPage;
pocketSyncPage=function(initial=true){pocketSyncPageV8590(initial);const root=document.querySelector('.pocketSyncPage');if(root)root.insertAdjacentHTML('beforeend',pocketOrchestratorPanelHtml()+pocketAdapterFrameworkPanelHtml()+pocketIngestionPanelHtml());if(initial&&!pocketSyncState.loaded)loadPocketSyncState().then(()=>pocketSyncPage(false));if(initial&&pocketSyncSignedIn())loadPocketOrchestratorState().then(()=>pocketSyncPage(false))}

/* V8.59.4 Sync Conflict Resolution + Audit Trail */
const pocketConflictState={loading:false,error:'',items:[],audit:[]};
function pocketConflictCurrentSnapshot(item){
 const k=String(item.normalized_key||'');
 if(item.domain==='collection')return state.collection?.[k]?{...state.collection[k]}:null;
 if(item.domain==='rank_history')return (state.rankHistory||[]).find(x=>String(x.id)===k)||null;
 if(item.domain==='battle_history')return (state.matches||[]).find(x=>String(x.id)===k)||null;
 return null;
}
function pocketApplyResolvedPayload(item){
 const k=String(item.normalized_key||''),p=item.normalized_payload||{};
 if(item.domain==='collection'){state.collection=state.collection||{};state.collection[k]={owned:Number(p.owned||0),wanted:Number(p.wanted||0),tradeable:Number(p.tradeable||0)};return state.collection[k]}
 if(item.domain==='rank_history'){
  state.rankHistory=state.rankHistory||[];const i=state.rankHistory.findIndex(x=>String(x.id)===k);if(i>=0)state.rankHistory[i]=p;else state.rankHistory.push(p);return p
 }
 if(item.domain==='battle_history'){
  state.matches=state.matches||[];const i=state.matches.findIndex(x=>String(x.id)===k);if(i>=0)state.matches[i]=p;else state.matches.push(p);return p
 }
 return null;
}
async function loadPocketConflictState(){
 if(!pocketSyncSignedIn()){pocketConflictState.items=[];pocketConflictState.audit=[];pocketConflictState.error='';return}
 if(pocketConflictState.loading)return;pocketConflictState.loading=true;pocketConflictState.error='';
 try{
  const c=pocketSyncClient();
  const [conflicts,audit]=await Promise.all([
   c.from('pocket_sync_import_items').select('id,batch_id,domain,normalized_key,status,normalized_payload,existing_snapshot,conflict_reason,provenance,created_at,resolution,resolved_at').eq('status','conflict').is('resolution',null).order('created_at',{ascending:false}).limit(100),
   c.from('pocket_sync_audit_events').select('id,batch_id,item_id,domain,normalized_key,action,before_snapshot,incoming_snapshot,after_snapshot,source_key,metadata,created_at').order('created_at',{ascending:false}).limit(100)
  ]);
  if(conflicts.error)throw conflicts.error;if(audit.error)throw audit.error;
  pocketConflictState.items=conflicts.data||[];pocketConflictState.audit=audit.data||[];
 }catch(e){pocketConflictState.error=e?.message||String(e)}finally{pocketConflictState.loading=false}
}
async function pocketAuditInsert(row){
 if(!pocketSyncSignedIn())return;const c=pocketSyncClient(),uid=pocketSyncSession()?.user?.id;if(!c||!uid)return;
 const res=await c.from('pocket_sync_audit_events').insert({user_id:uid,...row});if(res.error)console.warn('Pocket Sync audit',res.error)
}
async function resolvePocketSyncConflict(itemId,choice){
 if(!pocketSyncSignedIn()){ppcNotice('Sign in to resolve cloud sync conflicts.');return}
 const item=pocketConflictState.items.find(x=>x.id===itemId);if(!item)return;
 if(!['accept_incoming','keep_existing'].includes(choice))return;
 try{
  const before=pocketConflictCurrentSnapshot(item)??item.existing_snapshot??null;
  let after=before;
  if(choice==='accept_incoming'){after=pocketApplyResolvedPayload(item);save()}
  const now=new Date().toISOString(),uid=pocketSyncSession().user.id,c=pocketSyncClient();
  const upd=await c.from('pocket_sync_import_items').update({status:'resolved',resolution:choice,resolved_at:now,resolved_by:uid,applied_at:choice==='accept_incoming'?now:null}).eq('id',item.id);
  if(upd.error)throw upd.error;
  await pocketAuditInsert({batch_id:item.batch_id,item_id:item.id,domain:item.domain,normalized_key:item.normalized_key,action:choice,before_snapshot:before,incoming_snapshot:item.normalized_payload||{},after_snapshot:after,source_key:item.provenance?.source_key||null,metadata:{resolution:true,conflict_reason:item.conflict_reason||null}});
  await loadPocketConflictState();pocketSyncPage(false);ppcNotice(choice==='accept_incoming'?'Incoming sync data accepted.':'Existing Companion data kept.');
 }catch(e){ppcNotice(e?.message||'Could not resolve sync conflict.')}
}
function pocketJsonPreview(x){if(x==null)return '—';try{const s=JSON.stringify(x);return s.length>180?s.slice(0,177)+'…':s}catch{return String(x)}}
function pocketConflictPanelHtml(){
 if(!pocketSyncSignedIn())return `<section class="panel pocketConflictCenter"><div class="between"><div><span class="eyebrow">V8.59.4 • CONFLICT CENTER</span><h2>Review before overwrite</h2></div><span class="badge muted">SIGN IN REQUIRED</span></div><p class="muted">Cloud-backed conflict resolution and audit history are available after signing in. Guest imports still keep conflicting records staged instead of overwriting them.</p></section>`;
 const rows=pocketConflictState.items;
 return `<section class="panel pocketConflictCenter"><div class="between"><div><span class="eyebrow">V8.59.4 • CONFLICT CENTER</span><h2>Resolve incoming vs existing data</h2></div><span class="badge ${rows.length?'warn':'ok'}">${rows.length} OPEN</span></div><p class="muted">Every disagreement stays blocked until you choose which version wins. Nothing here is resolved automatically.</p>${pocketConflictState.error?`<div class="dangerBox">${esc(pocketConflictState.error)}</div>`:''}<div class="pocketConflictList">${rows.length?rows.map(x=>`<article class="pocketConflictCard"><div class="between"><div><span class="badge warn">CONFLICT</span> <strong>${esc(pocketSyncScopeName(x.domain))} • ${esc(x.normalized_key)}</strong></div><small>${esc(new Date(x.created_at).toLocaleString())}</small></div><p>${esc(x.conflict_reason||'Incoming data differs from existing Companion data.')}</p><div class="pocketConflictCompare"><div><span>Existing</span><code>${esc(pocketJsonPreview(x.existing_snapshot))}</code></div><div><span>Incoming</span><code>${esc(pocketJsonPreview(x.normalized_payload))}</code></div></div><div class="row wrap"><button onclick="resolvePocketSyncConflict('${x.id}','accept_incoming')">Accept Incoming</button><button class="secondary" onclick="resolvePocketSyncConflict('${x.id}','keep_existing')">Keep Existing</button></div></article>`).join(''):'<div class="infoBox"><strong>No unresolved conflicts.</strong> Incoming records that agree or are new can continue through the normal ingestion flow.</div>'}</div></section>`
}
function pocketAuditPanelHtml(){
 const rows=pocketConflictState.audit;
 return `<section class="panel pocketAuditTrail"><div class="between"><div><span class="eyebrow">SYNC AUDIT TRAIL</span><h2>What changed, when, and why</h2></div><span class="pill">${rows.length} recent events</span></div><p class="muted">Audit entries record the before state, incoming value, resulting state, source, and resolution action. They never store Nintendo/Pokémon passwords, cookies, or reusable session credentials.</p><div class="pocketAuditRows">${rows.length?rows.map(x=>`<article><div class="between"><div><span class="badge ${x.action==='accept_incoming'?'ok':x.action==='keep_existing'?'muted':'ok'}">${esc(String(x.action||'changed').replaceAll('_',' ').toUpperCase())}</span> <strong>${esc(pocketSyncScopeName(x.domain||'record'))} • ${esc(x.normalized_key||'')}</strong></div><small>${esc(new Date(x.created_at).toLocaleString())}</small></div><div class="pocketAuditSnapshots"><span><b>Before</b> ${esc(pocketJsonPreview(x.before_snapshot))}</span><span><b>Incoming</b> ${esc(pocketJsonPreview(x.incoming_snapshot))}</span><span><b>After</b> ${esc(pocketJsonPreview(x.after_snapshot))}</span></div></article>`).join(''):'<p class="muted">No audit events yet. Future accepted sync changes and conflict decisions will appear here.</p>'}</div></section>`
}
window.resolvePocketSyncConflict=resolvePocketSyncConflict;

const pocketSyncPageV8593=pocketSyncPage;
pocketSyncPage=function(initial=true){
 pocketSyncPageV8593(initial);
 const root=document.querySelector('.pocketSyncPage');if(root)root.insertAdjacentHTML('beforeend',pocketConflictPanelHtml()+pocketAuditPanelHtml());
 if(initial&&pocketSyncSignedIn())loadPocketConflictState().then(()=>pocketSyncPage(false));
};
window.pocketSyncPage=pocketSyncPage;
