/* V8.61.5 — Daily Challenges + Training Streaks + Profile Showcase */
const WTC_STORE='ppc_whats_this_card_v8610';
function wtcDateKey(){return new Date().toISOString().slice(0,10)}
function wtcHash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function wtcRead(){try{return JSON.parse(localStorage.getItem(WTC_STORE)||'{}')||{}}catch{return {}}}
function wtcWrite(v){try{localStorage.setItem(WTC_STORE,JSON.stringify(v))}catch(e){console.warn('Daily card stats could not be saved',e)}}
function wtcEligibleCards(){const seen=new Set();return (CARDS||[]).filter(c=>{const img=c?.fullImageUrl||c?.thumbnailUrl||c?.image||'';const name=String(c?.name||'').trim();if(!img||!name||String(c.id||'').startsWith('fallback-'))return false;const key=name.toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>String(a.id).localeCompare(String(b.id)))}
function wtcDailyCard(){const pool=wtcEligibleCards();if(!pool.length)return null;return pool[wtcHash('PocketCompanion|'+wtcDateKey())%pool.length]}
function wtcGame(){const db=wtcRead(),day=wtcDateKey();db.days=db.days||{};db.days[day]=db.days[day]||{guesses:[],solved:false,failed:false,completed:false,stars:0};return {db,day,game:db.days[day]}}
function wtcSave(ctx){ctx.db.days[ctx.day]=ctx.game;wtcWrite(ctx.db)}
function wtcAttempt(){const {game}=wtcGame();return Math.min(5,game.guesses.length+1)}
function wtcZoomForAttempt(n){return [3.9,3.1,2.5,2.0,1.55][Math.max(0,Math.min(4,n-1))]}
function wtcStats(){const db=wtcRead(),days=Object.entries(db.days||{}).filter(([,g])=>g.completed).sort(([a],[b])=>a.localeCompare(b));let solved=0,totalGuess=0,best=0,current=0,run=0,last='';for(const [d,g] of days){if(g.solved){solved++;totalGuess+=g.guesses?.length||0;if(last){const next=new Date(last+'T00:00:00Z');next.setUTCDate(next.getUTCDate()+1);run=next.toISOString().slice(0,10)===d?run+1:1}else run=1;best=Math.max(best,run)}else run=0;last=d}if(days.length){const [d,g]=days[days.length-1];const today=wtcDateKey(),y=new Date();y.setUTCDate(y.getUTCDate()-1);const yk=y.toISOString().slice(0,10);current=(g.solved&&(d===today||d===yk))?run:0}return {played:days.length,solved,current,best,avg:solved?(totalGuess/solved):0}}
function wtcOptions(q){const s=String(q||'').trim().toLowerCase();if(!s)return [];return wtcEligibleCards().filter(c=>c.name.toLowerCase().includes(s)).slice(0,8)}
function wtcSuggestions(){const input=document.getElementById('wtcGuess'),root=document.getElementById('wtcSuggestions');if(!input||!root)return;const opts=wtcOptions(input.value);root.innerHTML=opts.map(c=>`<button type="button" onclick="wtcPick(${JSON.stringify(c.name).replace(/"/g,'&quot;')})">${esc(c.name)}</button>`).join('');root.hidden=!opts.length}
function wtcPick(name){const input=document.getElementById('wtcGuess');if(input)input.value=name;const root=document.getElementById('wtcSuggestions');if(root)root.hidden=true}
function wtcSubmit(){const card=wtcDailyCard();if(!card)return ppcNotice('The card database is still loading. Try again in a moment.');const input=document.getElementById('wtcGuess'),guess=String(input?.value||'').trim();if(!guess)return ppcNotice('Choose a card name first.');const match=wtcEligibleCards().find(c=>c.name.toLowerCase()===guess.toLowerCase());if(!match)return ppcNotice('Choose a card from the Pocket card database.');const ctx=wtcGame();if(ctx.game.completed)return;ctx.game.guesses=ctx.game.guesses||[];if(ctx.game.guesses.some(x=>x.toLowerCase()===match.name.toLowerCase()))return ppcNotice('You already guessed that card.');ctx.game.guesses.push(match.name);if(match.name.toLowerCase()===card.name.toLowerCase()){ctx.game.solved=true;ctx.game.completed=true;ctx.game.stars=Math.max(1,6-ctx.game.guesses.length)}else if(ctx.game.guesses.length>=5){ctx.game.failed=true;ctx.game.completed=true;ctx.game.stars=0}wtcSave(ctx);trainingPage();if(ctx.game.completed){trainingChallengeRefresh();trainingCloudSync(true)}}
function wtcShare(){const {game}=wtcGame();if(!game.completed)return;const result=game.solved?'★'.repeat(game.stars)+'☆'.repeat(5-game.stars):'☆☆☆☆☆';const text=`Pocket Companion — What's This Card? ${wtcDateKey()}\n${result} ${game.solved?game.guesses.length+'/5':'X/5'}\nNo spoilers.`;navigator.clipboard?.writeText(text).then(()=>ppcNotice('Spoiler-free result copied.')).catch(()=>ppcNotice(text))}
function wtcResetToday(){if(!confirm('Reset today’s local puzzle progress on this browser?'))return;const db=wtcRead();delete db.days?.[wtcDateKey()];wtcWrite(db);trainingPage()}


/* V8.61.1 curated competitive brain teasers.
   Puzzles intentionally use board-state facts supplied by the puzzle itself instead of
   inventing or paraphrasing live card effects. Future effect-aware puzzles must resolve
   every referenced effect from the canonical card database before becoming playable. */
const BRAIN_STORE='ppc_brain_teasers_v8611';
const BRAIN_PUZZLES=[
 {id:'best-001',type:'Best Move',title:'Protect the two-point lead',difficulty:'Intermediate',prompt:'You lead 2–1. Your Active Pokémon can retreat safely. Your opponent’s Active is worth 1 point and can be Knocked Out this turn. A Benched Pokémon is worth 2 points, but you cannot Knock it Out this turn.',choices:['Take the guaranteed 1-point Knock Out now','Ignore the Active and set up for the 2-point Pokémon next turn','Retreat and end the turn without attacking'],answer:0,why:'The guaranteed Knock Out reaches 3 points immediately. Passing the win for a possible higher-value target adds unnecessary risk.'},
 {id:'best-002',type:'Best Move',title:'Do not give away the race',difficulty:'Beginner',prompt:'The score is 2–2. You can Knock Out the opponent’s Active this turn for the final point. You also have an optional setup play that does not change whether the Knock Out succeeds.',choices:['Take the winning Knock Out first','Use every optional setup action before attacking','End the turn to preserve resources'],answer:0,why:'When the winning Knock Out is already guaranteed, take it. Extra actions cannot improve a game that ends now and can create avoidable mistakes.'},
 {id:'misplay-001',type:'Find the Misplay',title:'The unnecessary retreat',difficulty:'Beginner',prompt:'You are ahead 2–1. Your Active can Knock Out the opponent’s 1-point Active right now. Instead, you spend your retreat resource, move to a Benched attacker, and fail to Knock Out anything.',choices:['Keeping the winning attacker Active','Retreating away from a guaranteed game-winning Knock Out','Having a Benched attacker ready'],answer:1,why:'The retreat gives up an immediate winning line. Competitive sequencing starts by checking whether the game can be ended before spending resources.'},
 {id:'misplay-002',type:'Find the Misplay',title:'Damage before math',difficulty:'Intermediate',prompt:'An opposing Pokémon has 120 HP remaining. Your available attack deals 100 damage. A legal +20 damage modifier is available this turn, but the player attacks before using it.',choices:['Attacking before applying the available +20 modifier','Checking the opponent’s remaining HP','Planning around a 120-damage threshold'],answer:0,why:'100 damage misses the 120-HP threshold. The known +20 modifier must be applied before the attack to reach the Knock Out.'},
 {id:'ko-001',type:'KO Math',title:'Exact damage',difficulty:'Beginner',prompt:'The opposing Active has 130 HP remaining. Your attack deals 110 damage and you have a legal +20 damage modifier available this turn. Is the Knock Out available?',choices:['Yes — 130 total damage is enough','No — it is 10 damage short','No — it is 20 damage short'],answer:0,why:'110 + 20 = 130, exactly matching the remaining HP.'},
 {id:'ko-002',type:'KO Math',title:'Count the shortfall',difficulty:'Beginner',prompt:'The opposing Active has 150 HP remaining. Your attack deals 120 damage. You can add 20 damage this turn. How much damage are you still short?',choices:['0','10','30'],answer:1,why:'120 + 20 = 140. Against 150 remaining HP, the attack is 10 damage short.'},
 {id:'ko-003',type:'KO Math',title:'Two modifiers',difficulty:'Intermediate',prompt:'The opposing Active has 170 HP remaining. Your attack deals 130 damage. Two separate legal modifiers add +20 damage each and can both be used this turn. What is the result?',choices:['150 damage — no Knock Out','170 damage — exact Knock Out','190 damage — Knock Out'],answer:1,why:'130 + 20 + 20 = 170, exactly enough for the Knock Out.'},
 {id:'seq-001',type:'Sequencing',title:'Secure information first',difficulty:'Beginner',prompt:'You have one action that reveals useful information before you must choose between two legal setup lines. Neither setup line is lost by checking the information first.',choices:['Choose a setup line immediately','Use the information-gathering action first, then choose','Skip both setup lines'],answer:1,why:'When a legal information action does not cost access to your later choices, using it first lets you make the setup decision with more information.'},
 {id:'seq-002',type:'Sequencing',title:'Do not spend the escape first',difficulty:'Intermediate',prompt:'Your Active can take a guaranteed Knock Out. You also have a limited retreat option available, but retreating first would move the attacker that can take the Knock Out to the Bench.',choices:['Retreat first because movement should always come before attacking','Take the guaranteed Knock Out without spending the retreat option','End the turn and save every resource'],answer:1,why:'Check the winning or scoring line before spending a limited movement resource. The retreat is unnecessary when the Active already completes the objective.'},
 {id:'energy-001',type:'Energy Management',title:'Fund the immediate attacker',difficulty:'Beginner',prompt:'Attacker A needs one more Energy to use its required attack this turn. Attacker B is already fully funded for its role. You can attach one Energy this turn.',choices:['Attach to Attacker A','Attach to already-funded Attacker B','Do not attach Energy'],answer:0,why:'The attachment immediately turns Attacker A online while Attacker B already has what it needs. Prioritize the attachment that changes your available line this turn.'},
 {id:'energy-002',type:'Energy Management',title:'Plan the next attacker',difficulty:'Intermediate',prompt:'Your Active is already fully funded and can attack this turn. A Benched attacker needs one Energy now and one on a later turn to become ready. You have one attachment available and no stated reason to overfund the Active.',choices:['Add extra Energy to the already-funded Active','Attach to the Benched attacker to begin preparing it','Skip the attachment'],answer:1,why:'With the current attacker already funded, starting the next attacker improves future readiness instead of placing an unnecessary extra resource on the Active.'},
 {id:'retreat-001',type:'Retreat Decisions',title:'Retreat to preserve the point race',difficulty:'Beginner',prompt:'Your Active cannot take a Knock Out this turn and will be Knocked Out by the opponent next turn if it stays Active. You have a legal retreat into a healthy Benched Pokémon, and the puzzle states there is no penalty for making that retreat.',choices:['Stay Active and give up the Knock Out','Retreat to the healthy Benched Pokémon','Concede immediately'],answer:1,why:'Under the stated facts, retreating prevents a guaranteed point loss without giving up a current Knock Out.'},
 {id:'retreat-002',type:'Retreat Decisions',title:'Do not retreat away from lethal',difficulty:'Intermediate',prompt:'The score is 2–2. Your Active has a guaranteed attack that Knocks Out the opponent’s 1-point Active this turn. You also have a legal retreat available.',choices:['Retreat to protect the Active','Take the game-winning Knock Out','Retreat and wait one turn'],answer:1,why:'A guaranteed final point ends the game now. Retreating only introduces risk and cannot improve on an immediate win.'},
 {id:'matchup-001',type:'Matchup Puzzles',title:'Attack the exposed weakness',difficulty:'Beginner',prompt:'For this scenario only: your opponent’s Active takes +20 damage from your Lightning attacker. Your Lightning attack deals 110 before the stated weakness bonus. The opposing Active has 130 HP remaining. Your alternative attacker deals 120 with no bonus.',choices:['Use the Lightning attacker for 130 total damage','Use the 120-damage attacker','Pass the attack and set up'],answer:0,why:'The puzzle explicitly gives a +20 matchup bonus. 110 + 20 = 130, so the Lightning line reaches the exact Knock Out.'},
 {id:'matchup-002',type:'Matchup Puzzles',title:'Play the point race, not the biggest target',difficulty:'Intermediate',prompt:'You are ahead 2–1. The opponent has a 1-point Active you can Knock Out now and a 2-point Benched threat you cannot Knock Out this turn. No effect in this scenario can move or damage the Bench.',choices:['Take the available 1-point Active Knock Out and win','Skip the Active to prepare for the 2-point threat','Retreat and wait for a better target'],answer:0,why:'The matchup objective is the point race. The available 1-point Knock Out immediately reaches 3 points, while the larger target is not currently reachable.'},
 {id:'opening-001',type:'Opening Hand',title:'Build the playable line',difficulty:'Beginner',prompt:'Your opening options include a Basic Pokémon you can place into play now, a future attacker that cannot be played without its required earlier stage, and a utility card that does not create a Pokémon by itself. The scenario gives no other playable Pokémon.',choices:['Start with the playable Basic Pokémon','Keep only the future attacker and hope','Use the utility card instead of establishing a Pokémon'],answer:0,why:'Under the stated opening-hand facts, the Basic is the only option that establishes a legal board immediately. Prioritize the line you can actually play.'},
 {id:'opening-002',type:'Opening Hand',title:'Do not spend the flexible resource yet',difficulty:'Intermediate',prompt:'You have a stable opening board and one flexible resource that can support either of two future lines. You do not yet know which line the opponent will force, and saving the resource this turn does not cost you an attack or setup action.',choices:['Commit the flexible resource immediately to Line A','Commit it immediately to Line B','Preserve the flexible resource until you have information'],answer:2,why:'Because waiting has no stated opportunity cost, preserving flexibility avoids committing to a line before the information needed to choose between them exists.'},
 {id:'endgame-001',type:'Endgame Training',title:'Take the final point now',difficulty:'Beginner',prompt:'The score is 2–2. Your Active can take a guaranteed 1-point Knock Out this turn. A different line could prepare a stronger board for next turn, but it does not score this turn.',choices:['Take the guaranteed final point','Prepare the stronger board and pass the Knock Out','Retreat to preserve your attacker'],answer:0,why:'At 2–2, the guaranteed 1-point Knock Out ends the game. Future board strength has no value after an immediate winning line.'},
 {id:'endgame-002',type:'Endgame Training',title:'Deny the return Knock Out',difficulty:'Intermediate',prompt:'You lead 2–1. You cannot score this turn. If your damaged 2-point Active stays in play, the opponent has a stated guaranteed Knock Out next turn and wins 3–2. You have a legal retreat to a healthy 1-point Pokémon, and the scenario states the opponent cannot Knock it Out next turn.',choices:['Leave the 2-point Active in place','Retreat to the healthy 1-point Pokémon','Concede because you cannot score this turn'],answer:1,why:'The retreat removes the opponent’s stated immediate winning line. Endgame play includes denying the exact points the opponent needs, not only maximizing your own damage.'}
];
function brainRead(){try{return JSON.parse(localStorage.getItem(BRAIN_STORE)||'{}')||{}}catch{return {}}}
function brainWrite(v){try{localStorage.setItem(BRAIN_STORE,JSON.stringify(v))}catch(e){console.warn('Brain teaser progress could not be saved',e)}}
function brainPuzzle(id){return BRAIN_PUZZLES.find(p=>p.id===id)||BRAIN_PUZZLES[0]}
function brainAnswer(id,choice){const db=brainRead(),p=brainPuzzle(id);db.answers=db.answers||{};if(db.answers[id])return;db.answers[id]={choice:Number(choice),correct:Number(choice)===p.answer,at:new Date().toISOString()};brainWrite(db);trainingChallengeRefresh();trainingPage();trainingCloudSync(true)}
function brainReset(){if(!confirm('Reset your local Brain Teaser progress on this browser?'))return;localStorage.removeItem(BRAIN_STORE);trainingPage()}
function brainStats(){const a=Object.values(brainRead().answers||{}),correct=a.filter(x=>x.correct).length;return {done:a.length,correct,accuracy:a.length?Math.round(correct/a.length*100):0}}
function brainCard(p){const a=brainRead().answers?.[p.id];return `<article class="brainCard ${a?'answered':''}"><div class="between"><span class="badge">${esc(p.type)}</span><span class="brainDifficulty">${esc(p.difficulty)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.prompt)}</p><div class="brainChoices">${p.choices.map((c,i)=>`<button class="brainChoice ${a?(i===p.answer?'correct':(i===a.choice?'wrong':'')):''}" ${a?'disabled':''} onclick="brainAnswer('${p.id}',${i})"><span>${String.fromCharCode(65+i)}</span>${esc(c)}</button>`).join('')}</div>${a?`<div class="brainExplain ${a.correct?'correct':'wrong'}"><strong>${a.correct?'Correct':'Not quite'}</strong><p>${esc(p.why)}</p></div>`:''}</article>`}
function brainSection(){const st=brainStats();return `<section class="brainTraining"><div class="brainHeader"><div><span class="eyebrow">V8.61.4 • COMPETITIVE TRAINING</span><h2>Competitive Brain Teasers</h2><p>Practice decisions, sequencing awareness, and damage math with curated scenarios. Puzzle facts are explicit so the trainer never invents a card effect.</p></div><div class="brainScore"><strong>${st.correct}/${st.done||0}</strong><span>${st.done?st.accuracy+'% accuracy':'Start training'}</span></div></div><div class="brainTabs"><span>Best Move</span><span>Find the Misplay</span><span>KO Math</span><span>Sequencing</span><span>Energy Management</span><span>Retreat Decisions</span><span>Matchup Puzzles</span><span>Opening Hand</span><span>Endgame Training</span></div><div class="brainGrid">${BRAIN_PUZZLES.map(brainCard).join('')}</div><div class="brainFooter"><span>${st.done} of ${BRAIN_PUZZLES.length} completed</span><button class="secondary" onclick="brainReset()">Reset Brain Teasers</button></div></section>`}


/* V8.61.4 — signed-in cloud continuity + training profile/achievements.
   Guest play stays local. Cloud sync only stores completed daily results and answered curated puzzles. */
const TRAINING_ACHIEVEMENTS={
 first_training:['First Rep','Complete your first training activity.','✦'],
 brain_starter:['Brain Starter','Complete 5 Brain Teasers.','5'],
 brain_veteran:['Brain Veteran','Complete 15 Brain Teasers.','15'],
 sharp_eye:['Sharp Eye','Solve What’s This Card? once.','◉'],
 five_star_sleuth:['Five-Star Sleuth','Solve the daily card on guess one.','★★★★★'],
 mode_explorer:['Mode Explorer','Train in 6 different Brain Teaser modes.','6'],
 complete_competitor:['Complete Competitor','Train in all 9 Brain Teaser modes.','9'],
 perfect_ten:['Perfect Ten','Get your first 10 Brain Teasers correct.','10/10']
};
const trainingCloud={loading:false,loaded:false,error:'',profile:null,achievements:[],showcase:[]};
function trainingSigned(){try{return typeof ptSigned==='function'&&ptSigned()}catch{return false}}
function trainingLocalProfile(){const w=wtcStats(),b=brainStats(),ans=brainRead().answers||{},modes=new Set(Object.keys(ans).map(id=>brainPuzzle(id)?.type).filter(Boolean));const bestStars=Math.max(0,...Object.values(wtcRead().days||{}).map(g=>Number(g?.stars||0)));const ach=trainingLocalAchievements(),st=trainingStreaks(),dailyBonus=Object.values(trainingDailyRead()).reduce((sum,d)=>sum+Object.keys(d?.claimed||{}).reduce((n,k)=>n+({daily_card:10,daily_solve:20,daily_precision:30,brain_rep:15}[k]||0),0),0);return {daily_played:w.played,daily_solved:w.solved,daily_best_stars:bestStars,brain_completed:b.done,brain_correct:b.correct,brain_accuracy:b.accuracy,modes_completed:modes.size,achievement_count:ach.length,training_streak:st.current,best_training_streak:st.best,training_xp:w.played*20+w.solved*20+bestStars*5+b.done*10+b.correct*10+ach.length*25+dailyBonus}}
function trainingLocalAchievements(){const w=wtcStats(),ans=brainRead().answers||{},rows=Object.entries(ans),correct=rows.filter(([,a])=>a.correct).length,modes=new Set(rows.map(([id])=>brainPuzzle(id)?.type).filter(Boolean)).size,five=Object.values(wtcRead().days||{}).some(g=>g?.solved&&Number(g.stars)===5);return [['first_training',rows.length+w.solved>=1],['brain_starter',rows.length>=5],['brain_veteran',rows.length>=15],['sharp_eye',w.solved>=1],['five_star_sleuth',five],['mode_explorer',modes>=6],['complete_competitor',modes>=9],['perfect_ten',rows.length>=10&&correct>=10]].filter(x=>x[1]).map(x=>({achievement_key:x[0]}))}
function trainingLevel(xp){return Math.max(1,Math.floor(Number(xp||0)/150)+1)}
async function trainingCloudPush(c,uid){const days=Object.entries(wtcRead().days||{}).filter(([,g])=>g?.completed).map(([d,g])=>({user_id:uid,puzzle_date:d,card_id:String((wtcHash('PocketCompanion|'+d))),solved:!!g.solved,guesses:Math.min(5,Number(g.guesses?.length||0)),stars:Math.min(5,Number(g.stars||0)),completed_at:new Date().toISOString()}));if(days.length){const r=await c.from('training_daily_card_results').upsert(days,{onConflict:'user_id,puzzle_date'});if(r.error)throw r.error}const answers=brainRead().answers||{};const brain=Object.entries(answers).map(([id,a])=>{const p=brainPuzzle(id);return {user_id:uid,puzzle_id:id,puzzle_type:p?.type||'Unknown',choice:Number(a.choice||0),correct:!!a.correct,answered_at:a.at||new Date().toISOString()}});if(brain.length){const r=await c.from('training_brain_results').upsert(brain,{onConflict:'user_id,puzzle_id'});if(r.error)throw r.error}}
async function trainingCloudPull(c,uid){const [dr,br]=await Promise.all([c.from('training_daily_card_results').select('*').eq('user_id',uid).order('puzzle_date'),c.from('training_brain_results').select('*').eq('user_id',uid)]);if(dr.error)throw dr.error;if(br.error)throw br.error;const wd=wtcRead();wd.days=wd.days||{};(dr.data||[]).forEach(r=>{const d=String(r.puzzle_date);wd.days[d]={guesses:Array.from({length:Number(r.guesses||0)},(_,i)=>`Cloud guess ${i+1}`),solved:!!r.solved,failed:!r.solved,completed:true,stars:Number(r.stars||0),cloud:true}});wtcWrite(wd);const bd=brainRead();bd.answers=bd.answers||{};(br.data||[]).forEach(r=>{bd.answers[r.puzzle_id]={choice:Number(r.choice),correct:!!r.correct,at:r.answered_at,cloud:true}});brainWrite(bd)}
async function trainingCloudSync(force=false){if(!trainingSigned()||trainingCloud.loading)return;if(trainingCloud.loaded&&!force)return;trainingCloud.loading=true;trainingCloud.error='';try{const c=ptClient(),uid=ptSession()?.user?.id;if(!uid)throw new Error('Sign in required');await trainingCloudPush(c,uid);await trainingCloudPull(c,uid);await c.rpc('sync_my_training_achievements');const [pr,ar,sr]=await Promise.all([c.rpc('get_my_training_profile'),c.from('training_achievements').select('achievement_key,unlocked_at').eq('user_id',uid).order('unlocked_at'),c.from('training_profile_showcase').select('achievement_keys').eq('user_id',uid).maybeSingle()]);if(pr.error)throw pr.error;if(ar.error)throw ar.error;trainingCloud.profile=Array.isArray(pr.data)?pr.data[0]:pr.data;trainingCloud.achievements=ar.data||[];if(!sr.error&&Array.isArray(sr.data?.achievement_keys)){trainingCloud.showcase=sr.data.achievement_keys;trainingShowcaseWrite(trainingCloud.showcase)}trainingCloud.loaded=true}catch(e){trainingCloud.error=e?.message||String(e)}finally{trainingCloud.loading=false;if(state?.page==='training')trainingPage(false)}}


/* V8.61.5 — deterministic daily challenges, activity streaks, and achievement showcase. */
const TRAINING_DAILY_STORE='ppc_training_daily_v8615',TRAINING_SHOWCASE_STORE='ppc_training_showcase_v8615';
function trainingDailyRead(){try{return JSON.parse(localStorage.getItem(TRAINING_DAILY_STORE)||'{}')||{}}catch{return {}}}
function trainingDailyWrite(v){try{localStorage.setItem(TRAINING_DAILY_STORE,JSON.stringify(v))}catch{}}
function trainingShowcaseRead(){try{return JSON.parse(localStorage.getItem(TRAINING_SHOWCASE_STORE)||'[]')||[]}catch{return []}}
function trainingShowcaseWrite(v){try{localStorage.setItem(TRAINING_SHOWCASE_STORE,JSON.stringify(v.slice(0,3)))}catch{}}
function trainingActivityDays(){const days=new Set();Object.entries(wtcRead().days||{}).forEach(([d,g])=>{if(g?.completed)days.add(d)});Object.values(brainRead().answers||{}).forEach(a=>{if(a?.at)days.add(String(a.at).slice(0,10))});return [...days].sort()}
function trainingStreaks(){const days=trainingActivityDays(),set=new Set(days),today=wtcDateKey();let best=0,run=0,last='';for(const d of days){if(last){const x=new Date(last+'T00:00:00Z');x.setUTCDate(x.getUTCDate()+1);run=x.toISOString().slice(0,10)===d?run+1:1}else run=1;best=Math.max(best,run);last=d}let current=0,cursor=new Date(today+'T00:00:00Z');if(!set.has(today)){cursor.setUTCDate(cursor.getUTCDate()-1);if(!set.has(cursor.toISOString().slice(0,10)))return {current:0,best,days:days.length}}while(set.has(cursor.toISOString().slice(0,10))){current++;cursor.setUTCDate(cursor.getUTCDate()-1)}return {current,best,days:days.length}}
function trainingChallengeState(){const day=wtcDateKey(),g=wtcRead().days?.[day]||{},answers=Object.values(brainRead().answers||{}),brainToday=answers.some(a=>String(a?.at||'').slice(0,10)===day),tasks=[{key:'daily_card',label:'Complete today’s What’s This Card?',xp:10,done:!!g.completed},{key:'daily_solve',label:'Solve today’s mystery card',xp:20,done:!!g.solved},{key:'daily_precision',label:'Solve it in 3 guesses or fewer',xp:30,done:!!g.solved&&Number(g.guesses?.length||99)<=3},{key:'brain_rep',label:'Complete a Brain Teaser today',xp:15,done:brainToday}];const db=trainingDailyRead();db[day]=db[day]||{claimed:{}};tasks.forEach(t=>{if(t.done)db[day].claimed[t.key]=true});trainingDailyWrite(db);return {day,tasks,complete:tasks.filter(t=>t.done).length,total:tasks.length,bonus:tasks.filter(t=>t.done).reduce((n,t)=>n+t.xp,0)}}
function trainingChallengeRefresh(){trainingChallengeState()}
function trainingDailyHtml(){const d=trainingChallengeState();return `<section class="panel trainingDailyChallenges"><div class="between"><div><span class="eyebrow">DAILY CHALLENGES</span><h2>${d.complete}/${d.total} complete</h2></div><span class="pill ${d.complete===d.total?'ready':''}">+${d.bonus} XP TODAY</span></div><div class="trainingChallengeGrid">${d.tasks.map(t=>`<article class="${t.done?'done':''}"><b>${t.done?'✓':'○'}</b><div><strong>${esc(t.label)}</strong><small>+${t.xp} Training XP</small></div></article>`).join('')}</div><p class="muted tiny">Challenges reset with the global daily card. Training streaks count any day with a completed daily card or Brain Teaser.</p></section>`}
function trainingShowcaseToggle(key){const unlocked=trainingSigned()&&trainingCloud.loaded?trainingCloud.achievements:trainingLocalAchievements();if(!unlocked.some(a=>a.achievement_key===key))return ppcNotice('Unlock this achievement before showcasing it.');let v=trainingShowcaseRead();if(v.includes(key))v=v.filter(x=>x!==key);else{if(v.length>=3)return ppcNotice('Your showcase can hold up to 3 achievements.');v.push(key)}trainingShowcaseWrite(v);trainingCloud.showcase=v;trainingPage();trainingShowcaseCloudSave()}
async function trainingShowcaseCloudSave(){if(!trainingSigned())return;try{const c=ptClient(),uid=ptSession()?.user?.id;if(!uid)return;await c.from('training_profile_showcase').upsert({user_id:uid,achievement_keys:trainingShowcaseRead(),updated_at:new Date().toISOString()},{onConflict:'user_id'})}catch(e){console.warn('Showcase cloud save failed',e)}}
function trainingShowcaseHtml(ach){const selected=trainingShowcaseRead();return `<section class="panel trainingShowcase"><div class="between"><div><span class="eyebrow">PROFILE SHOWCASE</span><h2>Featured achievements</h2></div><span class="pill">${selected.length}/3 FEATURED</span></div><p class="muted">Choose up to three unlocked achievements to represent your Training Profile.</p><div class="trainingShowcaseGrid">${Object.entries(TRAINING_ACHIEVEMENTS).filter(([k])=>ach.some(a=>a.achievement_key===k)).map(([k,v])=>`<button class="${selected.includes(k)?'selected':''}" onclick="trainingShowcaseToggle('${k}')"><b>${v[2]}</b><span><strong>${esc(v[0])}</strong><small>${selected.includes(k)?'Featured':'Add to showcase'}</small></span></button>`).join('')||'<div class="identityEmpty">Unlock an achievement to start your showcase.</div>'}</div></section>`}
function trainingProfileHtml(){const signed=trainingSigned(),p=signed&&trainingCloud.profile?trainingCloud.profile:trainingLocalProfile(),ach=signed&&trainingCloud.loaded?trainingCloud.achievements:trainingLocalAchievements(),level=trainingLevel(p.training_xp),st=trainingStreaks();return `<section class="panel trainingProfile"><div class="between"><div><span class="eyebrow">TRAINING PROFILE</span><h2>Level ${level}</h2></div><span class="pill ${signed?'ready':''}">${signed?(trainingCloud.loading?'SYNCING':'CLOUD SYNC'):'GUEST • LOCAL'}</span></div><div class="trainingProfileStats"><div><strong>${Number(p.training_xp||0)}</strong><span>Training XP</span></div><div><strong>${st.current}</strong><span>Training streak</span></div><div><strong>${Number(p.brain_accuracy||0)}%</strong><span>Accuracy</span></div><div><strong>${Number(p.modes_completed||0)}/9</strong><span>Modes trained</span></div></div><div class="trainingStreakLine"><span>🔥 Current ${st.current} day${st.current===1?'':'s'}</span><span>🏆 Best ${st.best} day${st.best===1?'':'s'}</span><span>📅 ${st.days} active training days</span></div>${trainingCloud.error&&signed?`<div class="notice">Cloud sync issue: ${esc(trainingCloud.error)}</div>`:''}<p class="muted tiny">${signed?'Completed training is backed up to your account and restored across signed-in devices.':'Guest progress stays in this browser. Sign in to back up and carry training stats across devices.'}</p></section><section class="panel trainingAchievements"><div class="between"><div><span class="eyebrow">ACHIEVEMENTS</span><h2>${ach.length} unlocked</h2></div>${signed?`<button class="secondary" onclick="trainingCloudSync(true)">Sync</button>`:''}</div><div class="trainingAchievementGrid">${Object.entries(TRAINING_ACHIEVEMENTS).map(([key,v])=>{const unlocked=ach.some(a=>a.achievement_key===key);return `<article class="${unlocked?'unlocked':'locked'}"><b>${v[2]}</b><div><strong>${esc(v[0])}</strong><small>${esc(v[1])}</small></div></article>`}).join('')}</div></section>${trainingShowcaseHtml(ach)}`}

function trainingPage(){
 const root=document.getElementById('app');if(!root)return;
 if(!cardsRequested||!cardsLoadedOnline){loadCards().then(()=>{if(state.page==='training')trainingPage()}).catch(()=>{});}
 const card=wtcDailyCard(),ctx=wtcGame(),g=ctx.game,attempt=wtcAttempt(),stats=wtcStats(),done=g.completed;
 const img=card?(card.fullImageUrl||card.thumbnailUrl||card.image||''):'';
 const history=g.cloud?'':(g.guesses||[]).map((x,i)=>`<div class="wtcGuessRow ${x.toLowerCase()===String(card?.name||'').toLowerCase()?'correct':'wrong'}"><span>Guess ${i+1}</span><strong>${esc(x)}</strong><b>${x.toLowerCase()===String(card?.name||'').toLowerCase()?'✓':'×'}</b></div>`).join('');
 if(trainingSigned()&&!trainingCloud.loaded&&!trainingCloud.loading)setTimeout(()=>trainingCloudSync(false),0);
 root.innerHTML=`<div class="trainingHero"><div><span class="eyebrow">V8.61 • DAILY TRAINING</span><h1>What’s This Card?</h1><p>One global Pocket card every day. You get five guesses; every miss reveals more of the artwork.</p></div><div class="wtcDate">${esc(ctx.day)}</div></div>
 <div class="wtcLayout"><section class="panel wtcGame"><div class="between"><div><span class="badge">${done?'REVEAL':`GUESS ${attempt} OF 5`}</span><h2>${done?(g.solved?'You got it!':'Card revealed'):'Identify the card'}</h2></div><div class="wtcStars">${done?(g.solved?'★'.repeat(g.stars)+'☆'.repeat(5-g.stars):'☆☆☆☆☆'):'●'.repeat(g.guesses.length)+'○'.repeat(5-g.guesses.length)}</div></div>
 ${card&&img?`<div class="wtcArtFrame ${done?'revealed':''}"><img src="${esc(img)}" alt="${done?esc(card.name):'Zoomed mystery card artwork'}" style="--wtc-zoom:${done?1:wtcZoomForAttempt(attempt)}" onerror="this.closest('.wtcArtFrame').classList.add('imageError')"><div class="wtcMask top"></div><div class="wtcMask bottom"></div><div class="wtcImageError">Card artwork could not load.</div></div>`:`<div class="wtcLoading"><strong>Loading today’s Pocket card…</strong><span>The canonical card database is required so the puzzle never invents a card.</span></div>`}
 ${done&&card?`<div class="wtcReveal"><span class="eyebrow">TODAY’S CARD</span><h2>${esc(card.name)}</h2><p>${esc(card.setName||card.setCode||'Pokémon TCG Pocket')} ${card.rarity?`• ${esc(card.rarity)}`:''}</p><div class="row"><button onclick="openCardModal('${esc(card.id)}')">View Card</button><button class="secondary" onclick="wtcShare()">Copy Spoiler-Free Result</button></div></div>`:`<div class="wtcGuessBox"><label for="wtcGuess">Your guess</label><div class="wtcInputRow"><div class="wtcAutocomplete"><input id="wtcGuess" autocomplete="off" placeholder="Start typing a card name…" oninput="wtcSuggestions()" onkeydown="if(event.key==='Enter'){event.preventDefault();wtcSubmit()}"><div id="wtcSuggestions" class="wtcSuggestions" hidden></div></div><button onclick="wtcSubmit()" ${card?'':'disabled'}>Submit Guess</button></div><small>Only real cards from Pocket Companion’s canonical card database can be submitted.</small></div>`}
 ${history?`<div class="wtcHistory"><h3>Your guesses</h3>${history}</div>`:''}</section>
 <aside><section class="panel"><span class="eyebrow">DAILY STATS</span><div class="wtcStatGrid"><div><strong>${stats.current}</strong><span>Current streak</span></div><div><strong>${stats.best}</strong><span>Best streak</span></div><div><strong>${stats.solved}</strong><span>Cards solved</span></div><div><strong>${stats.avg?stats.avg.toFixed(1):'—'}</strong><span>Avg. guess</span></div></div><p class="muted tiny">Daily results contribute to your V8.61.5 Training Profile and daily challenges. Signed-in players get cloud backup; guests remain local.</p></section>
 <section class="panel"><span class="eyebrow">COMPETITIVE TRAINING</span><h2>Brain Teasers Live</h2><p class="muted">V8.61.5 connects all nine competitive modes to your Training Profile while preserving the curated puzzle library. Every scenario supplies the facts needed to solve it without inventing card effects.</p><div class="wtcComing">9 MODES LIVE</div></section>
 <section class="panel"><button class="secondary" onclick="wtcResetToday()">Reset Today’s Local Puzzle</button></section></aside></div>${trainingDailyHtml()}${trainingProfileHtml()}${brainSection()}`;
}
window.trainingPage=trainingPage;

window.brainAnswer=brainAnswer;window.brainReset=brainReset;window.trainingCloudSync=trainingCloudSync;window.trainingShowcaseToggle=trainingShowcaseToggle;
