/* PocketNexus V8.69.0 — validated Pokemon Zone Card Service + Updates area.
   Only validated staging data is exposed. Production card tables are not written by this feature. */
(function(){
'use strict';
if(window.PPCUpdates)return;
const updatesState={loading:false,loaded:false,error:'',feed:null,tab:'overview'};
const escU=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function fmtDate(v){if(!v)return'Unknown';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function updateKindLabel(k){const x=String(k||'update').toLowerCase();if(x.includes('event'))return'Event';if(x.includes('set'))return'Set';if(x.includes('card'))return'Cards';if(x.includes('shop'))return'Shop';if(x.includes('rank'))return'Ranked';return'Game Update'}
async function updatesLoad(force=false){if(updatesState.loading)return;if(updatesState.loaded&&!force)return;updatesState.loading=true;updatesState.error='';try{updatesState.feed=await CardService.fetchValidatedPokemonZoneFeed({force});updatesState.loaded=true}catch(e){updatesState.error=e?.message||String(e)}finally{updatesState.loading=false;if(state?.page==='updates')updatesPage(true)}}
function updatesSetTab(tab){updatesState.tab=['overview','sets','cards','events'].includes(tab)?tab:'overview';updatesPage(true)}
function sourceStatusHtml(feed){const s=feed?.sourceStatus||{},run=s.latestRun;return `<section class="panel pnUpdateStatus"><div class="between"><div><span class="eyebrow">SOURCE PIPELINE</span><h2>Pokemon Zone validation feed</h2></div><span class="badge ${Number(s.validatedCards||0)>0?'good':''}">${Number(s.validatedCards||0)} validated cards</span></div><div class="pnUpdateStats"><div><strong>${Number(s.validatedSets||0)}</strong><span>Validated sets</span></div><div><strong>${Number(s.validatedCards||0)}</strong><span>Validated cards</span></div><div><strong>${Number(s.validatedUpdates||0)}</strong><span>Validated updates</span></div><div><strong>${run?.status?escU(String(run.status).toUpperCase()):'WAITING'}</strong><span>Latest collector run</span></div></div><p class="muted tiny">Only records that passed PocketNexus validation appear here. Staging data never overwrites the production Card Database automatically.</p></section>`}
function setsHtml(feed){const sets=feed?.sets||[];return `<section class="panel"><div class="between"><div><span class="eyebrow">SETS</span><h2>Validated expansions</h2></div><span class="pill">${sets.length}</span></div>${sets.length?`<div class="pnUpdateList">${sets.map(s=>`<article><div><strong>${escU(s.name||s.set_code)}</strong><span>${escU(s.set_code||'')} • ${fmtDate(s.release_date)}</span></div><div class="pnUpdateRight"><b>${Number(s.cards_found||0)}/${Number(s.expected_cards||0)||'?'}</b><span>${escU(s.validation_status||'validated')}</span></div></article>`).join('')}</div>`:`<div class="identityEmpty">No validated Pokemon Zone sets are available yet. The page will populate automatically after a collector run passes validation.</div>`}</section>`}
function cardsHtml(feed){const cards=feed?.cards||[],recent=cards.slice(-24).reverse();return `<section class="panel"><div class="between"><div><span class="eyebrow">CARDS</span><h2>Newest validated card records</h2></div><span class="pill">${cards.length} total</span></div>${recent.length?`<div class="pnCardFeed">${recent.map(c=>`<article><span class="pnCardNum">${escU(c.set_code)} #${String(c.card_number||'').padStart(3,'0')}</span><strong>${escU(c.name)}</strong><small>${escU(c.card_kind||'Card')}${c.rarity?` • ${escU(c.rarity)}`:''}</small></article>`).join('')}</div>`:`<div class="identityEmpty">No validated Pokemon Zone card records are available yet.</div>`}</section>`}
function eventsHtml(feed){const rows=feed?.updates||[];return `<section class="panel"><div class="between"><div><span class="eyebrow">EVENTS + GAME UPDATES</span><h2>Validated game changes</h2></div><span class="pill">${rows.length}</span></div>${rows.length?`<div class="pnUpdateTimeline">${rows.map(x=>`<article><span class="badge">${escU(updateKindLabel(x.update_kind))}</span><div><strong>${escU(x.title||'Pokemon TCG Pocket update')}</strong><small>${x.starts_at?`Starts ${fmtDate(x.starts_at)}`:'Date not supplied'}${x.ends_at?` • Ends ${fmtDate(x.ends_at)}`:''}</small></div></article>`).join('')}</div>`:`<div class="identityEmpty">The update collector has not produced validated event/news records yet. Nothing unverified is shown to users.</div>`}</section>`}
function overviewHtml(feed){const sets=feed?.sets||[],updates=feed?.updates||[],latestSet=sets[0],recent=updates.slice(0,5);return `${sourceStatusHtml(feed)}<div class="pnUpdatesGrid"><section class="panel"><span class="eyebrow">LATEST VALIDATED SET</span>${latestSet?`<h2>${escU(latestSet.name||latestSet.set_code)}</h2><p class="muted">${escU(latestSet.set_code)} • ${fmtDate(latestSet.release_date)}</p><div class="pnBigMetric">${Number(latestSet.cards_found||0)}<span>cards validated</span></div>`:`<h2>Waiting for first validated set</h2><p class="muted">The Card Service will adopt new records only after the collector passes its validation gate.</p>`}</section><section class="panel"><span class="eyebrow">RECENT UPDATES</span>${recent.length?`<div class="pnMiniUpdates">${recent.map(x=>`<div><b>${escU(updateKindLabel(x.update_kind))}</b><span>${escU(x.title)}</span></div>`).join('')}</div>`:`<h2>No validated updates yet</h2><p class="muted">Events and game updates will appear here after their staging records are validated.</p>`}</section></div>${setsHtml(feed)}`}
function updatesPage(skipLoad=false){const root=document.getElementById('app');if(!root)return;if(!skipLoad&&!updatesState.loaded&&!updatesState.loading)updatesLoad();const feed=updatesState.feed||{sets:[],cards:[],updates:[],sourceStatus:{}};root.innerHTML=`<div class="pnUpdatesPage"><div class="between pnUpdatesHero"><div><span class="eyebrow">POCKETNEXUS UPDATES</span><h1>Cards, sets, events, and game updates</h1><p class="muted">Validated Pokemon Zone information is normalized by PocketNexus before it reaches the Card Service or this page.</p></div><button class="secondary" onclick="updatesLoad(true)" ${updatesState.loading?'disabled':''}>${updatesState.loading?'Refreshing…':'Refresh'}</button></div><div class="pnUpdateTabs"><button class="${updatesState.tab==='overview'?'active':''}" onclick="updatesSetTab('overview')">Overview</button><button class="${updatesState.tab==='sets'?'active':''}" onclick="updatesSetTab('sets')">Sets</button><button class="${updatesState.tab==='cards'?'active':''}" onclick="updatesSetTab('cards')">Cards</button><button class="${updatesState.tab==='events'?'active':''}" onclick="updatesSetTab('events')">Events + Updates</button></div>${updatesState.error?`<div class="dangerBox">${escU(updatesState.error)}</div>`:''}${updatesState.loading&&!updatesState.loaded?`<section class="panel"><p class="muted">Loading validated update feed…</p></section>`:updatesState.tab==='sets'?setsHtml(feed):updatesState.tab==='cards'?cardsHtml(feed):updatesState.tab==='events'?eventsHtml(feed):overviewHtml(feed)}<p class="muted tiny pnUpdatesFoot">Pokemon Zone is used as a third-party reference source. PocketNexus remains independent and does not present unvalidated staging records as confirmed production data.</p></div>`}

// Let the existing Card DB remain the foundation, then append only validated set/number records not already present.
if(typeof loadCards==='function'){
 const baseLoadCards=loadCards;
 loadCards=async function(){const out=await baseLoadCards.apply(this,arguments);try{const hydrated=await CardService.hydrateValidatedCards(CARDS);if(hydrated?.cards?.length&&hydrated.cards.length!==CARDS.length){CARDS=hydrated.cards;cardMap=CardService.buildNameMap(CARDS);window.PPCUpdates?.markHydrated?.(CARDS.length)}}catch(e){console.warn('Validated Pokemon Zone card hydration skipped',e)}return out};
}

// Register Updates without rebuilding the existing router.
try{VALID_PAGES.add('updates')}catch{}
const baseRender=window.render;
window.render=function(){if(state?.page==='updates'){try{nav()}catch{}if(!state.user&&!cloudSession?.user)return entryScreen();return updatesPage()}return baseRender.apply(this,arguments)};

// Add Updates to existing desktop and mobile navigation while preserving current navigation code.
const baseNav=window.nav;
window.nav=function(){const out=baseNav.apply(this,arguments);try{const more=[...document.querySelectorAll('.navCategory')].find(x=>x.dataset.category==='More')?.querySelector('.navCategoryMenu');if(more&&!more.querySelector('[data-pn-updates]'))more.insertAdjacentHTML('afterbegin',`<button data-pn-updates class="navCategoryItem ${state.page==='updates'?'active':''}" role="menuitem" onclick="headerNavigate('updates')"><span class="navCategoryIcon">◫</span><span><strong>Updates</strong><small>New sets, cards, events, and game updates.</small></span></button>`)}catch{}return out};
const baseOpenMobile=window.openMobileMoreSheet;
window.openMobileMoreSheet=function(){const out=baseOpenMobile.apply(this,arguments);try{const groups=[...document.querySelectorAll('.mobileMoreGroup')],g=groups.find(x=>x.querySelector('h3')?.textContent==='UTILITIES')||groups.at(-1),grid=g?.querySelector('.mobileMoreGrid');if(grid&&!grid.querySelector('[data-pn-updates]'))grid.insertAdjacentHTML('afterbegin',`<button data-pn-updates type="button" class="mobileMoreItem ${state.page==='updates'?'active':''}" onclick="closeMobileMoreSheet();headerNavigate('updates')"><span>◫</span><strong>Updates</strong></button>`)}catch{}return out};

function injectStyle(){if(document.getElementById('pnUpdatesStyle'))return;const s=document.createElement('style');s.id='pnUpdatesStyle';s.textContent=`.pnUpdatesPage{display:grid;gap:14px}.pnUpdatesHero{align-items:flex-start}.pnUpdatesHero h1{margin:.2rem 0}.pnUpdateTabs{display:flex;gap:8px;flex-wrap:wrap}.pnUpdateTabs button{background:var(--panel);border:1px solid var(--line);color:inherit;border-radius:999px;padding:8px 12px}.pnUpdateTabs button.active{outline:2px solid rgba(96,165,250,.35)}.pnUpdateStats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:14px 0}.pnUpdateStats>div,.pnBigMetric{border:1px solid var(--line);border-radius:14px;padding:12px;background:rgba(255,255,255,.025)}.pnUpdateStats strong,.pnBigMetric{font-size:1.45rem}.pnUpdateStats span,.pnBigMetric span{display:block;font-size:.72rem;color:var(--muted);margin-top:3px}.pnUpdatesGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pnUpdateList,.pnUpdateTimeline,.pnMiniUpdates{display:grid;gap:8px;margin-top:12px}.pnUpdateList article,.pnUpdateTimeline article,.pnMiniUpdates>div{display:flex;justify-content:space-between;gap:12px;align-items:center;border:1px solid var(--line);border-radius:12px;padding:10px}.pnUpdateList article div:first-child,.pnUpdateRight,.pnUpdateTimeline article div{display:grid;gap:3px}.pnUpdateList span,.pnUpdateRight span,.pnUpdateTimeline small,.pnMiniUpdates span{color:var(--muted);font-size:.75rem}.pnUpdateRight{text-align:right}.pnCardFeed{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:12px}.pnCardFeed article{display:grid;gap:5px;border:1px solid var(--line);border-radius:12px;padding:11px}.pnCardNum{font-size:.7rem;color:var(--muted)}.pnCardFeed small{color:var(--muted)}.pnUpdatesFoot{text-align:center;padding:4px 0 12px}@media(max-width:850px){.pnUpdateStats{grid-template-columns:repeat(2,minmax(0,1fr))}.pnUpdatesGrid{grid-template-columns:1fr}.pnCardFeed{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.pnUpdatesHero{display:grid}.pnUpdateStats,.pnCardFeed{grid-template-columns:1fr}.pnUpdateTabs{overflow-x:auto;flex-wrap:nowrap}.pnUpdateTabs button{white-space:nowrap}}`;document.head.appendChild(s)}
injectStyle();
window.updatesPage=updatesPage;window.updatesLoad=updatesLoad;window.updatesSetTab=updatesSetTab;window.PPCUpdates={version:'8.69.0',state:updatesState,load:updatesLoad,page:updatesPage,markHydrated:n=>{updatesState.hydratedCardCount=n}};
})();
